<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Thomas Husson">

<title>Devoir Statistiques Avancées</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="S1_4_Modeles_files/libs/clipboard/clipboard.min.js"></script>
<script src="S1_4_Modeles_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="S1_4_Modeles_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="S1_4_Modeles_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="S1_4_Modeles_files/libs/quarto-html/popper.min.js"></script>
<script src="S1_4_Modeles_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="S1_4_Modeles_files/libs/quarto-html/anchor.min.js"></script>
<link href="S1_4_Modeles_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="S1_4_Modeles_files/libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="S1_4_Modeles_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="S1_4_Modeles_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="S1_4_Modeles_files/libs/bootstrap/bootstrap-d6a003b94517c951b2d65075d42fb01b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#modèle-linéaire" id="toc-modèle-linéaire" class="nav-link active" data-scroll-target="#modèle-linéaire"><span class="header-section-number">1</span> Modèle linéaire</a>
  <ul>
  <li><a href="#principe-et-mise-en-œuvre" id="toc-principe-et-mise-en-œuvre" class="nav-link" data-scroll-target="#principe-et-mise-en-œuvre"><span class="header-section-number">1.1</span> Principe et mise en œuvre</a></li>
  <li><a href="#exemple-avec-le-jeu-de-données-smp" id="toc-exemple-avec-le-jeu-de-données-smp" class="nav-link" data-scroll-target="#exemple-avec-le-jeu-de-données-smp"><span class="header-section-number">1.2</span> Exemple avec le jeu de données <code>smp</code></a></li>
  <li><a href="#corrélation-et-modèle-linéaire" id="toc-corrélation-et-modèle-linéaire" class="nav-link" data-scroll-target="#corrélation-et-modèle-linéaire"><span class="header-section-number">1.3</span> Corrélation et modèle linéaire</a></li>
  <li><a href="#le-test-t-un-cas-particulier-du-modèle-linéaire" id="toc-le-test-t-un-cas-particulier-du-modèle-linéaire" class="nav-link" data-scroll-target="#le-test-t-un-cas-particulier-du-modèle-linéaire"><span class="header-section-number">1.4</span> Le test t : un cas particulier du modèle linéaire</a>
  <ul>
  <li><a href="#exemple-r" id="toc-exemple-r" class="nav-link" data-scroll-target="#exemple-r"><span class="header-section-number">1.4.1</span> Exemple R</a>
  <ul class="collapse">
  <li><a href="#test-t" id="toc-test-t" class="nav-link" data-scroll-target="#test-t"><span class="header-section-number">1.4.1.1</span> Test t</a></li>
  <li><a href="#régression-linéaire" id="toc-régression-linéaire" class="nav-link" data-scroll-target="#régression-linéaire"><span class="header-section-number">1.4.1.2</span> Régression linéaire</a></li>
  </ul></li>
  <li><a href="#relation-entre-test-t-et-régression-linéaire" id="toc-relation-entre-test-t-et-régression-linéaire" class="nav-link" data-scroll-target="#relation-entre-test-t-et-régression-linéaire"><span class="header-section-number">1.4.2</span> Relation entre test t et régression linéaire</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#modèle-logistique" id="toc-modèle-logistique" class="nav-link" data-scroll-target="#modèle-logistique"><span class="header-section-number">2</span> Modèle logistique</a>
  <ul>
  <li><a href="#modèle-linéaire-inadapté-pour-cas-témoins" id="toc-modèle-linéaire-inadapté-pour-cas-témoins" class="nav-link" data-scroll-target="#modèle-linéaire-inadapté-pour-cas-témoins"><span class="header-section-number">2.1</span> Modèle linéaire inadapté pour cas témoins</a></li>
  <li><a href="#principe-et-mise-en-œuvre-1" id="toc-principe-et-mise-en-œuvre-1" class="nav-link" data-scroll-target="#principe-et-mise-en-œuvre-1"><span class="header-section-number">2.2</span> Principe et mise en œuvre</a></li>
  <li><a href="#transformation-de-y" id="toc-transformation-de-y" class="nav-link" data-scroll-target="#transformation-de-y"><span class="header-section-number">2.3</span> Transformation de Y</a>
  <ul>
  <li><a href="#odds" id="toc-odds" class="nav-link" data-scroll-target="#odds"><span class="header-section-number">2.3.1</span> Odds</a></li>
  <li><a href="#log-odds" id="toc-log-odds" class="nav-link" data-scroll-target="#log-odds"><span class="header-section-number">2.3.2</span> Log-odds</a></li>
  </ul></li>
  <li><a href="#maximum-de-vraisemblance" id="toc-maximum-de-vraisemblance" class="nav-link" data-scroll-target="#maximum-de-vraisemblance"><span class="header-section-number">2.4</span> Maximum de vraisemblance</a></li>
  <li><a href="#conditions-de-validité" id="toc-conditions-de-validité" class="nav-link" data-scroll-target="#conditions-de-validité"><span class="header-section-number">2.5</span> Conditions de validité</a></li>
  <li><a href="#exemple-r-1" id="toc-exemple-r-1" class="nav-link" data-scroll-target="#exemple-r-1"><span class="header-section-number">2.6</span> Exemple R</a>
  <ul>
  <li><a href="#description-des-variables" id="toc-description-des-variables" class="nav-link" data-scroll-target="#description-des-variables"><span class="header-section-number">2.6.1</span> Description des variables</a></li>
  <li><a href="#fonction-glm" id="toc-fonction-glm" class="nav-link" data-scroll-target="#fonction-glm"><span class="header-section-number">2.6.2</span> Fonction glm</a></li>
  <li><a href="#tester-labsence-deffet-dune-variable" id="toc-tester-labsence-deffet-dune-variable" class="nav-link" data-scroll-target="#tester-labsence-deffet-dune-variable"><span class="header-section-number">2.6.3</span> Tester l’absence d’effet d’une variable</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#modèle-log-binomial" id="toc-modèle-log-binomial" class="nav-link" data-scroll-target="#modèle-log-binomial"><span class="header-section-number">3</span> Modèle log-binomial</a>
  <ul>
  <li><a href="#principe-et-mise-en-œuvre-2" id="toc-principe-et-mise-en-œuvre-2" class="nav-link" data-scroll-target="#principe-et-mise-en-œuvre-2"><span class="header-section-number">3.1</span> Principe et mise en œuvre</a></li>
  <li><a href="#exemple-r-2" id="toc-exemple-r-2" class="nav-link" data-scroll-target="#exemple-r-2"><span class="header-section-number">3.2</span> Exemple R</a></li>
  <li><a href="#problème-du-modèle-log-binomial" id="toc-problème-du-modèle-log-binomial" class="nav-link" data-scroll-target="#problème-du-modèle-log-binomial"><span class="header-section-number">3.3</span> Problème du modèle log-binomial</a></li>
  <li><a href="#limitations-du-modèle-log-binomial-et-alternative-pratique" id="toc-limitations-du-modèle-log-binomial-et-alternative-pratique" class="nav-link" data-scroll-target="#limitations-du-modèle-log-binomial-et-alternative-pratique"><span class="header-section-number">3.4</span> Limitations du modèle log-binomial et alternative pratique</a></li>
  <li><a href="#alternative-calculer-un-rr-marginal-à-partir-dun-modèle-logistique" id="toc-alternative-calculer-un-rr-marginal-à-partir-dun-modèle-logistique" class="nav-link" data-scroll-target="#alternative-calculer-un-rr-marginal-à-partir-dun-modèle-logistique"><span class="header-section-number">3.5</span> Alternative : calculer un RR marginal à partir d’un modèle logistique</a></li>
  </ul></li>
  <li><a href="#modèle-logistique-pour-odds-proportionnels" id="toc-modèle-logistique-pour-odds-proportionnels" class="nav-link" data-scroll-target="#modèle-logistique-pour-odds-proportionnels"><span class="header-section-number">4</span> Modèle logistique pour <em>odds</em> proportionnels</a></li>
  <li><a href="#modèle-de-poisson-et-binomial-négatif-pour-taux-dincidence" id="toc-modèle-de-poisson-et-binomial-négatif-pour-taux-dincidence" class="nav-link" data-scroll-target="#modèle-de-poisson-et-binomial-négatif-pour-taux-dincidence"><span class="header-section-number">5</span> Modèle de Poisson et binomial négatif pour taux d’incidence</a>
  <ul>
  <li><a href="#pourquoi-les-modèles-linéaires-classiques-ne-sont-pas-adaptés" id="toc-pourquoi-les-modèles-linéaires-classiques-ne-sont-pas-adaptés" class="nav-link" data-scroll-target="#pourquoi-les-modèles-linéaires-classiques-ne-sont-pas-adaptés"><span class="header-section-number">5.1</span> Pourquoi les modèles linéaires classiques ne sont pas adaptés</a></li>
  <li><a href="#la-distribution-de-poisson" id="toc-la-distribution-de-poisson" class="nav-link" data-scroll-target="#la-distribution-de-poisson"><span class="header-section-number">5.2</span> La distribution de Poisson</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="S1_4_Modeles.docx"><i class="bi bi-file-word"></i>MS Word</a></li><li><a href="../S1_4_Modeles.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Devoir Statistiques Avancées</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Thomas Husson </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<div style="page-break-after: always;"></div>
<section id="modèle-linéaire" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Modèle linéaire</h1>
<section id="principe-et-mise-en-œuvre" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="principe-et-mise-en-œuvre"><span class="header-section-number">1.1</span> Principe et mise en œuvre</h2>
<p>Modèle linéaire = modèle de régression linéaire = régression linéaire.</p>
<p>Utilisé quand une variable quantitative (continue) normalement distribuée <span class="math inline">\(Y\)</span> doit être mise en relation avec une ou plusieurs variables <span class="math inline">\(X_1, X_2, ..., X_p\)</span> (quantitatives ou qualitatives, binaires ou catégorielles (dans le cas de variables catégorielles, elles sont automatiquement transformées en variables binaires)).</p>
<ul>
<li><p><span class="math inline">\(Y\)</span> = variable dépendante, expliquée, à prédire</p></li>
<li><p><span class="math inline">\(X_1, X_2, ..., X_p\)</span> = variables indépendantes, explicatives, prédictives, ou régresseurs</p></li>
</ul>
<p>Équation du modèle linéaire :<br>
</p>
<p><span class="math display">\[
Y = \alpha_0 + \alpha_1 X_1 + \alpha_2 X_2 + ... + \alpha_p X_p + \epsilon
\]</span></p>
<p>où :</p>
<ul>
<li><p><span class="math inline">\(\alpha_0\)</span> = ordonnée à l’origine (intercept)</p></li>
<li><p><span class="math inline">\(\alpha_1, \alpha_2, ..., \alpha_p\)</span> = coefficients de régression (pentes)</p></li>
<li><p><span class="math inline">\(\epsilon\)</span> = terme d’erreur (résidus), supposé suivre une loi normale centrée réduite (d’espérance nulle = 0, avec espérance = moyenne)</p></li>
</ul>
<p>Objectif de l’algorithme = estimer les coefficients de régression (<span class="math inline">\(\alpha_0, \alpha_1, \alpha_2, ..., \alpha_p\)</span>) de façon à minimiser la variance estimée de <span class="math inline">\(\epsilon\)</span> (méthode des moindres carrés).</p>
<p>En gros : l’objectif est de trouver le modèle pour lequel le bruit est minimal.</p>
<p><strong>Conditions de validité</strong></p>
<ul>
<li><p>Normalité de la variable résiduelle <span class="math inline">\(\epsilon\)</span></p></li>
<li><p>Homoscédasticité des résidus (variance constante de <span class="math inline">\(\epsilon\)</span> pour toutes les valeurs de <span class="math inline">\(X\)</span>)</p></li>
<li><p>Indépendance des résidus <span class="math inline">\(\varepsilon\)</span> (les résidus doivent être indépendants les uns des autres, c’est à dire pas de structure d’autocorrélation en particulier pas de structure temporelle)</p></li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Relation régression linéaire et ANOVA</strong></p>
<p>L’ANOVA (analyse de la variance) est en fait un cas particulier de la régression linéaire où toutes les variables explicatives sont catégorielles. Ainsi, une ANOVA à un facteur est équivalente à une régression linéaire avec une variable explicative binaire.</p>
</div>
</div>
</section>
<section id="exemple-avec-le-jeu-de-données-smp" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="exemple-avec-le-jeu-de-données-smp"><span class="header-section-number">1.2</span> Exemple avec le jeu de données <code>smp</code></h2>
<p>Objectif : modéliser la durée de l’entretien en fonction de différentes variables explicatives.</p>
<p>La variable à expliquer est : durée de l’entretien (quantitative, donc régression linéaire adaptée)</p>
<ul>
<li><p>âge (quantitative)</p></li>
<li><p>trouble psychiatrique</p></li>
<li><p>trouble de la personnalité</p></li>
<li><p>traumatisme pendant l’enfance</p></li>
<li><p>type de prison</p></li>
</ul>
<ol type="1">
<li>Description des variables :</li>
</ol>
<ul>
<li><p>Étude descriptive des variables</p></li>
<li><p>Vérification des conditions de validité du modèle : notament la normalité de la variable à expliquer</p></li>
</ul>
<ol start="2" type="1">
<li>Construction du modèle linéaire</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>smp2 <span class="ot">&lt;-</span> smp[smp<span class="sc">$</span>duree.interv<span class="sc">&gt;</span><span class="dv">15</span>,] <span class="co"># exclut valeurs aberrantes</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>    duree.interv<span class="sc">~</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>    schizophrenie <span class="sc">+</span> depression <span class="sc">+</span> abus.subst <span class="sc">+</span> gravite <span class="sc">+</span> charactere <span class="sc">+</span> trauma.enfant <span class="sc">+</span> age <span class="sc">+</span> <span class="fu">factor</span>(type.centre),</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">data=</span>smp2)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = duree.interv ~ schizophrenie + depression + abus.subst + 
    gravite + charactere + trauma.enfant + age + factor(type.centre), 
    data = smp2)

Residuals:
    Min      1Q  Median      3Q     Max 
-38.578 -13.855  -1.769  10.922  64.405 

Coefficients:
                     Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)          42.48996    3.99998  10.623  &lt; 2e-16 ***
schizophrenie         3.06420    2.80997   1.090 0.275911    
depression            6.71269    1.64793   4.073 5.21e-05 ***
abus.subst            4.60037    1.79854   2.558 0.010760 *  
gravite               1.06236    0.56548   1.879 0.060737 .  
charactere            1.62547    0.93536   1.738 0.082723 .  
trauma.enfant        -0.66805    1.66931  -0.400 0.689144    
age                   0.20788    0.06066   3.427 0.000649 ***
factor(type.centre)2  4.09540    2.53401   1.616 0.106546    
factor(type.centre)3 -1.29681    2.44159  -0.531 0.595509    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 18.02 on 645 degrees of freedom
  (144 observations deleted due to missingness)
Multiple R-squared:  0.1086,    Adjusted R-squared:  0.09619 
F-statistic: 8.734 on 9 and 645 DF,  p-value: 1.919e-12</code></pre>
</div>
</div>
<ul>
<li><p>Schizophrénie : augmentation de la durrée moyenne de 3 minutes, non significatif (p=0,28)</p></li>
<li><p>Dépression : augmentation de la durée moyenne de 6 minutes, significatif</p></li>
<li><p>Gravité : augmentation de la durée moyenne de <strong>1 minute par point de gravité</strong>, significatif</p></li>
<li><p>Type de centre : deux lignes, car recodée en deux variables binaires (centre 2 vs centre 3, centre 3 vs centre 1)</p></li>
</ul>
<p>Mais la présentation ne permet pas de tester l’effet global de la variable « type de centre » , c’est-à-dire répondre à la question : la durée d’entretien est-elle indépendante du type de centre, à valeur égale des autres variables ?</p>
<p>Dans ce cas : fonction <code>drop1()</code> :</p>
<p>La fonction <code>drop1()</code> permet de tester l’effet global d’une variable explicative en comparant le modèle complet avec un modèle sans cette variable.</p>
<p>Ici : <code>drop1(mod, test="F")</code> permet de tester l’effet global de chaque variable explicative en comparant le modèle complet avec un modèle sans cette variable, en utilisant un test F (test F = test de comparaison de modèles (ANOVA)).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">drop1</span>(mod, <span class="at">test=</span><span class="st">"F"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Single term deletions

Model:
duree.interv ~ schizophrenie + depression + abus.subst + gravite + 
    charactere + trauma.enfant + age + factor(type.centre)
                    Df Sum of Sq    RSS    AIC F value    Pr(&gt;F)    
&lt;none&gt;                           209523 3798.0                      
schizophrenie        1     386.3 209910 3797.2  1.1891 0.2759114    
depression           1    5390.0 214913 3812.6 16.5927  5.21e-05 ***
abus.subst           1    2125.3 211649 3802.6  6.5425 0.0107602 *  
gravite              1    1146.5 210670 3799.6  3.5295 0.0607370 .  
charactere           1     981.0 210504 3799.1  3.0199 0.0827234 .  
trauma.enfant        1      52.0 209575 3796.2  0.1602 0.6891441    
age                  1    3814.8 213338 3807.8 11.7436 0.0006493 ***
factor(type.centre)  2    3446.2 212970 3804.7  5.3044 0.0051888 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Le type de centre a donc un effet global significatif (p=0,005) sur la durée de l’entretien.</p>
<ol start="3" type="1">
<li>Vérification des conditions de validité du modèle</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mod, <span class="at">which=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="S1_4_Modeles_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Residuals vs Fitted : permet de vérifier que la variance des résidus est constante et globalement indépendante des valeurs prédites (homoscédasticité).</p>
<p>Normal Q-Q : permet de vérifier la normalité des résidus (les points doivent être proches de la diagonale).</p>
<p>Cook’s distance : permet d’identifier les points influents (points avec une grande distance de Cook, au-dessus de la ligne pointillée).</p>
<div style="page-break-after: always;"></div>
</section>
<section id="corrélation-et-modèle-linéaire" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="corrélation-et-modèle-linéaire"><span class="header-section-number">1.3</span> Corrélation et modèle linéaire</h2>
<p>Rappel sur le coefficient de corrélation de Pearson (r) :</p>
<ul>
<li><p><span class="math inline">\(r\)</span> varie entre -1 et 1</p></li>
<li><p><span class="math inline">\(r = 1\)</span> : corrélation positive parfaite (lorsque <span class="math inline">\(X\)</span> augmente, <span class="math inline">\(Y\)</span> augmente de façon linéaire)</p></li>
<li><p><span class="math inline">\(r = -1\)</span> : corrélation négative parfaite (lorsque <span class="math inline">\(X\)</span> augmente, <span class="math inline">\(Y\)</span> diminue de façon linéaire)</p></li>
<li><p><span class="math inline">\(r = 0\)</span> : absence de corrélation linéaire entre <span class="math inline">\(X\)</span> et <span class="math inline">\(Y\)</span></p></li>
</ul>
<p>Donc quand 2 variables <span class="math inline">\(X\)</span> et <span class="math inline">\(Y\)</span> sont parfaitement corrélées (<span class="math inline">\(r\)</span> = 1 ou -1), elles sont linéairement déterminées (<span class="math inline">\(Y = a0 + a1 X\)</span>).</p>
<p><strong>Proximité entre corrélation et régression linéaire</strong> :</p>
<ul>
<li><p>Si <span class="math inline">\(X\)</span> et et <span class="math inline">\(Y\)</span> sont deux variables aléatoires, la régression linéaire de <span class="math inline">\(Y\)</span> en fonction de <span class="math inline">\(X\)</span> permet de prédire les valeurs de <span class="math inline">\(Y\)</span> à partir des valeurs de <span class="math inline">\(X\)</span>.</p></li>
<li><p>Si <span class="math inline">\(X\)</span> et <span class="math inline">\(Y\)</span> sont linéairement liés, le modèle de régression linéaire permet de quantifier cette relation linéaire.</p></li>
<li><p>La corrélation sert uniquement à dire s’il existe un lien entre deux variables et si ce lien va dans le même sens ou en sens inverse.</p></li>
<li><p>La régression sert à utiliser une variable pour estimer la valeur attendue d’une autre variable.</p></li>
<li><p>La dispersion d’une variable correspond au fait que ses valeurs sont plus ou moins éloignées les unes des autres.</p></li>
<li><p>Dire qu’une partie de la dispersion est expliquée signifie qu’une partie des différences observées dans Y est liée aux valeurs de X.</p></li>
<li><p>Le carré de la corrélation correspond à la fraction de la dispersion de Y qui est expliquée par X à travers la relation linéaire.</p></li>
<li><p>Une fraction signifie simplement une partie du tout, par exemple 40 % de ce qui varie dans Y.</p>
<ul>
<li><p>Si cette fraction est faible, alors connaître X aide très peu à estimer Y.</p></li>
<li><p>Si cette fraction est élevée, alors connaître X aide beaucoup à estimer Y.</p></li>
</ul></li>
<li><p>Même si une grande partie de la dispersion est expliquée, cela ne prouve jamais que X est la cause de Y.</p></li>
<li><p>Corrélation et régression décrivent donc le même lien linéaire, mais la corrélation mesure la force du lien et la régression sert à faire des estimations chiffrées de Y. Si un exemple numérique concret doit accompagner ces phrases pour ancrer chaque notion, cela peut être ajouté.</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="do">## 1. Simulation des données</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)          <span class="co"># pour rendre l'exemple reproductible</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">100</span>               <span class="co"># nombre d'observations</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>)     <span class="co"># génération X </span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>bruit <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>) <span class="co"># génération du bruit</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>Y <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> X <span class="sc">+</span> bruit <span class="co"># création de Y en fonction de X avec du bruit</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Corrélation entre X et Y :</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>r <span class="ot">&lt;-</span> <span class="fu">cor</span>(X, Y)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>r</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8786993</code></pre>
</div>
</div>
<p>r = 0.8786 : forte corrélation positive entre X et Y.</p>
<ol start="3" type="1">
<li>Régression linéaire de Y sur X</li>
</ol>
<p>Faire une régression linéaire de Y en fonction de X permet de construire une règle numérique qui permet de prédire Y à partir de X, à partir de données réelles (bruitées)</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(Y <span class="sc">~</span> X)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Y ~ X)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.9073 -0.6835 -0.0875  0.5806  3.2904 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -0.10280    0.09755  -1.054    0.295    
X            1.94753    0.10688  18.222   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.9707 on 98 degrees of freedom
Multiple R-squared:  0.7721,    Adjusted R-squared:  0.7698 
F-statistic:   332 on 1 and 98 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Affiche les coefficients, l’ordonnée à l’origine (intercept), la pente, le R², etc.</p>
<p><span class="math inline">\(r^2\)</span> correspond à la proportion de la variance de Y expliquée par X dans le modèle linéaire, c’est à dire la fraction de la variance de Y qui est expliquée par X à travers la relation linéaire.</p>
<ol start="4" type="1">
<li>Valeurs ajustées (prédictions pour les X observés)</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>Y_chapeau <span class="ot">&lt;-</span> <span class="fu">fitted</span>(mod)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>L’instruction <code>fitted(mod)</code> permet d’obtenir les valeurs prédites de Y (notées <span class="math inline">\(Y_{chapeau}\)</span>) pour chaque valeur observée de X, en utilisant le modèle de régression linéaire.</p>
<ol start="5" type="1">
<li>Vérification r^2 = Var(Y_chapeau) / Var(Y)</li>
</ol>
<p>On vérifie ici que le <span class="math inline">\(r^2\)</span> obtenu dans le résumé du modèle est bien égal à la variance des valeurs prédites (<span class="math inline">\(Y_{chapeau}\)</span>) divisée par la variance de Y.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>var_Y <span class="ot">&lt;-</span> <span class="fu">var</span>(Y)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>var_Y_chapeau <span class="ot">&lt;-</span> <span class="fu">var</span>(Y_chapeau)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>r2_via_cor <span class="ot">&lt;-</span> r<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>r2_via_var <span class="ot">&lt;-</span> var_Y_chapeau <span class="sc">/</span> var_Y</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>r2_via_cor</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7721124</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>r2_via_var</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7721124</code></pre>
</div>
</div>
<p>Si les deux valeurs sont égales, cela confirme que le <span class="math inline">\(r^2\)</span> du modèle linéaire correspond bien à la fraction de la variance de Y expliquée par X.</p>
<p>Cela revient à dire :</p>
<ul>
<li><p>La corrélation dit à quel point X et Y vont ensemble.</p></li>
<li><p>La régression dit combien des différences de Y on peut retrouver grâce à X (quelle est la part de la variance de Y expliquée par X = quelle part des variations de Y est liée aux variations de X).</p></li>
<li><p>Le pourcentage de la variance de Y expliquée par X est donné par le carré du coefficient de corrélation (r²).</p></li>
<li><p>Dans le cas d’une régression avec une seule variable X, ces deux informations sont numériquement équivalentes une fois mises au carré.</p></li>
</ul>
<p><strong>Avec une seule variable explicative X :</strong></p>
<ul>
<li><p><span class="math inline">\(r^2\)</span> = carré du coefficient de corrélation</p></li>
<li><p>= part de la variabilité de Y prédite par la régression</p></li>
<li><p>= % de la variance de Y expliquée par X.</p></li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="S1_4_Modeles_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Résumé : relation entre corrélation et régression linéaire</strong></p>
<p>La corrélation mesure à quel point deux variables X et Y varient ensemble de façon linéaire.</p>
<p>La régression utilise cette relation linéaire pour prédire les valeurs de Y à partir des valeurs de X, dans le cas où il y a une <strong>seule</strong> variable explicative X.</p>
</div>
</div>
<div style="page-break-after: always;"></div>
</section>
<section id="le-test-t-un-cas-particulier-du-modèle-linéaire" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="le-test-t-un-cas-particulier-du-modèle-linéaire"><span class="header-section-number">1.4</span> Le test t : un cas particulier du modèle linéaire</h2>
<p>Rappel : le test t permet de comparer <strong>la moyenne</strong> d’une variable quantitative entre deux groupes.</p>
<p>Dans le cadre d’un modèle linéaire, on peut considérer que le test t est un cas particulier où :</p>
<ul>
<li><p>la variable à expliquer <span class="math inline">\(Y\)</span> est quantitative</p></li>
<li><p>la variable explicative <span class="math inline">\(X\)</span> est binaire (deux groupes)</p></li>
<li><p>le modèle linéaire devient un modèle de régression linéaire avec une seule variable binaire explicative (un facteur à deux modalités).</p></li>
</ul>
<p><span class="math display">\[
Y = \alpha_0 + \alpha_1 \text{groupe}_i + \epsilon_i
\]</span></p>
<p>où <span class="math inline">\(\text{groupe}_i\)</span> est une variable binaire (0 ou 1) indiquant le groupe auquel appartient l’observation <span class="math inline">\(i\)</span>.</p>
<p>Dans ce cas, le modèle linéaire permet de tester si la moyenne de <span class="math inline">\(Y\)</span> est significativement différente entre les deux groupes.</p>
<section id="exemple-r" class="level3" data-number="1.4.1">
<h3 data-number="1.4.1" class="anchored" data-anchor-id="exemple-r"><span class="header-section-number">1.4.1</span> Exemple R</h3>
<section id="test-t" class="level4" data-number="1.4.1.1">
<h4 data-number="1.4.1.1" class="anchored" data-anchor-id="test-t"><span class="header-section-number">1.4.1.1</span> Test t</h4>
<p>On avait vu un test t qui comprarait la moyenne d’âge des détenus selon qu’ils étaient ou non déprimés.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(smp<span class="sc">$</span>age <span class="sc">~</span> smp<span class="sc">$</span>depression, <span class="at">var.equal=</span><span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Two Sample t-test

data:  smp$age by smp$depression
t = 2.6337, df = 795, p-value = 0.008611
alternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0
95 percent confidence interval:
 0.6425038 4.4032412
sample estimates:
mean in group 0 mean in group 1 
       39.93182        37.40895 </code></pre>
</div>
</div>
<p>t = 2.634 : la moyenne d’âge des détenus déprimés est significativement plus basse que celle des détenus non déprimés.</p>
<p>p-value = 0.008611 : la différence de moyenne est significative (p &lt; 0,05).</p>
</section>
<section id="régression-linéaire" class="level4" data-number="1.4.1.2">
<h4 data-number="1.4.1.2" class="anchored" data-anchor-id="régression-linéaire"><span class="header-section-number">1.4.1.2</span> Régression linéaire</h4>
<p>On peut aussi faire une régression linéaire avec la variable binaire <code>depression</code> comme variable explicative :</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(age <span class="sc">~</span> depression, <span class="at">data=</span>smp))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = age ~ depression, data = smp)

Residuals:
    Min      1Q  Median      3Q     Max 
-20.932 -10.932  -1.409   8.068  46.591 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  39.9318     0.6003  66.519  &lt; 2e-16 ***
depression   -2.5229     0.9579  -2.634  0.00861 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 13.21 on 795 degrees of freedom
  (2 observations deleted due to missingness)
Multiple R-squared:  0.008649,  Adjusted R-squared:  0.007402 
F-statistic: 6.936 on 1 and 795 DF,  p-value: 0.008611</code></pre>
</div>
</div>
<p>t value = - 2,634 et p value = 0,008611 : les résultats sont identiques à ceux du test t.</p>
</section>
</section>
<section id="relation-entre-test-t-et-régression-linéaire" class="level3" data-number="1.4.2">
<h3 data-number="1.4.2" class="anchored" data-anchor-id="relation-entre-test-t-et-régression-linéaire"><span class="header-section-number">1.4.2</span> Relation entre test t et régression linéaire</h3>
<p>Le test t est donc un cas particulier de la régression linéaire où la variable explicative est binaire (un facteur à deux modalités).</p>
<p>Dans ce cas, le modèle linéaire permet de tester si la moyenne de la variable à expliquer est significativement différente entre les deux groupes.</p>
<p>Considérer le modèle llinéaire comme une généralisation du test t permet de transposer une partie des propriétés du test t à la régression linéaire :</p>
<ul>
<li><p><strong>Normalité des résidus</strong> : <strong>hypothèse faible</strong>, pouvant être facilement compensée par un échantillon suffisamment grand</p></li>
<li><p><strong>Indépendance des observations</strong> : reste nécessaire</p></li>
<li><p><strong>Homoscédasticité</strong> : = égalité de la variance : peut être supprimée par un estimateur robuste</p>
<ul>
<li><p>Estimateur “sandwich” : fonctionne en utilisant la matrice de variance-covariance des résidus pour ajuster les erreurs standards des coefficients du modèle.</p></li>
<li><p>Bootstrap : méthode de rééchantillonnage qui permet d’estimer la variance des coefficients du modèle en générant de multiples échantillons à partir des données originales.</p></li>
</ul></li>
<li><p><strong>Défaut de linéarité d’une variable quantitative</strong> : peut poser problème, mais peut être compensé par une transformation de la variable (logarithmique, racine carrée, etc.) ou par l’utilisation de modèles non linéaires.</p></li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Méthode des moindres carrés</strong></p>
<p>La régression linéaire utilise la méthode des moindres carrés pour estimer les coefficients du modèle, de manière à minimiser la somme des carrés des résidus (différences entre les valeurs observées et les valeurs prédites).</p>
<p>L’objectif est de trouver les coefficients <span class="math inline">\(\alpha_0\)</span> et <span class="math inline">\(\alpha_1\)</span> qui minimisent la somme des carrés des erreurs (résidus) entre les valeurs observées de <span class="math inline">\(Y\)</span> et les valeurs prédites par le modèle.</p>
</div>
</div>
<div style="page-break-after: always;"></div>
</section>
</section>
</section>
<section id="modèle-logistique" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Modèle logistique</h1>
<section id="modèle-linéaire-inadapté-pour-cas-témoins" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="modèle-linéaire-inadapté-pour-cas-témoins"><span class="header-section-number">2.1</span> Modèle linéaire inadapté pour cas témoins</h2>
<p>En étude cas-témoins :</p>
<ul>
<li><p>on choisit un certain nombre de cas (Y=1) et un certain nombre de témoins (Y=0) de manière artificielle,</p></li>
<li><p>donc la proportion de cas dans les données ne reflète pas le vrai risque dans la population.</p></li>
</ul>
<p>On ne peut donc pas interpréter :</p>
<ul>
<li><p>ni la moyenne de Y comme un risque,</p></li>
<li><p>ni la différence de moyennes comme une différence absolue de risque.</p></li>
</ul>
<p>Or le modèle linéaire sur Y (0/1) raisonne justement en termes de moyennes et de différences absolues, donc ça ne marche pas en cas-témoins.</p>
<p>En revanche, en cas-témoins, l’odds-ratio reste interprétable → d’où l’intérêt de la logistique.</p>
</section>
<section id="principe-et-mise-en-œuvre-1" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="principe-et-mise-en-œuvre-1"><span class="header-section-number">2.2</span> Principe et mise en œuvre</h2>
<p>Objectif du modèle logistique : modéliser une variable binaire (0 ou 1) en fonction de variables explicatives quantitatives ou qualitatives.</p>
<p>Modèle logistique = régression logistique.</p>
<p>Équation du modèle logistique :</p>
<p><span class="math display">\[
Y = \log\left(\frac{p}{1-p}\right) = \alpha_0 + \alpha_1 X_1 + ... + \alpha_p X_p + \epsilon
\]</span></p>
<p>Il est très peu probable que <span class="math inline">\(\varepsilon\)</span> suive une loi normale :</p>
<ul>
<li><p><span class="math inline">\(Y\)</span> est binaire (0 ou 1), donc la variance de <span class="math inline">\(Y\)</span> n’est pas constante (elle dépend de la valeur de <span class="math inline">\(p\)</span>)</p></li>
<li><p>Les valeurs de à droites varient entre <span class="math inline">\(-\infty\)</span> et <span class="math inline">\(+\infty\)</span></p></li>
</ul>
<p>NB : les résidus se calculent <span class="math inline">\(\varepsilon = Y\ –\ (\alpha_0 + \alpha_1 X_1 + ... + \alpha_p X_p)\)</span>.</p>
<p>En fait l’équation n’a pas de sens !</p>
<ul>
<li><p>À gauche : Y = 0 ou 1</p></li>
<li><p>À droite : une combinaison linéaire + une erreur ε → ça peut être n’importe quel réel, positif ou négatif.</p></li>
<li><p>Un modèle linéaire peut prédire des valeurs &lt; 0 ou &gt; 1, or on veut prédire quelque chose qui ressemble à une probabilité.</p></li>
<li><p>Il n’y a ni log-linéarité, ni proportionnalité des risques.</p></li>
</ul>
<p>L’objectif est donc de modéliser la “probabilité” que Y = 1 en fonction des variables explicatives <span class="math inline">\(X_1, X_2, ..., X_p\)</span>.</p>
<p>C’est à dire <span class="math inline">\(P(Y=1|X_1, X_2, ..., X_p)\)</span>. (pour probabilité de Y sachant X1, X2, …, Xp)</p>
</section>
<section id="transformation-de-y" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="transformation-de-y"><span class="header-section-number">2.3</span> Transformation de Y</h2>
<section id="odds" class="level3" data-number="2.3.1">
<h3 data-number="2.3.1" class="anchored" data-anchor-id="odds"><span class="header-section-number">2.3.1</span> Odds</h3>
<p>L’objectif est de modéliser la probabilité que Y = 1 en fonction des variables explicatives <span class="math inline">\(X_1, X_2, ..., X_p\)</span>.</p>
<p>Donc on cherche à modéliser <span class="math inline">\(p = P(Y=1|X_1, X_2, ..., X_p)\)</span>.</p>
<ul>
<li><p><span class="math inline">\(p\)</span> est compris entre 0 et 1.</p></li>
<li><p>on cherche en fait à calculer l’odds = la cote = la probabilité que Y = 1 / probabilité que Y = 0 = <span class="math inline">\(p/(1-p)\)</span>.</p></li>
</ul>
<p>Les odds varient entre 0 et +∞. Exemple :</p>
<ul>
<li><p>si p = 0.5 → odds = 0.5 / 0.5 = 1</p></li>
<li><p>si p = 0.8 → odds = 0.8 / 0.2 = 4</p></li>
</ul>
</section>
<section id="log-odds" class="level3" data-number="2.3.2">
<h3 data-number="2.3.2" class="anchored" data-anchor-id="log-odds"><span class="header-section-number">2.3.2</span> Log-odds</h3>
<p>On applique la transformation logarithmique aux odds afin d’obtenir une variable qui varie entre -∞ et +∞ et de la rendre compatible avec une régression linéaire.</p>
<p>Attention, on supprime <span class="math inline">\(\varepsilon\)</span> car :</p>
<ul>
<li><p>on ne peut pas avoir de terme d’erreur dans une régression logistique</p></li>
<li><p>en fait, comme on modélise la probabilité que <span class="math inline">\(Y=1\)</span> à partir des données observées, l’erreur est “contenue” dans les données elles-mêmes.</p></li>
</ul>
<p><span class="math display">\[
\log\left(\frac{p(Y=1)}{1-p(Y=1)}\right) = \alpha_0 + \alpha_1 X_1 + ... + \alpha_p X_p
\]</span></p>
</section>
</section>
<section id="maximum-de-vraisemblance" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="maximum-de-vraisemblance"><span class="header-section-number">2.4</span> Maximum de vraisemblance</h2>
<p>L’estimation des coefficients du modèle logistique se fait par la méthode du maximum de vraisemblance.</p>
<p>Vraisemblance = probabilité d’observer les données réelles, en fonction des paramètres du modèle.</p>
<p>L’idée est de trouver les coefficients <span class="math inline">\(\alpha_0, \alpha_1, ..., \alpha_p\)</span> qui maximisent la probabilité d’observer les données réelles, en supposant que le modèle est correct.</p>
<p>Quand on dit “maximiser la log-vraisemblance”, c’est équivalent à maximiser la vraisemblance, mais c’est plus facile à calculer avec des logarithmes.</p>
<p>L’utilisation des logarithmes facilite les calculs car :</p>
<ul>
<li><p>la log-vraisemblance transforme les produits en sommes, ce qui est plus simple à manipuler mathématiquement.</p></li>
<li><p>elle permet d’éviter des problèmes numériques liés à la manipulation de très petites probabilités.</p></li>
<li><p>Elle est souvent utilisée en statistique pour simplifier les calculs d’optimisation.</p></li>
</ul>
</section>
<section id="conditions-de-validité" class="level2" data-number="2.5">
<h2 data-number="2.5" class="anchored" data-anchor-id="conditions-de-validité"><span class="header-section-number">2.5</span> Conditions de validité</h2>
<p>La condition de validité la plus importante : au moins 10 évènements par variable explicative dans le modèle (10 événements = 10 cas où Y=1).</p>
<p>Cela permet d’assurer que les estimations des coefficients du modèle sont stables et fiables.</p>
</section>
<section id="exemple-r-1" class="level2" data-number="2.6">
<h2 data-number="2.6" class="anchored" data-anchor-id="exemple-r-1"><span class="header-section-number">2.6</span> Exemple R</h2>
<p>La fonction <code>glm()</code> permet de faire une régression logistique en R.</p>
<p>Objectif : modéliser l’existence d’un risque suicidaire élevé à l’aide des variables :</p>
<ul>
<li><p>abus dans l’enfance (oui/non),</p></li>
<li><p>procédure disciplinaire pendant l’incarcération (oui/non),</p></li>
<li><p>durée de la peine (&lt;1 mois, 1-6 mois, 6-12 mois, 1-5 ans, &gt;5 ans),</p></li>
<li><p>âge (continue)</p></li>
<li><p>type de prison (« 1 » pour maison centrale, « 2 » pour centre de détention et « 3 » pour maison d’arrêt).</p></li>
</ul>
<section id="description-des-variables" class="level3" data-number="2.6.1">
<h3 data-number="2.6.1" class="anchored" data-anchor-id="description-des-variables"><span class="header-section-number">2.6.1</span> Description des variables</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">describe</span>(</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>    smp[, <span class="fu">c</span>(<span class="st">"hr.suicide"</span>,<span class="st">"abus.enfant"</span>,<span class="st">"discipline"</span>, <span class="st">"duree.peine"</span>,<span class="st">"age"</span>)], </span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">num.desc=</span><span class="fu">c</span>(<span class="st">"mean"</span>,<span class="st">"sd"</span>,<span class="st">"median"</span>, <span class="st">"min"</span>,<span class="st">"max"</span>,<span class="st">"valid.n"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Description of smp[, c("hr.suicide", "abus.enfant", "discipline", "duree.peine",      "age")] </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
 Numeric 
             mean    sd median min max valid.n
hr.suicide   0.20  0.40      0   0   1     760
abus.enfant  0.28  0.45      0   0   1     792
discipline   0.23  0.42      0   0   1     793
duree.peine  4.32  0.85      5   1   5     575
age         38.94 13.26     37  19  84     797</code></pre>
</div>
</div>
</section>
<section id="fonction-glm" class="level3" data-number="2.6.2">
<h3 data-number="2.6.2" class="anchored" data-anchor-id="fonction-glm"><span class="header-section-number">2.6.2</span> Fonction glm</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="fu">glm</span>(</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>    hr.suicide <span class="sc">~</span> </span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>        abus.enfant <span class="sc">+</span> discipline <span class="sc">+</span> duree.peine <span class="sc">+</span> age <span class="sc">+</span> <span class="fu">factor</span>(type.centre), </span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">data=</span>smp, </span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = hr.suicide ~ abus.enfant + discipline + duree.peine + 
    age + factor(type.centre), family = "binomial", data = smp)

Coefficients:
                      Estimate Std. Error z value Pr(&gt;|z|)   
(Intercept)          -0.329750   0.787283  -0.419  0.67533   
abus.enfant           0.633421   0.228495   2.772  0.00557 **
discipline            0.454877   0.254880   1.785  0.07431 . 
duree.peine          -0.295252   0.149316  -1.977  0.04800 * 
age                  -0.005002   0.009468  -0.528  0.59729   
factor(type.centre)2 -0.045704   0.333694  -0.137  0.89106   
factor(type.centre)3  0.273555   0.371157   0.737  0.46110   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 555.49  on 548  degrees of freedom
Residual deviance: 531.28  on 542  degrees of freedom
  (250 observations deleted due to missingness)
AIC: 545.28

Number of Fisher Scoring iterations: 4</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coefficients</span>(mod))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         (Intercept)          abus.enfant           discipline 
           0.7191038            1.8840458            1.5759788 
         duree.peine                  age factor(type.centre)2 
           0.7443441            0.9950108            0.9553243 
factor(type.centre)3 
           1.3146295 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">confint</span>(mod))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Waiting for profiling to be done...</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                         2.5 %    97.5 %
(Intercept)          0.1526791 3.3673241
abus.enfant          1.1996784 2.9433962
discipline           0.9514471 2.5901545
duree.peine          0.5549039 0.9978941
age                  0.9764391 1.0134442
factor(type.centre)2 0.5042208 1.8782340
factor(type.centre)3 0.6406323 2.7632295</code></pre>
</div>
</div>
<p>Pour afficher tous les résultats en un seul tableau facilement exportable en latex (tableau gtsummary)</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>res_table1 <span class="ot">&lt;-</span> <span class="fu">tbl_regression</span>(</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>    mod,</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">exponentiate =</span> <span class="cn">TRUE</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">|&gt;</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">modify_table_styling</span>(</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">columns =</span> estimate,</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">footnote =</span> <span class="st">"Estimates are odds ratios from a logistic regression model."</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>res_table1</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="zesyyichzg" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#zesyyichzg table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#zesyyichzg thead, #zesyyichzg tbody, #zesyyichzg tfoot, #zesyyichzg tr, #zesyyichzg td, #zesyyichzg th {
  border-style: none;
}

#zesyyichzg p {
  margin: 0;
  padding: 0;
}

#zesyyichzg .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#zesyyichzg .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#zesyyichzg .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#zesyyichzg .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#zesyyichzg .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#zesyyichzg .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#zesyyichzg .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#zesyyichzg .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#zesyyichzg .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#zesyyichzg .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#zesyyichzg .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#zesyyichzg .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#zesyyichzg .gt_spanner_row {
  border-bottom-style: hidden;
}

#zesyyichzg .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#zesyyichzg .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#zesyyichzg .gt_from_md > :first-child {
  margin-top: 0;
}

#zesyyichzg .gt_from_md > :last-child {
  margin-bottom: 0;
}

#zesyyichzg .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#zesyyichzg .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#zesyyichzg .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#zesyyichzg .gt_row_group_first td {
  border-top-width: 2px;
}

#zesyyichzg .gt_row_group_first th {
  border-top-width: 2px;
}

#zesyyichzg .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#zesyyichzg .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#zesyyichzg .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#zesyyichzg .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#zesyyichzg .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#zesyyichzg .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#zesyyichzg .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#zesyyichzg .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#zesyyichzg .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#zesyyichzg .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#zesyyichzg .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#zesyyichzg .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#zesyyichzg .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#zesyyichzg .gt_left {
  text-align: left;
}

#zesyyichzg .gt_center {
  text-align: center;
}

#zesyyichzg .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#zesyyichzg .gt_font_normal {
  font-weight: normal;
}

#zesyyichzg .gt_font_bold {
  font-weight: bold;
}

#zesyyichzg .gt_font_italic {
  font-style: italic;
}

#zesyyichzg .gt_super {
  font-size: 65%;
}

#zesyyichzg .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#zesyyichzg .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#zesyyichzg .gt_indent_1 {
  text-indent: 5px;
}

#zesyyichzg .gt_indent_2 {
  text-indent: 10px;
}

#zesyyichzg .gt_indent_3 {
  text-indent: 15px;
}

#zesyyichzg .gt_indent_4 {
  text-indent: 20px;
}

#zesyyichzg .gt_indent_5 {
  text-indent: 25px;
}

#zesyyichzg .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#zesyyichzg div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table caption-top table table-sm table-striped small" data-quarto-bootstrap="false">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="gt_col_headings header">
<th id="label" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col"><strong>Characteristic</strong></th>
<th id="estimate" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>OR</strong><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span></th>
<th id="conf.low" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>95% CI</strong></th>
<th id="p.value" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>p-value</strong></th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="label">abus.enfant</td>
<td class="gt_row gt_center" headers="estimate">1.88</td>
<td class="gt_row gt_center" headers="conf.low">1.20, 2.94</td>
<td class="gt_row gt_center" headers="p.value">0.006</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">discipline</td>
<td class="gt_row gt_center" headers="estimate">1.58</td>
<td class="gt_row gt_center" headers="conf.low">0.95, 2.59</td>
<td class="gt_row gt_center" headers="p.value">0.074</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">duree.peine</td>
<td class="gt_row gt_center" headers="estimate">0.74</td>
<td class="gt_row gt_center" headers="conf.low">0.55, 1.00</td>
<td class="gt_row gt_center" headers="p.value">0.048</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">age</td>
<td class="gt_row gt_center" headers="estimate">1.00</td>
<td class="gt_row gt_center" headers="conf.low">0.98, 1.01</td>
<td class="gt_row gt_center" headers="p.value">0.6</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">factor(type.centre)</td>
<td class="gt_row gt_center" headers="estimate"><br>
</td>
<td class="gt_row gt_center" headers="conf.low"><br>
</td>
<td class="gt_row gt_center" headers="p.value"><br>
</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;1</td>
<td class="gt_row gt_center" headers="estimate">—</td>
<td class="gt_row gt_center" headers="conf.low">—</td>
<td class="gt_row gt_center" headers="p.value"><br>
</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;2</td>
<td class="gt_row gt_center" headers="estimate">0.96</td>
<td class="gt_row gt_center" headers="conf.low">0.50, 1.88</td>
<td class="gt_row gt_center" headers="p.value">0.9</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;3</td>
<td class="gt_row gt_center" headers="estimate">1.31</td>
<td class="gt_row gt_center" headers="conf.low">0.64, 2.76</td>
<td class="gt_row gt_center" headers="p.value">0.5</td>
</tr>
</tbody><tfoot>
<tr class="gt_footnotes odd">
<td colspan="4" class="gt_footnote"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span> Estimates are odds ratios from a logistic regression model.</td>
</tr>
<tr class="gt_sourcenotes even">
<td colspan="4" class="gt_sourcenote">Abbreviations: CI = Confidence Interval, OR = Odds Ratio</td>
</tr>
</tfoot>

</table>

</div>
</div>
</div>
</section>
<section id="tester-labsence-deffet-dune-variable" class="level3" data-number="2.6.3">
<h3 data-number="2.6.3" class="anchored" data-anchor-id="tester-labsence-deffet-dune-variable"><span class="header-section-number">2.6.3</span> Tester l’absence d’effet d’une variable</h3>
<p>Fonction <code>drop1</code> permet de tester si “globalement”, l’effet d’une variable catégorielle a un effet sur <code>hr.suicide</code></p>
<p>La fonction <code>drop1</code> permet de “supprimer” la variable du modèle.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">drop1</span>(mod,.<span class="sc">~</span>.,<span class="at">test=</span><span class="st">"Chisq"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Single term deletions

Model:
hr.suicide ~ abus.enfant + discipline + duree.peine + age + factor(type.centre)
                    Df Deviance    AIC    LRT Pr(&gt;Chi)   
&lt;none&gt;                   531.28 545.28                   
abus.enfant          1   538.78 550.78 7.5010 0.006166 **
discipline           1   534.41 546.41 3.1287 0.076924 . 
duree.peine          1   535.18 547.18 3.8968 0.048379 * 
age                  1   531.56 543.56 0.2810 0.596049   
factor(type.centre)  2   532.72 542.72 1.4368 0.487522   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>On utilise ici un test du Chi2 car on utilise le Maximum de Vraisemblance, qui suit une loi du Chi2 asymptotiquement.</p>
<p>Pour un modèle linéaire, on utilisait un test F car on utilisait la méthode des moindres carrés, qui suit une loi F (pour Fisher) asymptotiquement.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Différence entre test F et test du Chi2 dans le contexte des modèles linéaires et logistiques</strong></p>
<ul>
<li><p>Test F : utilisé dans les modèles linéaires (régression linéaire) basés sur la méthode des moindres carrés. Il compare la variance expliquée par le modèle à la variance résiduelle pour évaluer la signification des variables explicatives.</p></li>
<li><p>Test du Chi2 : utilisé dans les modèles logistiques basés sur le maximum de vraisemblance. Il compare la log-vraisemblance du modèle complet avec celle d’un modèle réduit (sans la variable testée) pour évaluer l’effet global de la variable explicative.</p></li>
</ul>
</div>
</div>
<div style="page-break-after: always;"></div>
</section>
</section>
</section>
<section id="modèle-log-binomial" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Modèle log-binomial</h1>
<p>Problème du modèle logistique : les odds-ratios sont ajustés et donc difficiles à interpréter.</p>
<p>Comment traduire un OR en truc du quotidien (si la maladie est fréquente) ?</p>
<p>Solution : modèle log-binomial.</p>
<section id="principe-et-mise-en-œuvre-2" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="principe-et-mise-en-œuvre-2"><span class="header-section-number">3.1</span> Principe et mise en œuvre</h2>
<p>Objectif du modèle log-binomial : modéliser une variable binaire (0 ou 1) en fonction de variables explicatives quantitatives ou qualitatives, <strong>en estimant directement les risques relatifs (RR) au lieu des odds-ratios (OR).</strong></p>
<p>Modèle log-binomial = régression log-binomial.</p>
<p>Équation du modèle log-binomial :</p>
<br>

<span class="math display">\[\begin{aligned}
\log[p(Y=1)] &amp;= \alpha_0 + \alpha_1 X_1 + \dots + \alpha_p X_p \\
\longleftrightarrow\quad
p(Y=1 \mid X) &amp;= \exp(a_0 + a_1 X_1 + \dots + a_p X_p)
\end{aligned}\]</span>
<p><br>
</p>
<p>où <span class="math inline">\(p(Y=1)\)</span> est la probabilité que Y = 1 (risque).</p>
<p>Problème mathématique :</p>
<ul>
<li><p>à gauche : <span class="math inline">\(\log[p(Y=1)]\)</span> varie entre <span class="math inline">\(-\infty\)</span> et 0 (car <span class="math inline">\(p(Y=1)\)</span> varie entre 0 et 1) donc <span class="math inline">\(\log[p(Y=1)]\)</span> ne peut pas prendre toutes les valeurs réelles.</p></li>
<li><p>à droite : une combinaison linéaire de variables explicatives qui peut prendre toutes les valeurs réelles (entre <span class="math inline">\(-\infty\)</span> et <span class="math inline">\(+\infty\)</span>).</p></li>
</ul>
<p>On a donc un problème de convergence (on dit que l’algorithme converge quand il trouve une solution stable) :</p>
<ul>
<li><p>une probabilité doit être ≤ 1,</p></li>
<li><p>mais <span class="math inline">\(\exp(\cdot)\)</span> peut dépasser 1 très facilement.</p></li>
</ul>
<p>Le modèle log-binomial fonctionne donc avec des contraintes :</p>
<ul>
<li><p><span class="math inline">\(\exp(a_0 + a_1 X_1 + ... ) \le 1\)</span> : le modèle interdit des combinaisons de variables explicatives qui donneraient des probabilités &gt; 1.</p></li>
<li><p>donc les coefficients sont fortement contraints à se rapprocher de 0.</p></li>
</ul>
</section>
<section id="exemple-r-2" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="exemple-r-2"><span class="header-section-number">3.2</span> Exemple R</h2>
<p>On utilise la fonction <code>logbin()</code> du package <code>logbin</code>.</p>
<p>Objectif : idem que précédemment, modéliser l’existence d’un risque suicidaire élevé.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>mod2 <span class="ot">&lt;-</span> <span class="fu">logbin</span>(</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>    hr.suicide <span class="sc">~</span> </span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>        abus.enfant <span class="sc">+</span> discipline <span class="sc">+</span> duree.peine <span class="sc">+</span> age <span class="sc">+</span> <span class="fu">factor</span>(type.centre),</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> smp</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mod2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
logbin(formula = hr.suicide ~ abus.enfant + discipline + duree.peine + 
    age + factor(type.centre), data = smp)

Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-1.4029  -0.6821  -0.5819  -0.4928   2.0684  

Coefficients:
                      Estimate Std. Error z value Pr(&gt;|z|)   
(Intercept)          -0.928551   0.585717  -1.585  0.11289   
abus.enfant           0.480690   0.167112   2.876  0.00402 **
discipline            0.275071   0.187525   1.467  0.14242   
duree.peine          -0.191619   0.107833  -1.777  0.07557 . 
age                  -0.004893   0.007487  -0.654  0.51343   
factor(type.centre)2  0.011596   0.270326   0.043  0.96578   
factor(type.centre)3  0.224932   0.294407   0.764  0.44486   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

    Null deviance: 555.49  on 548  degrees of freedom
Residual deviance: 532.19  on 542  degrees of freedom
  (250 observations deleted due to missingness)

  AIC: 546.19 
AIC_c: 546.40 

Number of iterations: 59719 (best: 2929)</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coefficients</span>(mod2))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         (Intercept)          abus.enfant           discipline 
           0.3951260            1.6171894            1.3166236 
         duree.peine                  age factor(type.centre)2 
           0.8256215            0.9951193            1.0116637 
factor(type.centre)3 
           1.2522375 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">confint</span>(mod2))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                         2.5 %   97.5 %
(Intercept)          0.1253640 1.245370
abus.enfant          1.1655076 2.243916
discipline           0.9116757 1.901441
duree.peine          0.6683343 1.019925
age                  0.9806236 1.009829
factor(type.centre)2 0.5955717 1.718455
factor(type.centre)3 0.7032138 2.229903</code></pre>
</div>
</div>
<p>Et représentation en tableau :</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>res_table2 <span class="ot">&lt;-</span> <span class="fu">tbl_regression</span>(mod2, <span class="at">exponentiate =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">modify_table_styling</span>(</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">columns =</span> estimate,</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">footnote =</span> <span class="st">"Estimates are risk ratios from a log-binomial model."</span></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>    )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: The `tidy()` method for objects of class `logbin` is not maintained by the broom team, and is only supported through the `glm` tidier method. Please be cautious in interpreting and reporting broom output.

This warning is displayed once per session.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>res_table2</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="uguzitfrqe" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#uguzitfrqe table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#uguzitfrqe thead, #uguzitfrqe tbody, #uguzitfrqe tfoot, #uguzitfrqe tr, #uguzitfrqe td, #uguzitfrqe th {
  border-style: none;
}

#uguzitfrqe p {
  margin: 0;
  padding: 0;
}

#uguzitfrqe .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#uguzitfrqe .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#uguzitfrqe .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#uguzitfrqe .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#uguzitfrqe .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#uguzitfrqe .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#uguzitfrqe .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#uguzitfrqe .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#uguzitfrqe .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#uguzitfrqe .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#uguzitfrqe .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#uguzitfrqe .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#uguzitfrqe .gt_spanner_row {
  border-bottom-style: hidden;
}

#uguzitfrqe .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#uguzitfrqe .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#uguzitfrqe .gt_from_md > :first-child {
  margin-top: 0;
}

#uguzitfrqe .gt_from_md > :last-child {
  margin-bottom: 0;
}

#uguzitfrqe .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#uguzitfrqe .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#uguzitfrqe .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#uguzitfrqe .gt_row_group_first td {
  border-top-width: 2px;
}

#uguzitfrqe .gt_row_group_first th {
  border-top-width: 2px;
}

#uguzitfrqe .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#uguzitfrqe .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#uguzitfrqe .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#uguzitfrqe .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#uguzitfrqe .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#uguzitfrqe .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#uguzitfrqe .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#uguzitfrqe .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#uguzitfrqe .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#uguzitfrqe .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#uguzitfrqe .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#uguzitfrqe .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#uguzitfrqe .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#uguzitfrqe .gt_left {
  text-align: left;
}

#uguzitfrqe .gt_center {
  text-align: center;
}

#uguzitfrqe .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#uguzitfrqe .gt_font_normal {
  font-weight: normal;
}

#uguzitfrqe .gt_font_bold {
  font-weight: bold;
}

#uguzitfrqe .gt_font_italic {
  font-style: italic;
}

#uguzitfrqe .gt_super {
  font-size: 65%;
}

#uguzitfrqe .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#uguzitfrqe .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#uguzitfrqe .gt_indent_1 {
  text-indent: 5px;
}

#uguzitfrqe .gt_indent_2 {
  text-indent: 10px;
}

#uguzitfrqe .gt_indent_3 {
  text-indent: 15px;
}

#uguzitfrqe .gt_indent_4 {
  text-indent: 20px;
}

#uguzitfrqe .gt_indent_5 {
  text-indent: 25px;
}

#uguzitfrqe .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#uguzitfrqe div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table caption-top table table-sm table-striped small" data-quarto-bootstrap="false">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="gt_col_headings header">
<th id="label" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col"><strong>Characteristic</strong></th>
<th id="estimate" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>RR</strong><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span></th>
<th id="conf.low" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>95% CI</strong></th>
<th id="p.value" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>p-value</strong></th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="label">abus.enfant</td>
<td class="gt_row gt_center" headers="estimate">1.62</td>
<td class="gt_row gt_center" headers="conf.low">1.17, 2.24</td>
<td class="gt_row gt_center" headers="p.value">0.004</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">discipline</td>
<td class="gt_row gt_center" headers="estimate">1.32</td>
<td class="gt_row gt_center" headers="conf.low">0.91, 1.90</td>
<td class="gt_row gt_center" headers="p.value">0.14</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">duree.peine</td>
<td class="gt_row gt_center" headers="estimate">0.83</td>
<td class="gt_row gt_center" headers="conf.low">0.67, 1.02</td>
<td class="gt_row gt_center" headers="p.value">0.076</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">age</td>
<td class="gt_row gt_center" headers="estimate">1.00</td>
<td class="gt_row gt_center" headers="conf.low">0.98, 1.01</td>
<td class="gt_row gt_center" headers="p.value">0.5</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">factor(type.centre)</td>
<td class="gt_row gt_center" headers="estimate"><br>
</td>
<td class="gt_row gt_center" headers="conf.low"><br>
</td>
<td class="gt_row gt_center" headers="p.value"><br>
</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;1</td>
<td class="gt_row gt_center" headers="estimate">—</td>
<td class="gt_row gt_center" headers="conf.low">—</td>
<td class="gt_row gt_center" headers="p.value"><br>
</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;2</td>
<td class="gt_row gt_center" headers="estimate">1.01</td>
<td class="gt_row gt_center" headers="conf.low">0.60, 1.72</td>
<td class="gt_row gt_center" headers="p.value">&gt;0.9</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="label">&nbsp;&nbsp;&nbsp;&nbsp;3</td>
<td class="gt_row gt_center" headers="estimate">1.25</td>
<td class="gt_row gt_center" headers="conf.low">0.70, 2.23</td>
<td class="gt_row gt_center" headers="p.value">0.4</td>
</tr>
</tbody><tfoot>
<tr class="gt_footnotes odd">
<td colspan="4" class="gt_footnote"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span> Estimates are risk ratios from a log-binomial model.</td>
</tr>
<tr class="gt_sourcenotes even">
<td colspan="4" class="gt_sourcenote">Abbreviations: CI = Confidence Interval, RR = Relative Risk</td>
</tr>
</tfoot>

</table>

</div>
</div>
</div>
</section>
<section id="problème-du-modèle-log-binomial" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="problème-du-modèle-log-binomial"><span class="header-section-number">3.3</span> Problème du modèle log-binomial</h2>
</section>
<section id="limitations-du-modèle-log-binomial-et-alternative-pratique" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="limitations-du-modèle-log-binomial-et-alternative-pratique"><span class="header-section-number">3.4</span> Limitations du modèle log-binomial et alternative pratique</h2>
<p>Le modèle <strong>log-binomial</strong>, utilisé pour estimer directement un <strong>risque relatif (RR)</strong> ajusté lorsque la maladie est fréquente, présente plusieurs limites majeures :</p>
<ul>
<li><p>méthodes d’estimation instables lorsque la prévalence est élevée ou que de nombreuses covariables sont incluses ;</p></li>
<li><p>problèmes fréquents de <strong>convergence</strong>, car les probabilités prédites doivent rester ≤ 1 alors que la forme exponentielle peut facilement dépasser cette limite ;</p></li>
<li><p>les coefficients sont contraints vers 0, ce qui produit des <strong>risques relatifs artificiellement proches de 1</strong> ;</p></li>
<li><p>le modèle estime des <strong>RR conditionnels</strong>, difficiles à interpréter en présence de nombreuses covariables ou de covariables corrélées ;</p></li>
<li><p>pour des maladies fréquentes, l’hypothèse d’absence d’interaction est souvent intenable, menant soit à des probabilités &gt; 100 %, soit à un aplatissement général des RR.</p></li>
</ul>
</section>
<section id="alternative-calculer-un-rr-marginal-à-partir-dun-modèle-logistique" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="alternative-calculer-un-rr-marginal-à-partir-dun-modèle-logistique"><span class="header-section-number">3.5</span> Alternative : calculer un RR marginal à partir d’un modèle logistique</h2>
<p>Une approche robuste consiste à :</p>
<ol type="1">
<li><p>ajuster une <strong>régression logistique</strong> ;</p></li>
<li><p>créer deux jeux de données contrefactuels :</p>
<ul>
<li><p>un où l’exposition vaut <span class="math inline">\(0\)</span> pour tous les sujets ;</p></li>
<li><p>un où l’exposition vaut <span class="math inline">\(1\)</span> pour tous les sujets ;</p></li>
</ul></li>
<li><p>prédire les probabilités dans chaque scénario ;</p></li>
<li><p>calculer :</p>
<ul>
<li><p>le risque moyen non exposé : <span class="math inline">\(p_0\)</span> ;</p></li>
<li><p>le risque moyen exposé : <span class="math inline">\(p_1\)</span> ;</p></li>
<li><p>le risque relatif marginal : <span class="math inline">\(RR = \dfrac{p_1}{p_0}\)</span> ;</p></li>
<li><p>l’odds-ratio marginal : <span class="math inline">\(OR = \dfrac{p_1/(1-p_1)}{p_0/(1-p_0)}\)</span> ;</p></li>
<li><p>la différence absolue de risque : <span class="math inline">\(DAR = p_1 - p_0\)</span>.</p></li>
</ul></li>
</ol>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="modèle-logistique-pour-odds-proportionnels" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Modèle logistique pour <em>odds</em> proportionnels</h1>
<p>Ces modèles sont adaptés quand la variable à expliquer est qualitative ordonnée. p151 du pdf</p>
<div style="page-break-after: always;"></div>
</section>
<section id="modèle-de-poisson-et-binomial-négatif-pour-taux-dincidence" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Modèle de Poisson et binomial négatif pour taux d’incidence</h1>
<p>Variable de type “compte” (= entier positif)</p>
<p>= nombre d’occurences d’un évènement dans un intervalle de temps donné (= nombre de buts marqués, d’œufs pondus…)</p>
<p>Les modèles de Poisson et binomial négatif permettent de modéliser une variable de type “compte” en fonction de variables explicatives quantitatives ou qualitatives.</p>
<p>Définition :</p>
<ul>
<li><p>Ce sont des GLM (= modèles linéaires généralisés)</p></li>
<li><p>Fonction lien log = logarithme naturel</p></li>
<li><p>Structure d’erreur de type Poisson.</p></li>
</ul>
<section id="pourquoi-les-modèles-linéaires-classiques-ne-sont-pas-adaptés" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="pourquoi-les-modèles-linéaires-classiques-ne-sont-pas-adaptés"><span class="header-section-number">5.1</span> Pourquoi les modèles linéaires classiques ne sont pas adaptés</h2>
<p>Données de compte : ne remplissent pas les conditions de validité des modèles linéaires classiques.</p>
<ul>
<li><p>Ne suivent pas une loi normale (mais une loi de Poisson)</p></li>
<li><p>Leur variance n’est pas constante (mais proportionnelle à la moyenne)</p></li>
</ul>
</section>
<section id="la-distribution-de-poisson" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="la-distribution-de-poisson"><span class="header-section-number">5.2</span> La distribution de Poisson</h2>
<p>La distribution de Poisson est une distribution de probabilité discrète qui décrit le nombre d’événements se produisant dans un intervalle de temps ou d’espace fixe, lorsque ces événements se produisent avec une moyenne constante et indépendamment les uns des autres.</p>
<p>Équation :</p>
<p><span class="math display">\[
P(X = k) = \frac{\lambda^k e^{-\lambda}}{k!}
\]</span></p>
<p>Avec :</p>
<ul>
<li><p><span class="math inline">\(P(X = k)\)</span> : probabilité d’observer exactement <span class="math inline">\(k\)</span> événements dans l’intervalle</p></li>
<li><p><span class="math inline">\(\lambda\)</span> : moyenne (et variance) du nombre d’événements dans l’intervalle</p></li>
<li><p><span class="math inline">\(e\)</span> : base du logarithme naturel (environ 2,71828)</p></li>
<li><p><span class="math inline">\(k!\)</span> : factorielle de <span class="math inline">\(k\)</span> (produit des entiers de 1 à <span class="math inline">\(k\)</span>)</p></li>
</ul>
<p>Donc la distribution de Poisson est ainsi définie par un seul paramètre : Lambda !</p>
<p>Exemples de distributions de poisson avec différentes valeurs de λ :</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="S1_4_Modeles_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>