project:
  type: default
  render:
    - poly_revision_nsn.qmd
    - poly_revision_RC_codex.qmd
    - poly_revision_epi_codex.qmd
    - poly_revision_intermediaires_2026.qmd
    - poly_revisions_epi_2026.qmd
    - poly_revisions_RC_2026.qmd
  post-render:
    - ./publish_to_docs.sh
