<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>S5_3_GLM : Modèles linéaires généralisés</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="S5_3_1_GLM_files/libs/clipboard/clipboard.min.js"></script>
<script src="S5_3_1_GLM_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="S5_3_1_GLM_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="S5_3_1_GLM_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="S5_3_1_GLM_files/libs/quarto-html/popper.min.js"></script>
<script src="S5_3_1_GLM_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="S5_3_1_GLM_files/libs/quarto-html/anchor.min.js"></script>
<link href="S5_3_1_GLM_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="S5_3_1_GLM_files/libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="S5_3_1_GLM_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="S5_3_1_GLM_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="S5_3_1_GLM_files/libs/bootstrap/bootstrap-d6a003b94517c951b2d65075d42fb01b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a>
  <ul>
  <li><a href="#retour-sur-le-modèle-linéaire-simple" id="toc-retour-sur-le-modèle-linéaire-simple" class="nav-link" data-scroll-target="#retour-sur-le-modèle-linéaire-simple"><span class="header-section-number">1.1</span> Retour sur le modèle linéaire simple</a></li>
  <li><a href="#modèles-linéaires-généralisés-glm" id="toc-modèles-linéaires-généralisés-glm" class="nav-link" data-scroll-target="#modèles-linéaires-généralisés-glm"><span class="header-section-number">1.2</span> Modèles linéaires généralisés (GLM)</a>
  <ul>
  <li><a href="#modèle-logistique" id="toc-modèle-logistique" class="nav-link" data-scroll-target="#modèle-logistique"><span class="header-section-number">1.2.1</span> Modèle logistique</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#définition-des-risques" id="toc-définition-des-risques" class="nav-link" data-scroll-target="#définition-des-risques"><span class="header-section-number">2</span> Définition des risques</a>
  <ul>
  <li><a href="#exemple" id="toc-exemple" class="nav-link" data-scroll-target="#exemple"><span class="header-section-number">2.1</span> Exemple</a></li>
  <li><a href="#mesures-dassociations" id="toc-mesures-dassociations" class="nav-link" data-scroll-target="#mesures-dassociations"><span class="header-section-number">2.2</span> Mesures d’associations</a></li>
  <li><a href="#interprétation-des-risques" id="toc-interprétation-des-risques" class="nav-link" data-scroll-target="#interprétation-des-risques"><span class="header-section-number">2.3</span> Interprétation des risques</a>
  <ul>
  <li><a href="#exemple-1" id="toc-exemple-1" class="nav-link" data-scroll-target="#exemple-1"><span class="header-section-number">2.3.1</span> Exemple</a></li>
  </ul></li>
  <li><a href="#calcul-des-or-et-rr-dans-un-tableau-de-contingence" id="toc-calcul-des-or-et-rr-dans-un-tableau-de-contingence" class="nav-link" data-scroll-target="#calcul-des-or-et-rr-dans-un-tableau-de-contingence"><span class="header-section-number">2.4</span> Calcul des OR et RR dans un tableau de contingence</a>
  <ul>
  <li><a href="#exemple-numérique-avec-r" id="toc-exemple-numérique-avec-r" class="nav-link" data-scroll-target="#exemple-numérique-avec-r"><span class="header-section-number">2.4.1</span> Exemple numérique avec R</a></li>
  <li><a href="#intervalles-de-confiance-des-or-et-rr" id="toc-intervalles-de-confiance-des-or-et-rr" class="nav-link" data-scroll-target="#intervalles-de-confiance-des-or-et-rr"><span class="header-section-number">2.4.2</span> Intervalles de confiance des OR et RR</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#régression-logistique-univariable" id="toc-régression-logistique-univariable" class="nav-link" data-scroll-target="#régression-logistique-univariable"><span class="header-section-number">3</span> Régression logistique univariable</a>
  <ul>
  <li><a href="#introduction-1" id="toc-introduction-1" class="nav-link" data-scroll-target="#introduction-1"><span class="header-section-number">3.1</span> Introduction</a></li>
  <li><a href="#transformation-logistique" id="toc-transformation-logistique" class="nav-link" data-scroll-target="#transformation-logistique"><span class="header-section-number">3.2</span> Transformation logistique</a></li>
  <li><a href="#modèle-logistique-1" id="toc-modèle-logistique-1" class="nav-link" data-scroll-target="#modèle-logistique-1"><span class="header-section-number">3.3</span> Modèle logistique</a>
  <ul>
  <li><a href="#si-x-est-une-variable-binaire-01" id="toc-si-x-est-une-variable-binaire-01" class="nav-link" data-scroll-target="#si-x-est-une-variable-binaire-01"><span class="header-section-number">3.3.1</span> Si X est une variable binaire (0/1) :</a></li>
  <li><a href="#si-x-est-une-variable-catégorielle-à-3-valeurs-0-1-2" id="toc-si-x-est-une-variable-catégorielle-à-3-valeurs-0-1-2" class="nav-link" data-scroll-target="#si-x-est-une-variable-catégorielle-à-3-valeurs-0-1-2"><span class="header-section-number">3.3.2</span> Si X est une variable catégorielle à 3 valeurs (0, 1, 2) :</a></li>
  <li><a href="#si-x-est-une-variable-catégorielle-à-k-valeurs" id="toc-si-x-est-une-variable-catégorielle-à-k-valeurs" class="nav-link" data-scroll-target="#si-x-est-une-variable-catégorielle-à-k-valeurs"><span class="header-section-number">3.3.3</span> Si X est une variable catégorielle à K valeurs</a></li>
  <li><a href="#si-x-est-une-variable-continue-quantitative" id="toc-si-x-est-une-variable-continue-quantitative" class="nav-link" data-scroll-target="#si-x-est-une-variable-continue-quantitative"><span class="header-section-number">3.3.4</span> Si X est une variable continue / quantitative</a></li>
  </ul></li>
  <li><a href="#fonction-de-vraisemblance" id="toc-fonction-de-vraisemblance" class="nav-link" data-scroll-target="#fonction-de-vraisemblance"><span class="header-section-number">3.4</span> Fonction de vraisemblance</a></li>
  <li><a href="#test-de-wald" id="toc-test-de-wald" class="nav-link" data-scroll-target="#test-de-wald"><span class="header-section-number">3.5</span> Test de Wald</a></li>
  <li><a href="#exemple-avec-r" id="toc-exemple-avec-r" class="nav-link" data-scroll-target="#exemple-avec-r"><span class="header-section-number">3.6</span> Exemple avec R</a></li>
  </ul></li>
  <li><a href="#régression-logistique-multivariable" id="toc-régression-logistique-multivariable" class="nav-link" data-scroll-target="#régression-logistique-multivariable"><span class="header-section-number">4</span> Régression logistique multivariable</a>
  <ul>
  <li><a href="#principe" id="toc-principe" class="nav-link" data-scroll-target="#principe"><span class="header-section-number">4.1</span> Principe</a>
  <ul>
  <li><a href="#principe-général" id="toc-principe-général" class="nav-link" data-scroll-target="#principe-général"><span class="header-section-number">4.1.1</span> Principe général</a></li>
  <li><a href="#hypothèse-de-multiplicativité-des-effets" id="toc-hypothèse-de-multiplicativité-des-effets" class="nav-link" data-scroll-target="#hypothèse-de-multiplicativité-des-effets"><span class="header-section-number">4.1.2</span> Hypothèse de multiplicativité des effets</a></li>
  <li><a href="#notion-dinteraction" id="toc-notion-dinteraction" class="nav-link" data-scroll-target="#notion-dinteraction"><span class="header-section-number">4.1.3</span> Notion d’interaction</a></li>
  </ul></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="S5_3_1_GLM.docx"><i class="bi bi-file-word"></i>MS Word</a></li><li><a href="../S5_3_1_GLM.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">S5_3_GLM : Modèles linéaires généralisés</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introduction" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introduction</h1>
<section id="retour-sur-le-modèle-linéaire-simple" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="retour-sur-le-modèle-linéaire-simple"><span class="header-section-number">1.1</span> Retour sur le modèle linéaire simple</h2>
<p>BAS : score quantitatif de dévoleppement cognitif</p>
<p>Dans ce tableau :</p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 7%">
<col style="width: 19%">
<col style="width: 27%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th>Durée de l’allaitement maternel</th>
<th>Moyennes (n)</th>
<th>Coefficients bruts (IC 95%) (n=10 944)</th>
<th>Coefficients partiellement ajustés (IC 95%) (n=10 929)</th>
<th>Coefficients complètement ajustés (IC 95%) (n=10 416)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Jamais</td>
<td>106.5 (3825)</td>
<td>Reference</td>
<td>Reference</td>
<td>Reference</td>
</tr>
<tr class="even">
<td>&lt; 2,0 mois</td>
<td>110.2 (2901)</td>
<td>3.7 (2.8–4.6)</td>
<td>0.7 (–0.1–1.5)</td>
<td>0.7 (–0.1–1.5)</td>
</tr>
<tr class="odd">
<td>2,0–3,9 mois</td>
<td>111.8 (1047)</td>
<td>5.4 (4.1–6.6)</td>
<td>1.2 (0–2.4)</td>
<td>1.2 (0–2.4)</td>
</tr>
<tr class="even">
<td>4,0–5,9 mois</td>
<td>113.0 (889)</td>
<td>6.5 (5.1–7.9)</td>
<td>1.2 (0–2.5)</td>
<td>1.0 (–0.3–2.3)</td>
</tr>
<tr class="odd">
<td>6,0–11,9 mois</td>
<td>114.1 (1392)</td>
<td>7.7 (6.5–8.8)</td>
<td>2.2 (1.2–3.2)</td>
<td>2.0 (1.0–3.0)</td>
</tr>
<tr class="even">
<td>≥ 12,0 mois</td>
<td>114.2 (890)</td>
<td>7.7 (6.6–8.9)</td>
<td>2.4 (1.3–3.5)</td>
<td>2.4 (1.3–3.6)</td>
</tr>
</tbody>
</table>
<ul>
<li><p>Durée d’allaitement : variable explicative <strong>catégorielle ordinale</strong> en 6 niveaux : Jamais ; &lt; 2 mois ; 2-3,9 mois ; 4-5,9 mois ; 6-11,9 mois ; ≥ 12 mois</p></li>
<li><p>Estimation de l’effet de l’allaitement sur le score BAS</p></li>
<li><p>Modèle avec coefficients “bruts” + partiellement ajustés + ajustés</p></li>
<li><p>“Brut” : analyse univariable = régression linéaire simple</p></li>
<li><p>“Ajustement” : analyse multivariable = régression linéaire multiple</p></li>
</ul>
<p><strong>Questions</strong> :</p>
<ul>
<li><p>Pourquoi le modèle brut est sur 10 944 et le modèle ajusté complet sur 10 416 ?</p>
<ul>
<li>Probablement en raison des données manquantes pour les variables de confusion incluses dans le modèle ajusté complet.</li>
</ul></li>
<li><p>Pourquoi l’intervalle de confiance est diminué dans le modèle ajusté complet par rapport au modèle brut ?</p>
<ul>
<li><p>L’ajustement pour les variables de confusion peut réduire la variabilité non expliquée, ce qui peut conduire à des intervalles de confiance plus étroits.</p></li>
<li><p>Même s’il ne s’agit pas d’une variable de confusion, l’ajout de variables explicatives pertinentes peut améliorer la précision des estimations.</p></li>
</ul></li>
<li><p>Pourquoi pas de p-value ?</p>
<ul>
<li><p>Dans un modèle linéaire, les coefficients s’interprètent comme des différences de moyennes entre les groupes par rapport à la catégorie de référence.</p></li>
<li><p>C’est différent d’un modèle de régression logistique où les coefficients sont des log-odds ratios, et où les p-values sont souvent utilisées pour tester l’association.</p></li>
<li><p>3,7 : différence de moyenne de score de BAS entre le groupe “&lt; 2 mois” et le groupe “Jamais”.</p></li>
</ul></li>
<li><p>Ce ne sont pas des odds ratios ?</p>
<ul>
<li><p>Non, dans un modèle linéaire, les coefficients représentent des différences de moyennes, pas des rapports de cotes.</p></li>
<li><p>Dans un modèle linéaire, la valeur neutre = 0 (pas de différence de moyenne).</p></li>
<li><p><strong>Mesures d’associations (OR, RR, HR) sont des rapports dont la valeur neutre = 1.</strong></p></li>
</ul></li>
<li><p>Pourquoi des catégories d’âge maternelle et pas l’âge en continu ?</p>
<ul>
<li><p>Utilisation de catégories peut faciliter l’interprétation des résultats.</p></li>
<li><p>Utilisation de l’âge en continue reviendrait à faire l’hypothèse d’une relation linéaire entre l’âge maternel et le score BAS, ce qui peut ne pas être approprié.</p></li>
</ul></li>
<li><p>Si on devait avoir une variable quantitative dont il est difficile d’avoir un seuil</p>
<ul>
<li><p>Binarisation en optimisant un seuil (Youden)</p></li>
<li><p>Binarisation par la médiane</p></li>
<li><p>Catégories d’âge</p></li>
</ul></li>
</ul>
<hr>
</section>
<section id="modèles-linéaires-généralisés-glm" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="modèles-linéaires-généralisés-glm"><span class="header-section-number">1.2</span> Modèles linéaires généralisés (GLM)</h2>
<ul>
<li><p>Extension des modèles linéaires pour permettre de modéliser des variables dépendantes qui ne suivent pas une distribution normale.</p></li>
<li><p>Permettent de modéliser des relations entre une variable dépendante et une ou plusieurs variables indépendantes, tout en tenant compte de la nature spécifique de la variable dépendante.</p></li>
<li><p>Composants principaux des GLM :</p>
<ul>
<li><p><strong>Fonction de lien</strong> : établit une relation entre la moyenne de la variable dépendante et les variables indépendantes.</p></li>
<li><p><strong>Distribution de la famille exponentielle</strong> : spécifie la distribution de la variable dépendante (ex. binomiale, Poisson, etc.).</p></li>
</ul></li>
<li><p>Exemples courants de GLM :</p>
<ul>
<li><p>Régression logistique : pour les variables dépendantes binaires (oui/non).</p></li>
<li><p>Régression de Poisson : pour les variables dépendantes de comptage.</p></li>
<li><p>Régression gamma : pour les variables dépendantes continues et positives.</p></li>
</ul></li>
</ul>
<section id="modèle-logistique" class="level3" data-number="1.2.1">
<h3 data-number="1.2.1" class="anchored" data-anchor-id="modèle-logistique"><span class="header-section-number">1.2.1</span> Modèle logistique</h3>
<p>Reprend presque toutes les caractéristiques de la régression linéaire, mais est adapté pour les variables dépendantes binaires.</p>
<ul>
<li><p>possibilité d’obtenir des coefficients bruts ou ajustés</p></li>
<li><p>codage des variables explicatives catégorielles</p></li>
<li><p>interprétation des résultats</p></li>
</ul>
<p>SAUF</p>
<ul>
<li><p>La variable expliquée (critère de jugement) est <strong>BINAIRE</strong> (oui/non, succès/échec, malade/pas malade)</p></li>
<li><p>La force de l’association est mesurée par des <strong>odds ratios (OR)</strong> au lieu de différences de moyennes</p></li>
</ul>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>PLAN DU COURS</strong></p>
<ol type="1">
<li><p>Mesures d’association : RR et OR</p></li>
<li><p>Modèle logistique univariable</p>
<ul>
<li>Interprétation des coefficients</li>
<li>Test statistiques sur les coefficients</li>
</ul></li>
<li><p>Modèle logistique multivariable</p>
<ul>
<li>Notion d’interaction</li>
<li>Construction de modèles multivariables</li>
</ul></li>
</ol>
</div>
</div>
</section>
</section>
</section>
<section id="définition-des-risques" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Définition des risques</h1>
<section id="exemple" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="exemple"><span class="header-section-number">2.1</span> Exemple</h2>
<ul>
<li><p>256 patients avec transplantation de moelle osseuse</p></li>
<li><p>Variable à expliquer Y : rejet de la greffe (oui/non) = variable binaire dichotomique</p></li>
<li><p>Covariable X : dose faible (X = 1) vs dose élevée (X = 0) d’un médicament immunosuppresseur</p></li>
</ul>
<p>Étude du lien entre dose de médicament et risque de rejet de la greffe.</p>
<p>Tableau de contingence :</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>Rejet (Y=1)</th>
<th>Pas de rejet (Y=0)</th>
<th>Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Dose faible (X=1)</td>
<td>37</td>
<td>71</td>
<td>108</td>
</tr>
<tr class="even">
<td>Dose élevée (X=0)</td>
<td>31</td>
<td>117</td>
<td>148</td>
</tr>
<tr class="odd">
<td>Total</td>
<td>68</td>
<td>188</td>
<td>256</td>
</tr>
</tbody>
</table>
<ul>
<li><p>Pourcentage de rejet dans chaque groupe :</p>
<ul>
<li><p>Dose faible : 37/108 ≈ 34%</p></li>
<li><p>Dose élevée : 31/148 ≈ 21%</p></li>
</ul></li>
<li><p>Comparaison de pourcentages = test du chi2</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Tableau de contingence</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>tableau <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">37</span>, <span class="dv">71</span>, <span class="dv">31</span>, <span class="dv">117</span>), <span class="at">ncol =</span> <span class="dv">2</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(tableau) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Rejet"</span>, <span class="st">"Pas de rejet"</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(tableau) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Dose faible"</span>, <span class="st">"Dose élevée"</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>tableau</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Rejet Pas de rejet
Dose faible    37           31
Dose élevée    71          117</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Test du chi2</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(tableau, <span class="at">correct =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  tableau
X-squared = 5.6732, df = 1, p-value = 0.01723</code></pre>
</div>
</div>
<p><strong>Syntaxe</strong> :</p>
<ul>
<li><p><code>matrix(c(a, b, c, d), ncol = 2)</code> : création du tableau de contingence</p></li>
<li><p><code>chisq.test(tableau, correct = FALSE)</code> : test du chi2</p>
<ul>
<li>correct = FALSE : pas de correction de Yates pour les petits effectifs</li>
</ul></li>
</ul>
<p>Interprétation des résultats :</p>
<ul>
<li><p>LIEN significatif</p></li>
<li><p>mais pas de mesure de la force</p></li>
<li><p>pour mesurer la force : on pourrait faire 34/21 = 1,62 = RR</p></li>
</ul>
<p><strong>Questions</strong> :</p>
<ul>
<li><p>Est-ce une mesure de la force de l’association entre dose et rejet ?</p>
<ul>
<li>Non, le test du chi2 indique s’il y a une association statistiquement significative, mais ne quantifie pas la force de cette association.</li>
</ul></li>
<li><p>Est-ce une mesure de la signification statistique ?</p>
<ul>
<li>Oui, le test du chi2 fournit une p-value qui indique si l’association observée est statistiquement significative.</li>
</ul></li>
<li><p>Est-ce que ça dépend de l’effectif ?</p>
<ul>
<li>Oui, la puissance du test du chi2 dépend de la taille de l’échantillon. Des échantillons plus grands peuvent détecter des associations plus faibles.</li>
</ul></li>
</ul>
</section>
<section id="mesures-dassociations" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="mesures-dassociations"><span class="header-section-number">2.2</span> Mesures d’associations</h2>
<p><strong>Risque</strong> : soit un facteur de risque X (Oui = 1, Non = 0) et un événement Y</p>
<ul>
<li><p>R1 = P(Y=1 | X=1) = probabilité que l’événement se produise chez les sujets exposés au facteur de risque X=1</p></li>
<li><p>Dans l’exemple, R1 = 37/108 = 0,3426 (risque que le rejet se produise dans le groupe dose faible)</p></li>
<li><p>R0 = P(Y=1 | X=0) = probabilité que l’événement se produise chez les sujets non exposés au facteur de risque X=0</p></li>
<li><p>Dans l’exemple, R0 = 31/148 = 0,2095 (risque que le rejet se produise dans le groupe dose élevée)</p></li>
</ul>
<p><strong>Ratio de risque = Risque Relatif (RR)</strong></p>
<ul>
<li><p><span class="math inline">\(RR = R_1 / R_0\)</span>.</p></li>
<li><p>Dans le cas de l’exemple au dessus :</p>
<ul>
<li><p><span class="math inline">\(R_1\)</span> = 37/108 = 0,3426 (risque de rejet dans le groupe dose faible)</p></li>
<li><p><span class="math inline">\(R_0\)</span> = 31/148 = 0,2095 (risque de rejet dans le groupe dose élevée)</p></li>
<li><p><span class="math inline">\(RR\)</span> = <span class="math inline">\(R_1\)</span> / <span class="math inline">\(R_0\)</span> = 0,3426 / 0,2095 = 1,61 / R0 = (37/108) / (31/148) = 1,62</p></li>
</ul></li>
</ul>
<p><strong>Cote ou Odds</strong> :</p>
<ul>
<li><p><span class="math inline">\(Odds = R / (1-R)\)</span> = probabilité que l’événement se produise / probabilité que l’événement ne se produise pas</p></li>
<li><p>Par exemple si <span class="math inline">\(R\)</span> vaut 0,75 (risque = 75%)</p></li>
<li><p>O = 0,75 / (1-0,75) = 3 donc la cote est de 3 (3 fois plus de chances que l’événement se produise que de ne pas se produire)</p></li>
</ul>
<p><strong>Rapport de cotes = Odds Ratio (OR)</strong></p>
<ul>
<li><span class="math inline">\(OR = \frac{R_1 / 1 - R_1}{R_0 / 1 - R_0}\)</span></li>
</ul>
<p>RR et OR = 2 manières différentes de mesurer l’association entre variables binaires</p>
</section>
<section id="interprétation-des-risques" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="interprétation-des-risques"><span class="header-section-number">2.3</span> Interprétation des risques</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 54%">
<col style="width: 45%">
</colgroup>
<thead>
<tr class="header">
<th>RR</th>
<th>OR</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><ul>
<li><p>Facilement interprétable</p>
<ul>
<li>Facteur par lequel le risque de Y est multiplié si le facteur X est présent</li>
</ul></li>
<li><p>Pas estimable pour tous les types d’études épidémiologiques (notamment pas pour cas témoins)</p></li>
<li><p>Moins bonnes propriétés statistiques et mathématiques que l’OR</p></li>
</ul></td>
<td><ul>
<li><p>Interpétation moins immédiate (rapport des cotes souvent confondus avec RR)</p></li>
<li><p>Obtenus dans analyses statistiques multivariées</p></li>
<li><p>Estimable dans les enquêtes cas-témoin (maladie à prévalence non estimable)</p></li>
</ul></td>
</tr>
</tbody>
</table>
<section id="exemple-1" class="level3" data-number="2.3.1">
<h3 data-number="2.3.1" class="anchored" data-anchor-id="exemple-1"><span class="header-section-number">2.3.1</span> Exemple</h3>
<ul>
<li><p>100 hommes : 90 ont bu du vin la semaine précédente</p>
<ul>
<li>Odds d’un homme d’avoir bu du vin : 9:1</li>
</ul></li>
<li><p>100 femmes : 20 ont bu</p>
<ul>
<li>Odds : 20/80 : 1:4</li>
</ul></li>
<li><p>OR = 9/0,25 = 36 donc peu interprétable</p></li>
<li><p>RR = 0.9/0.2 = 4,5</p></li>
</ul>
<p>NB : l’OR est symétrique mais pas le RR !</p>
<ul>
<li><p>OR de ne pas boire de vin : 0.11/4 = 1/36 = 1/OR d’avoir bu</p></li>
<li><p>RR de ne pas avoir bu : 0.1/0.8 = 1/8 = 0.125 ≠ de 1/RR !!</p></li>
</ul>
</section>
</section>
<section id="calcul-des-or-et-rr-dans-un-tableau-de-contingence" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="calcul-des-or-et-rr-dans-un-tableau-de-contingence"><span class="header-section-number">2.4</span> Calcul des OR et RR dans un tableau de contingence</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th>Rejet (Y=1)</th>
<th>Pas de rejet (Y=0)</th>
<th>Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Dose faible (X=1)</td>
<td>a</td>
<td>b</td>
<td>a+b</td>
</tr>
<tr class="even">
<td>Dose élevée (X=0)</td>
<td>c</td>
<td>d</td>
<td>c+d</td>
</tr>
<tr class="odd">
<td>Total</td>
<td>a+c</td>
<td>b+d</td>
<td>n</td>
</tr>
</tbody>
</table>
<p><u><strong>Risques</strong></u> :</p>
<ul>
<li><p>Risque dans le groupe exposé (X=1) : <span class="math inline">\(R_1 = \frac{a}{a+b}\)</span></p></li>
<li><p>Risque dans le groupe non exposé (X=0) : <span class="math inline">\(R_0 = \frac{c}{c+d}\)</span></p></li>
<li><p>Risque relatif (RR) : <span class="math inline">\(RR = \frac{R_1}{R_0} = \frac{a / (a+b)}{c / (c+d)}\)</span></p></li>
</ul>
<p><u><strong>Côtes</strong></u> :</p>
<ul>
<li><p>Cote dans le groupe exposé (X=1) : <span class="math inline">\(O_1 = \frac{a}{b}\)</span></p></li>
<li><p>Cote dans le groupe non exposé (X=0) : <span class="math inline">\(O_0 = \frac{c}{d}\)</span></p></li>
<li><p>Odds ratio (OR) : <span class="math inline">\(OR = \frac{R_1/(1 - R_1)}{R_0/(1 - R_0)} = \frac{a / b}{c / d} = \frac{ad}{bc}\)</span></p></li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Imaginons qu’on multiplie les effectifs des réponse = oui</p>
<ul>
<li><p>OR : <span class="math inline">\(\frac{(2a) (d)}{(b) (2c)} = \frac{2a*d}{b*2c}\)</span> donc OR ne change pas (un 2 de chaque côté se simplifie)</p>
<ul>
<li>Donc OR beaucoup plus utilisé ! (peut être calculé dans bcp + de cas)</li>
</ul></li>
<li><p>RR : <span class="math inline">\(\frac{(2a)/(2a + b)}{(2c)/(2c + d)}\)</span> donc RR change (le 2 ne se simplifie pas)</p>
<ul>
<li>Le RR dépend de la proportion rejet / non rejet !!</li>
</ul></li>
</ul>
</div>
</div>
<section id="exemple-numérique-avec-r" class="level3" data-number="2.4.1">
<h3 data-number="2.4.1" class="anchored" data-anchor-id="exemple-numérique-avec-r"><span class="header-section-number">2.4.1</span> Exemple numérique avec R</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Effectifs</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="dv">37</span>  <span class="co"># Rejet, Dose faible</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="dv">31</span>  <span class="co"># Pas de rejet, Dose faible</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>c <span class="ot">&lt;-</span> <span class="dv">71</span>  <span class="co"># Rejet, Dose élevée</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="dv">117</span> <span class="co"># Pas de rejet, Dose élevée</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="co">#création et affichage tableau de contingence</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>tableau <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(a, b, c, d), <span class="at">ncol =</span> <span class="dv">2</span>)</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(tableau) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Rejet"</span>, <span class="st">"Pas de rejet"</span>)</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(tableau) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Dose faible"</span>, <span class="st">"Dose élevée"</span>)</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>tableau</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Rejet Pas de rejet
Dose faible    37           71
Dose élevée    31          117</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcul des OR et RR</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>RR <span class="ot">&lt;-</span> a<span class="sc">/</span>(a<span class="sc">+</span>c)<span class="sc">/</span>(b<span class="sc">/</span>(b<span class="sc">+</span>d))</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>OR <span class="ot">&lt;-</span> (a<span class="sc">*</span>d)<span class="sc">/</span>(b<span class="sc">*</span>c)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Affichage des résultats</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>OR</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.966833</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>RR  </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.635603</code></pre>
</div>
</div>
<p>OR = 1.966833</p>
<p>RR = 1.635603</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><p>A-t-on toujours OR &gt; RR ?</p>
<ul>
<li><p>Oui, sauf lorsque l’événement est rare (risque faible), où OR et RR peuvent être proches.</p></li>
<li><p>Dans tous les cas <strong>plus éloigné de 1</strong> que le RR.</p></li>
</ul></li>
</ul>
</div>
</div>
</section>
<section id="intervalles-de-confiance-des-or-et-rr" class="level3" data-number="2.4.2">
<h3 data-number="2.4.2" class="anchored" data-anchor-id="intervalles-de-confiance-des-or-et-rr"><span class="header-section-number">2.4.2</span> Intervalles de confiance des OR et RR</h3>
<ul>
<li>Calcul des intervalles de confiance (IC) pour les OR et RR</li>
</ul>
<p><span class="math display">\[SE = \sqrt{\frac{1}{a} + \frac{1}{b} + \frac{1}{c} + \frac{1}{d}}\]</span></p>
</section>
</section>
</section>
<section id="régression-logistique-univariable" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Régression logistique univariable</h1>
<section id="introduction-1" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="introduction-1"><span class="header-section-number">3.1</span> Introduction</h2>
<p>Exemple.1 : on veut étudier le relation entre pathologie et plusieurs FDR</p>
<p>Exemple 2 : on veut étudier le lien entre survenue d’un évènement et plusieurs évènements intercurrents</p>
<ul>
<li><p>Variable dépendante Y :</p>
<ul>
<li><p>binaire dichotomique (0/1)</p></li>
<li><p>Loi de Bernoulli = success/failure</p></li>
</ul></li>
<li><p>Variables explicatives x1, x2, …, xp :</p>
<ul>
<li><p>quantitatives et/ou qualitatives</p></li>
<li><p>peuvent être continues ou discrètes</p></li>
</ul></li>
<li><p>On a des données chez n patients numérotés i = 1, 2, …, n</p>
<ul>
<li><p><span class="math inline">\(Y_i\)</span> : réponse binaire pour le patient i</p></li>
<li><p><span class="math inline">\(x_{i1}, x_{i2}, ..., x_{ip}\)</span> : covariables explicatives pour le patient i</p></li>
</ul></li>
</ul>
</section>
<section id="transformation-logistique" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="transformation-logistique"><span class="header-section-number">3.2</span> Transformation logistique</h2>
<ul>
<li><p>Au lieu de modéliser le lien entre <span class="math inline">\(Y_i\)</span> et les <span class="math inline">\(x_{i}\)</span> directement, on veut un modèle pour</p>
<p><span class="math inline">\(p_i = E(Y = 1 / X = x_{i})\)</span></p>
<ul>
<li><p>C’est à dire la probabilité que <span class="math inline">\(Y_i = 1\)</span> sachant les valeurs des covariables explicatives pour le patient i</p></li>
<li><p>Exemple : dose plus élevée associée à une plus grande probabilité de réponse</p></li>
</ul></li>
<li><p><span class="math inline">\(p_i\)</span> n’est pas directement observée</p>
<ul>
<li>Peut être estimée chez tous les patients avec <span class="math inline">\(X = x_i\)</span> si variable catégorielle ou groupements</li>
</ul></li>
<li><p>Problème : <span class="math inline">\(p_i = P(Y_i = 1 \| X = x_i)\)</span> est une probabilité</p>
<ul>
<li><p>Doit être comprise entre 0 et 1 (donc les modèles linéaires ne sont pas adaptés car supposent la normalité des résidus)</p></li>
<li><p>Relation linéaire entre <span class="math inline">\(p_i\)</span> et les <span class="math inline">\(x_{i}\)</span> peut donner des valeurs en dehors de [0, 1]</p></li>
</ul></li>
<li><p>Solution : transformation logistique (fonction logit)</p>
<ul>
<li><p><span class="math inline">\(q = logit(p) = \ln\left(\frac{p}{1 - p}\right)\)</span></p></li>
<li><p>même transformation que R/(1-R) = Odds</p></li>
<li><p>prendre le log permet d’avoir quelque chose entre -∞ et +∞</p></li>
</ul></li>
<li><p>Fonction expit (inverse du logit) :</p>
<ul>
<li><p><span class="math inline">\(p = expit(q) = \frac{e^q}{1 + e^q} = \frac{1}{1 + e^{-q}}\)</span></p></li>
<li><p>permet de revenir à une probabilité entre 0 et 1</p></li>
</ul></li>
</ul>
</section>
<section id="modèle-logistique-1" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="modèle-logistique-1"><span class="header-section-number">3.3</span> Modèle logistique</h2>
<p>On modélise logit de <span class="math inline">\(p = P(Y=1 / X = x)\)</span> comme une combinaison linéaire des variables explicatives x1, x2, …, xp</p>
<p>$logit(p) = \alpha + \beta x$</p>
<p>Transformation inverse (expit) :</p>
<p><span class="math inline">\(p = \frac{1}{1 + exp(-\alpha + \beta x)} = \frac{exp(\alpha + \beta x)}{1 + exp(\alpha + \beta x)}\)</span></p>
<section id="si-x-est-une-variable-binaire-01" class="level3" data-number="3.3.1">
<h3 data-number="3.3.1" class="anchored" data-anchor-id="si-x-est-une-variable-binaire-01"><span class="header-section-number">3.3.1</span> Si X est une variable binaire (0/1) :</h3>
<ul>
<li><p>quand X = 0, <span class="math inline">\(logit(p_0) = \\alpha = logit(R_O\)</span></p></li>
<li><p>quand X = 1, <span class="math inline">\(logit(p_1) = \\alpha + \\beta = logit(R_1)\)</span></p></li>
<li><p>OR =</p>
<ul>
<li><p><span class="math inline">\(= \frac{R_1 / (1 - R_1)}{R_0 / (1 - R_0)}\)</span> ou <span class="math inline">\(ln(OR) = logit(R_1) - logit(R_0) = \\beta\)</span>)</p></li>
<li><p><span class="math inline">\(= \frac{exp(\\alpha + \\beta)}{exp(\\alpha)}\)</span></p></li>
<li><p><span class="math inline">\(= exp(\\beta)\)</span></p></li>
</ul></li>
</ul>
<p>Valeur neutre pour l’OR = 1 donc valeur neutre pour β = 0</p>
</section>
<section id="si-x-est-une-variable-catégorielle-à-3-valeurs-0-1-2" class="level3" data-number="3.3.2">
<h3 data-number="3.3.2" class="anchored" data-anchor-id="si-x-est-une-variable-catégorielle-à-3-valeurs-0-1-2"><span class="header-section-number">3.3.2</span> Si X est une variable catégorielle à 3 valeurs (0, 1, 2) :</h3>
<ul>
<li><p>Équivalent à 2 variables binaires indicatrices :</p>
<ul>
<li><p><span class="math inline">\(x_1 = 1\)</span> si X = 1, 0 sinon</p></li>
<li><p><span class="math inline">\(x_2 = 1\)</span> si X = 2, 0 sinon</p></li>
</ul></li>
<li><p>Modèle à 2 variables :</p>
<ul>
<li><p><span class="math inline">\(logit(p) = \\alpha + \\beta_1 x_1 + \\beta_2 x_2\)</span></p></li>
<li><p>quand X = 0, <span class="math inline">\(logit(p_0) = \\alpha = logit(R_0)\)</span></p></li>
<li><p>quand X = 1, <span class="math inline">\(logit(p_1) = \\alpha + \\beta_1 = logit(R_1)\)</span></p></li>
<li><p>quand X = 2, <span class="math inline">\(logit(p_2) = \\alpha + \\beta_2 = logit(R_2)\)</span></p></li>
</ul></li>
<li><p><span class="math inline">\(OR_1 = exp(\\beta_1) vs 0\)</span></p></li>
<li><p><span class="math inline">\(OR_2 = exp(\\beta_2) vs 0\)</span></p></li>
<li><p>OR de 2 vs 1 = <span class="math inline">\(exp(\\beta_2) / exp(\\beta_1) = OR2 / OR1\)</span></p></li>
</ul>
</section>
<section id="si-x-est-une-variable-catégorielle-à-k-valeurs" class="level3" data-number="3.3.3">
<h3 data-number="3.3.3" class="anchored" data-anchor-id="si-x-est-une-variable-catégorielle-à-k-valeurs"><span class="header-section-number">3.3.3</span> Si X est une variable catégorielle à K valeurs</h3>
<ul>
<li><p>Définir une classe de référence (X=0)</p></li>
<li><p>Il y aura K-1 OR par rapport à la classe de référence</p></li>
</ul>
<p>Attention au choix de la classe de référence !</p>
<p>Atention aux regroupements de catégories (si faibles effectifs)</p>
</section>
<section id="si-x-est-une-variable-continue-quantitative" class="level3" data-number="3.3.4">
<h3 data-number="3.3.4" class="anchored" data-anchor-id="si-x-est-une-variable-continue-quantitative"><span class="header-section-number">3.3.4</span> Si X est une variable continue / quantitative</h3>
<p>Hypothèse : relation linéaire de logit(p) avec x (sur le logOR)</p>
<p><span class="math inline">\(f(x) = P(Y = 1/X = x = \frac{1}{1 + exp(-(\alpha + \beta x))}\)</span></p>
<ul>
<li>Risque que Y = 1 sachant que X prend la valeur x</li>
</ul>
<p>Entre deux valeurs x1 et x2 :</p>
<ul>
<li><span class="math inline">\(ln(OR) = \beta (x_1 - x_0)\)</span> ; OR = <span class="math inline">\(exp(\beta (x_1 - x_0))\)</span></li>
</ul>
<p>NB : si pour des variables QUANTITATIVES, l’OR a une UNITÉ</p>
<ul>
<li><p>Pour 1 an d’âge</p></li>
<li><p>pour 10mg de morphine.</p></li>
</ul>
</section>
</section>
<section id="fonction-de-vraisemblance" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="fonction-de-vraisemblance"><span class="header-section-number">3.4</span> Fonction de vraisemblance</h2>
<ul>
<li><p>Estimation des paramètres du modèle (α, β1, β2, …, βp) par la méthode du maximum de vraisemblance</p></li>
<li><p>Vraisemblance = probabilité d’observer les données telles qu’elles ont été observées, en fonction des paramètres du modèle</p></li>
<li><p>On cherche les valeurs des paramètres qui maximisent cette probabilité</p></li>
<li><p>Ordinateur cherche les meilleur coefficient <span class="math inline">\(\alpha\)</span> et <span class="math inline">\(\beta\)</span> qui maximisent la vraisemblance</p></li>
</ul>
</section>
<section id="test-de-wald" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="test-de-wald"><span class="header-section-number">3.5</span> Test de Wald</h2>
<p>Test de Wald = Basé sur le logOR</p>
<ul>
<li><p>logciels fournissent <span class="math inline">\(\beta\)</span> et l’erreur d’estimation SE(<span class="math inline">\(\beta\)</span>) (erreur standard)</p></li>
<li><p>H0 = <span class="math inline">\(\beta\)</span> = 0 (OR = 1)</p>
<ul>
<li><p><span class="math inline">\(\beta\)</span>/se(<span class="math inline">\(\beta\)</span>) suit une loi normale centrée réduite N(0,1)</p></li>
<li><p>comparaison de <span class="math inline">\(\beta\)</span>/se(<span class="math inline">\(\beta\)</span>) à 1,96 pour un test bilatéral au seuil 5%</p></li>
<li><p>calcul du IC à partir de <span class="math inline">\(\beta\)</span> et se(<span class="math inline">\(\beta\)</span>) = <span class="math inline">\(\beta\)</span> ± 1,96*se(<span class="math inline">\(\beta\)</span>)</p></li>
</ul></li>
</ul>
<p>Intervalle de confiance sur OR</p>
<ul>
<li><p>on prend l’exponentielle des bornes de l’IC pour b : [exp(b1) ; exp(b2)]</p></li>
<li><p>intervalle non symétrique autour de exp(b)</p></li>
<li><p>Si IC pour <span class="math inline">\(\beta\)</span> contient 0, IC pour OR contient 1 alors rejet de H0</p></li>
</ul>
</section>
<section id="exemple-avec-r" class="level2" data-number="3.6">
<h2 data-number="3.6" class="anchored" data-anchor-id="exemple-avec-r"><span class="header-section-number">3.6</span> Exemple avec R</h2>
<p>Exemple du rejet de greffe</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Données</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>beta <span class="ot">&lt;-</span> <span class="fu">log</span>(OR)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>beta</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6764248</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimation de l'erreur standard</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>se_beta <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">37</span> <span class="sc">+</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">71</span> <span class="sc">+</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">31</span> <span class="sc">+</span> <span class="dv">1</span><span class="sc">/</span><span class="dv">117</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>se_beta</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2862108</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Test de Wald</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>beta<span class="sc">/</span>se_beta</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.36338</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ici &gt; 1,96 donc on rejette H0</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="co"># pvalue</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span> <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fu">pnorm</span>(<span class="fu">abs</span>(beta<span class="sc">/</span>se_beta)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0181091</code></pre>
</div>
</div>
<ul>
<li><p>OR = 1.96</p></li>
<li><p><span class="math inline">\(\beta\)</span> = log(OR) = 0,68 (b = coefficient)</p></li>
<li><p>se(<span class="math inline">\(\beta\)</span>) = 0,29 (écart-type de l’estimateur)</p></li>
<li><p>Rapport coeffcient/écart-type : b/se(b) = 2,36 &gt; 1,96 donc on rejette H0</p></li>
</ul>
<p>Il y a donc un lien significatif entre infection et décès</p>
<p>Calcul de l’IC à 95% pour OR</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcul des bornes de l'IC pour b</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>beta1 <span class="ot">&lt;-</span> b <span class="sc">-</span> <span class="fl">1.96</span> <span class="sc">*</span> se_beta</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>beta2 <span class="ot">&lt;-</span> b <span class="sc">+</span> <span class="fl">1.96</span> <span class="sc">*</span> se_beta</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>beta1</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 30.43903</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>beta2</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 31.56097</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co">#exponentielle des bornes pour obtenir l'IC pour OR</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>ic_or <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">exp</span>(beta1), <span class="fu">exp</span>(beta2))</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>ic_or</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.657683e+13 5.090453e+13</code></pre>
</div>
</div>
<p>Donc IC à 95%</p>
<ul>
<li><p>pour <span class="math inline">\(\beta\)</span> : 0,68 ± 1,96 * 0.29 = [0,11 ; 1,24]</p></li>
<li><p>pour OR : exponentielle de l’IC de <span class="math inline">\(\beta\)</span> [1,12 ; 3,45].</p></li>
</ul>
</section>
</section>
<section id="régression-logistique-multivariable" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Régression logistique multivariable</h1>
<section id="principe" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="principe"><span class="header-section-number">4.1</span> Principe</h2>
<section id="principe-général" class="level3" data-number="4.1.1">
<h3 data-number="4.1.1" class="anchored" data-anchor-id="principe-général"><span class="header-section-number">4.1.1</span> Principe général</h3>
<p>Variable dichotomique <span class="math inline">\(Y\)</span> dont on veut étudier le lien avec <span class="math inline">\(p\)</span> variables continues ou discrètes : <span class="math inline">\(x_1\)</span>, <span class="math inline">\(x_2\)</span>, …, <span class="math inline">\(x_p\)</span></p>
<p>On dit que <span class="math inline">\(Y\)</span> est</p>
<ul>
<li><p>la variable dépendante</p></li>
<li><p>la variable à expliquer</p></li>
</ul>
<p>On dit que les <span class="math inline">\(X_k\)</span> sont</p>
<ul>
<li><p>les variables indépendantes</p></li>
<li><p>les variables explicatives</p></li>
<li><p>les covariables</p></li>
</ul>
<p>Extension de la régression logistique univariable :</p>
<p><span class="math inline">\(logit(P(Y=1 \| x_1,...,x_p)) = \alpha + \beta_1 x_1 + \beta_2 x_2 + ... + \beta_p x_p\)</span></p>
</section>
<section id="hypothèse-de-multiplicativité-des-effets" class="level3" data-number="4.1.2">
<h3 data-number="4.1.2" class="anchored" data-anchor-id="hypothèse-de-multiplicativité-des-effets"><span class="header-section-number">4.1.2</span> Hypothèse de multiplicativité des effets</h3>
<p>Le modèle logistique multivarié suppose la <strong>multiplicativité</strong> des effets des facteurs de risque</p>
<p>Cas particulier : deux facteurs de risque <span class="math inline">\(X_1\)</span> et <span class="math inline">\(X_2\)</span> prenant deux valeurs (0/1) (ex tabac et alcool et cancer du poumon)</p>
<ul>
<li><p>OR pour <span class="math inline">\(X_1\)</span> = 1 vs 0 : <span class="math inline">\(OR_1 = exp(\beta_1)\)</span></p></li>
<li><p>OR pour <span class="math inline">\(X_2\)</span> = 1 vs 0 : <span class="math inline">\(OR_2 = exp(\beta_2)\)</span></p></li>
<li><p>OR pour <span class="math inline">\(X_1\)</span> = 1 et <span class="math inline">\(X_2\)</span> = 1 = <span class="math inline">\(OR_{1,2} = exp(\beta_1 + \beta_2) = exp(\beta_1) * exp(\beta_2) = OR_1 * OR_2\)</span></p></li>
</ul>
<p>Si OR de cancer de poumon de 3 pour tabac et de 2 pour alcool ; OR pour tabac + alcool = 3 * 2 = 6</p>
<p><strong>Mais il est possible que l’effet combiné soit différent de la multiplication des effets individuels (interaction) !!!</strong></p>
<p>Dans ce cas, il faut ajouter un terme d’interaction dans le modèle</p>
<p>On peut très bien faire un tableau avec les <span class="math inline">\(\beta\)</span> et les <span class="math inline">\(se(\beta)\)</span> !</p>
<ul>
<li><p>Dans ce cas : les <strong>coefficients</strong> sont comparés à 0</p></li>
<li><p>Pour les variables continues ⇒ exprimer les coefficients et les OR <strong>DANS L’UNITÉ</strong> d’origine !</p></li>
<li><p><strong>IC de l’OR :</strong> <span class="math inline">\(exp(\beta ± 1,96 * se(\beta))\)</span></p></li>
</ul>
<p><img src="images/paste-43.png" class="img-fluid" width="697"></p>
</section>
<section id="notion-dinteraction" class="level3" data-number="4.1.3">
<h3 data-number="4.1.3" class="anchored" data-anchor-id="notion-dinteraction"><span class="header-section-number">4.1.3</span> Notion d’interaction</h3>
<p>Interaction entre deux variables explicatives <span class="math inline">\(X_1\)</span> et <span class="math inline">\(X_2\)</span> :</p>
<p><span class="math inline">\(logit(P(Y=1 \| x_1, x_2)) = \alpha + \beta_1 x_1 + \beta_2 x_2 + \beta_3 (x_1 * x_2)\)</span></p>
<p>Rajoute un coefficient et lève l’hypothèse de multiplicativité des OR</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Définitions essentielles : β, estimateur, estimation</strong></p>
<p>Dans un modèle logistique, on étudie l’association entre une variable explicative X (par exemple, dose d’un traitement) et la probabilité d’un événement Y (par exemple, rejet de greffe). Le modèle s’écrit :</p>
<p><span class="math inline">\(\text{logit}(p) = \alpha + \beta X\)</span></p>
<p><span class="math inline">\(p = P(Y = 1 \mid X)\)</span></p>
<p>Dans cette équation :</p>
<ul>
<li><p><span class="math inline">\(\alpha\)</span> est une constante appelée intercept ;</p></li>
<li><p><span class="math inline">\(\beta\)</span> est un paramètre du modèle, qui mesure l’effet de X sur la probabilité de l’événement.</p></li>
</ul>
<p>Un paramètre est une quantité théorique, supposée fixe (c’est à dire constante), qui décrit la relation vraie dans la population étudiée. Dans le modèle logistique, on montre que :</p>
<p><span class="math inline">\(\beta = \log(\text{OR}),\)</span></p>
<p><span class="math inline">\(\text{OR} = e^{\beta}.\)</span></p>
<p>Ainsi :</p>
<ul>
<li><p>si <span class="math inline">\(\beta = 0\)</span>, alors OR = 1 : il n’existe pas d’association entre X et Y ;</p></li>
<li><p>si <span class="math inline">\(\beta &gt; 0\)</span>, alors OR &gt; 1 : présence d’un effet augmentant le risque ;</p></li>
<li><p>si <span class="math inline">\(\beta &lt; 0\)</span>, alors OR &lt; 1 : présence d’un effet protecteur.</p></li>
</ul>
<p>En pratique, on ne connaît jamais la vraie valeur de <span class="math inline">\(\beta\)</span>.</p>
<p>On cherche donc à l’estimer à partir d’un échantillon.</p>
<p>Un estimateur est une méthode de calcul permettant d’approcher un paramètre à partir des données.</p>
<p>La valeur obtenue par cet estimateur dans un échantillon donné est appelée estimation.</p>
<p>Dans la régression logistique, l’estimateur utilisé pour <span class="math inline">\(\beta\)</span> est l’estimateur du maximum de vraisemblance, noté <span class="math inline">\(\hat\beta\)</span> (“bêta chapeau”).</p>
<p>La valeur numérique affichée par le logiciel (par exemple, 0.68) est l’estimation de <span class="math inline">\(\beta\)</span> dans l’échantillon étudié.</p>
<p>⸻</p>
<p><strong>Principe du maximum de vraisemblance : comment obtient-on <span class="math inline">\(\hat\beta\)</span> ?</strong></p>
<p>Pour chaque individu i, le modèle logistique calcule une probabilité prédite de l’événement :</p>
<p><span class="math inline">\(p_i = P(Y_i = 1 \mid X_i) = \frac{e^{\alpha + \beta X_i}}{1 + e^{\alpha + \beta X_i}}.\)</span></p>
<p>Si <span class="math inline">\(Y_i = 1\)</span>, la probabilité d’observer cette valeur est <span class="math inline">\(p_i\)</span>. Si <span class="math inline">\(Y_i = 0\)</span>, cette probabilité est <span class="math inline">\(1 - p_i\)</span>.</p>
<p>On définit alors la vraisemblance totale des paramètres <span class="math inline">\(\alpha\)</span> et <span class="math inline">\(\beta\)</span> comme la probabilité d’observer l’ensemble des données :</p>
<p><span class="math inline">\(L(\alpha,\beta)\)</span> <span class="math inline">\(= \prod_{i=1}^n p_i^{Y_i}(1-p_i)^{1-Y_i}.\)</span></p>
<p>Le principe du maximum de vraisemblance consiste à choisir les valeurs <span class="math inline">\(\hat\alpha\)</span> et <span class="math inline">\(\hat\beta\)</span> qui maximisent cette probabilité.</p>
<p>Autrement dit, on sélectionne les paramètres qui rendent les données observées les plus plausibles selon le modèle.</p>
<p>Pour des raisons numériques, on maximise généralement la log-vraisemblance :</p>
<p><span class="math inline">\(\ell(\alpha,\beta)\)</span> <span class="math inline">\(= \sum_{i=1}^n \left[ Y_i\log(p_i) + (1-Y_i)\log(1 - p_i)\right],\)</span></p>
<p>ce qui est équivalent à maximiser la vraisemblance elle-même.</p>
<p>Le logiciel recherche alors les valeurs de <span class="math inline">\(\alpha\)</span> et <span class="math inline">\(\beta\)</span> qui maximisent <span class="math inline">\(\ell(\alpha,\beta)\)</span>. La valeur obtenue pour <span class="math inline">\(\beta\)</span> est l’estimation <span class="math inline">\(\hat\beta\)</span>.</p>
<p>⸻</p>
<p><strong>Erreur standard : quantifier l’incertitude sur l’estimation <span class="math inline">\(\hat\beta\)</span></strong></p>
<p>Si l’on refaisait l’étude plusieurs fois sur des échantillons différents, on n’obtiendrait pas toujours la même estimation <span class="math inline">\(\hat\beta\)</span>. L’estimateur <span class="math inline">\(\hat\beta\)</span> varie d’un échantillon à l’autre : il s’agit d’une variable aléatoire.</p>
<p>L’erreur standard <span class="math inline">\(\text{SE}(\hat\beta)\)</span> mesure l’ampleur typique de cette variabilité. Elle correspond à la racine carrée de la variance théorique de l’estimateur. Plus <span class="math inline">\(\text{SE}(\hat\beta)\)</span> est petit, plus l’estimateur est précis.</p>
<p>Cette erreur standard est calculée (ou approximée) automatiquement par le logiciel à partir de la dérivée seconde de la log-vraisemblance (matrice d’information de Fisher).</p>
<p>⸻</p>
<p><strong>Standardisation de l’estimateur et loi normale centrée réduite</strong></p>
<p>Dans les modèles logistiques, et plus largement dans les modèles estimés par maximum de vraisemblance, un résultat fondamental est que, sous certaines conditions (échantillon suffisamment grand, modèle correctement spécifié), l’estimateur <span class="math inline">\(\hat\beta\)</span> suit approximativement une loi normale de moyenne <span class="math inline">\(\beta\)</span> et de variance <span class="math inline">\(\text{SE}(\hat\beta)^2\)</span>.</p>
<p>Sous l’hypothèse nulle <span class="math inline">\(H_0 : \beta = 0\)</span>, on a donc :</p>
<p><span class="math inline">\(\hat\beta \approx \mathcal{N}(0, \text{SE}(\hat\beta)^2).\)</span></p>
<p>Pour exploiter ce résultat, on standardise l’estimateur, c’est-à-dire qu’on le transforme en une variable sans unité, mesurant la distance à 0 en nombre d’erreurs standard :</p>
<p><span class="math inline">\(Z = \frac{\hat\beta - 0}{\text{SE}(\hat\beta)} = \frac{\hat\beta}{\text{SE}(\hat\beta)}.\)</span> Cette variable Z suit alors approximativement une loi normale centrée réduite <span class="math inline">\(\mathcal{N}(0,1)\)</span>, c’est-à-dire une loi normale de moyenne 0 et de variance 1.</p>
<p>Cette propriété est à la base du test de Wald.</p>
<p>⸻</p>
<p><strong>Test de Wald : définition, interprétation, limites</strong></p>
<p>Principe du test</p>
<p>On souhaite tester :</p>
<p><span class="math inline">\(H_0 : \beta = 0\)</span></p>
<p><span class="math inline">\(\text{vs}\)</span></p>
<p><span class="math inline">\(H_1 : \beta \neq 0.\)</span></p>
<p>Le test de Wald utilise la statistique :</p>
<p><span class="math inline">\(W = \frac{\hat\beta}{\text{SE}(\hat\beta)}.\)</span></p>
<p>Sous <span class="math inline">\(H_0 : \beta = 0\)</span>, <span class="math inline">\(W\)</span> suit approximativement une loi normale centrée réduite. Pour un test bilatéral au seuil de 5 %, on rejette <span class="math inline">\(H_0\)</span> si :</p>
<p><span class="math inline">\(|W| &gt; 1.96.\)</span></p>
<p>La p-value se déduit de la loi normale. L’intervalle de confiance de <span class="math inline">\(\beta\)</span> est :</p>
<p><span class="math inline">\(\hat\beta \pm 1.96 \times \text{SE}(\hat\beta).\)</span></p>
<p>L’intervalle de confiance de l’odds ratio s’obtient en exponentiant les bornes.</p>
<p><strong>Limites et précautions sur le test de Wald</strong>*</p>
<p>Le test de Wald repose sur des approximations asymptotiques. Il peut être peu fiable dans plusieurs situations : 1. Échantillons de petite taille</p>
<pre><code>-   L’approximation normale est mauvaise et le test peut être trop libéral ou trop conservateur.</code></pre>
<ol start="2" type="1">
<li><p>Événements rares</p>
<ul>
<li>Si l’événement étudié est très rare, <span class="math inline">\(\hat\beta\)</span> peut avoir une distribution très asymétrique. Les intervalles de confiance peuvent être trop étroits ou décalés.</li>
</ul></li>
<li><p>Effets très importants (odds ratios très élevés)</p>
<ul>
<li>Dans ces cas, la distribution de <span class="math inline">\(\hat\beta\)</span> est fortement asymétrique. Les intervalles basés sur Wald peuvent être inadaptés.</li>
</ul></li>
<li><p>Séparation complète ou quasi-complète</p>
<ul>
<li>Si une covariable prédit parfaitement l’événement (par exemple, tous les événements surviennent dans un seul groupe), <span class="math inline">\(\hat\beta\)</span> “diverge” et le test de Wald n’est plus utilisable.</li>
</ul></li>
</ol>
<p>Dans ces situations, il est souvent préférable d’utiliser des méthodes alternatives comme la régression logistique pénalisée (méthode de Firth), des tests exacts, ou le test du rapport de vraisemblance.</p>
<p>⸻</p>
<p><strong>Test du rapport de vraisemblance (Likelihood Ratio Test)</strong></p>
<p>Le test du rapport de vraisemblance (LRT) compare deux modèles emboîtés : un modèle réduit (sans la covariable testée) et un modèle complet (avec la covariable).</p>
<p>Pour tester <span class="math inline">\(\beta = 0\)</span>, on compare :</p>
<ul>
<li><p>modèle réduit : <span class="math inline">\(\text{logit}(p) = \alpha\)</span> ;</p></li>
<li><p>modèle complet : <span class="math inline">\(\text{logit}(p) = \alpha + \beta X\)</span>.</p></li>
</ul>
<p>Le logiciel calcule la log-vraisemblance maximale des deux modèles :</p>
<ul>
<li><p><span class="math inline">\(\ell_{\text{réduit}} : modèle sans X\)</span> ;</p></li>
<li><p><span class="math inline">\(\ell_{\text{complet}} : modèle avec X\)</span>.</p></li>
</ul>
<p>La statistique de test est :</p>
<p><span class="math inline">\(\Lambda = 2(\ell_{\text{complet}} - \ell_{\text{réduit}}).\)</span></p>
<p>Sous <span class="math inline">\(H_0 : \beta = 0\)</span> et sous des conditions générales, <span class="math inline">\(\Lambda\)</span> suit une loi du <span class="math inline">\(\chi^2\)</span> avec un degré de liberté égal au nombre de paramètres testés (ici, 1). On en déduit une p-value.</p>
<p>Le LRT présente plusieurs avantages :</p>
<ul>
<li><p>il repose sur la comparaison globale des modèles et non sur l’approximation locale autour de ;</p></li>
<li><p>il est plus robuste que le test de Wald lorsque l’échantillon est petit, lorsque les événements sont rares, ou lorsque l’effet étudié est important ;</p></li>
<li><p>il permet de tester simultanément plusieurs coefficients (par exemple, pour des variables qualitatives à plusieurs modalités).</p></li>
</ul>
<p>⸻</p>
<p><strong>Résumé</strong></p>
<ul>
<li><p><span class="math inline">\(\beta\)</span> est le paramètre du modèle logistique correspondant au log(odds ratio).</p></li>
<li><p><span class="math inline">\(\hat\beta\)</span> est son estimation obtenue par maximum de vraisemblance, en choisissant les valeurs qui rendent les données observées les plus probables.</p></li>
<li><p>L’erreur standard de <span class="math inline">\(\hat\beta\)</span> mesure la variabilité de l’estimation d’un échantillon à l’autre.</p></li>
<li><p>Le test de Wald repose sur la standardisation de <span class="math inline">\(\hat\beta\)</span>, qui suit approximativement une loi normale centrée réduite sous l’hypothèse nulle.</p></li>
<li><p>Ce test peut être peu fiable en cas de petits échantillons, d’événements rares ou d’effets extrêmes.</p></li>
<li><p>Le test du rapport de vraisemblance compare un modèle avec et sans la covariable, en s’appuyant sur la log-vraisemblance. Il est souvent plus robuste et peut être utilisé pour tester plusieurs coefficients simultanément.</p></li>
</ul>
</div>
</div>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>