<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>S8_2_Modèles linéaires mixtes</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="S8_2_Modeles_lineaires_mixtes_files/libs/clipboard/clipboard.min.js"></script>
<script src="S8_2_Modeles_lineaires_mixtes_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="S8_2_Modeles_lineaires_mixtes_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="S8_2_Modeles_lineaires_mixtes_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="S8_2_Modeles_lineaires_mixtes_files/libs/quarto-html/popper.min.js"></script>
<script src="S8_2_Modeles_lineaires_mixtes_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="S8_2_Modeles_lineaires_mixtes_files/libs/quarto-html/anchor.min.js"></script>
<link href="S8_2_Modeles_lineaires_mixtes_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="S8_2_Modeles_lineaires_mixtes_files/libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="S8_2_Modeles_lineaires_mixtes_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="S8_2_Modeles_lineaires_mixtes_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="S8_2_Modeles_lineaires_mixtes_files/libs/bootstrap/bootstrap-d6a003b94517c951b2d65075d42fb01b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#plan-du-cours" id="toc-plan-du-cours" class="nav-link active" data-scroll-target="#plan-du-cours"><span class="header-section-number">1</span> Plan du cours</a></li>
  <li><a href="#introduction-aux-modèles-linéaires-mixtes" id="toc-introduction-aux-modèles-linéaires-mixtes" class="nav-link" data-scroll-target="#introduction-aux-modèles-linéaires-mixtes"><span class="header-section-number">2</span> Introduction aux modèles linéaires mixtes</a>
  <ul>
  <li><a href="#quelques-stratégies-pour-gérer-la-non-indépendance-des-observations" id="toc-quelques-stratégies-pour-gérer-la-non-indépendance-des-observations" class="nav-link" data-scroll-target="#quelques-stratégies-pour-gérer-la-non-indépendance-des-observations"><span class="header-section-number">2.1</span> Quelques stratégies pour gérer la non-indépendance des observations</a></li>
  <li><a href="#le-modèle-linéaire-mixte-formulation-mathématique" id="toc-le-modèle-linéaire-mixte-formulation-mathématique" class="nav-link" data-scroll-target="#le-modèle-linéaire-mixte-formulation-mathématique"><span class="header-section-number">2.2</span> Le modèle linéaire mixte (formulation mathématique)</a></li>
  <li><a href="#estimation" id="toc-estimation" class="nav-link" data-scroll-target="#estimation"><span class="header-section-number">2.3</span> Estimation</a></li>
  <li><a href="#types-destimateurs" id="toc-types-destimateurs" class="nav-link" data-scroll-target="#types-destimateurs"><span class="header-section-number">2.4</span> Types d’estimateurs</a></li>
  </ul></li>
  <li><a href="#utilisation-de-r-pour-les-modèles-linéaires-mixtes" id="toc-utilisation-de-r-pour-les-modèles-linéaires-mixtes" class="nav-link" data-scroll-target="#utilisation-de-r-pour-les-modèles-linéaires-mixtes"><span class="header-section-number">3</span> Utilisation de R pour les modèles linéaires mixtes</a>
  <ul>
  <li><a href="#représentations" id="toc-représentations" class="nav-link" data-scroll-target="#représentations"><span class="header-section-number">3.1</span> Représentations</a>
  <ul>
  <li><a href="#version-wide-large" id="toc-version-wide-large" class="nav-link" data-scroll-target="#version-wide-large"><span class="header-section-number">3.1.1</span> Version Wide (large)</a></li>
  <li><a href="#version-long-longue" id="toc-version-long-longue" class="nav-link" data-scroll-target="#version-long-longue"><span class="header-section-number">3.1.2</span> Version Long (longue)</a></li>
  </ul></li>
  <li><a href="#modèle-linéaire-mixte-avec-r" id="toc-modèle-linéaire-mixte-avec-r" class="nav-link" data-scroll-target="#modèle-linéaire-mixte-avec-r"><span class="header-section-number">3.2</span> Modèle linéaire mixte avec R</a>
  <ul>
  <li><a href="#utilisation-de-la-fonction-lmer-du-package-lme4" id="toc-utilisation-de-la-fonction-lmer-du-package-lme4" class="nav-link" data-scroll-target="#utilisation-de-la-fonction-lmer-du-package-lme4"><span class="header-section-number">3.2.1</span> Utilisation de la fonction <code>lmer()</code> du package <code>lme4</code></a></li>
  <li><a href="#utilisation-de-la-fonction-lme-du-package-nlme" id="toc-utilisation-de-la-fonction-lme-du-package-nlme" class="nav-link" data-scroll-target="#utilisation-de-la-fonction-lme-du-package-nlme"><span class="header-section-number">3.2.2</span> Utilisation de la fonction <code>lme()</code> du package <code>nlme</code></a></li>
  <li><a href="#exemple-3-lmertest-obtention-de-p-values-pour-les-effets-fixes" id="toc-exemple-3-lmertest-obtention-de-p-values-pour-les-effets-fixes" class="nav-link" data-scroll-target="#exemple-3-lmertest-obtention-de-p-values-pour-les-effets-fixes"><span class="header-section-number">3.2.3</span> Exemple 3 : ‘lmerTest’ : obtention de p-values pour les effets fixes</a></li>
  <li><a href="#pertinence-de-la-variable-time-globale-dans-le-modèle" id="toc-pertinence-de-la-variable-time-globale-dans-le-modèle" class="nav-link" data-scroll-target="#pertinence-de-la-variable-time-globale-dans-le-modèle"><span class="header-section-number">3.2.4</span> Pertinence de la variable <code>time</code> globale dans le modèle</a></li>
  <li><a href="#pertinence-de-la-variable-sex-dans-le-modèle" id="toc-pertinence-de-la-variable-sex-dans-le-modèle" class="nav-link" data-scroll-target="#pertinence-de-la-variable-sex-dans-le-modèle"><span class="header-section-number">3.2.5</span> Pertinence de la variable <code>sex</code> dans le modèle</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#applications-études-publiées" id="toc-applications-études-publiées" class="nav-link" data-scroll-target="#applications-études-publiées"><span class="header-section-number">4</span> Applications (études publiées)</a>
  <ul>
  <li><a href="#déclin-cognitif-des-personnes-âgées-aux-états-unis-pendant-et-après-la-covid" id="toc-déclin-cognitif-des-personnes-âgées-aux-états-unis-pendant-et-après-la-covid" class="nav-link" data-scroll-target="#déclin-cognitif-des-personnes-âgées-aux-états-unis-pendant-et-après-la-covid"><span class="header-section-number">4.1</span> Déclin cognitif des personnes âgées aux États-Unis pendant et après la Covid !!</a></li>
  <li><a href="#analyse-statistique" id="toc-analyse-statistique" class="nav-link" data-scroll-target="#analyse-statistique"><span class="header-section-number">4.2</span> Analyse statistique</a></li>
  <li><a href="#résultats" id="toc-résultats" class="nav-link" data-scroll-target="#résultats"><span class="header-section-number">4.3</span> Résultats</a></li>
  </ul></li>
  <li><a href="#modèles-linéaires-mixtes-extension" id="toc-modèles-linéaires-mixtes-extension" class="nav-link" data-scroll-target="#modèles-linéaires-mixtes-extension"><span class="header-section-number">5</span> Modèles linéaires mixtes : extension</a>
  <ul>
  <li><a href="#modèles-non-linéaires-mixtes-nlmm" id="toc-modèles-non-linéaires-mixtes-nlmm" class="nav-link" data-scroll-target="#modèles-non-linéaires-mixtes-nlmm"><span class="header-section-number">5.1</span> Modèles non linéaires mixtes (NLMM)</a></li>
  <li><a href="#modèles-linéaires-généralisées-mixtes-glmm" id="toc-modèles-linéaires-généralisées-mixtes-glmm" class="nav-link" data-scroll-target="#modèles-linéaires-généralisées-mixtes-glmm"><span class="header-section-number">5.2</span> Modèles linéaires généralisées mixtes (GLMM)</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="S8_2_Modeles_lineaires_mixtes.docx"><i class="bi bi-file-word"></i>MS Word</a></li><li><a href="../S8_2_Modeles_lineaires_mixtes.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">S8_2_Modèles linéaires mixtes</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="plan-du-cours" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Plan du cours</h1>
</section>
<section id="introduction-aux-modèles-linéaires-mixtes" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Introduction aux modèles linéaires mixtes</h1>
<ul>
<li><p>Principale limitation du modèle linéaire : l’hypothèse des observations indépendantes = indépendance des résidus</p>
<ul>
<li><p>Observations doivent rester indépendantes après avoir été ajustées pour les prédicteurs fixes (âge, sexe)</p></li>
<li><p>Par ex : “patients-trimestres” : ce sont les mêmes patients qui sont mesurés à plusieurs reprises</p></li>
</ul></li>
<li><p>Problème : en pratique, il existe bcp de situation ou c’est pas raisonnable</p>
<ul>
<li><p>patients d’un essai clinique sont inclus dans plusieurs centres : deux patients d’un même centre se ressemblent plus que deux patients de centres différents</p></li>
<li><p>méta-analyse vise à synthétiser les résultats de plusieurs essais thérapeutiques</p></li>
<li><p>unité statistique est la “visite” d’un patient dans un service, mais le même patient peut revenir plusieurs fois</p></li>
<li><p>la même mesure biologique est répétée plusieurs fois chez un même individu (données longitudinales)</p></li>
</ul></li>
<li><p>Conséquence principale : le nombre de patients “effectif” est plus petit que la taille de la base de données <span class="math inline">\(\rightarrow\)</span> inflation de l’erreur de type 1</p></li>
</ul>
<p><a href="https://thomashusson29.github.io/M2biostatistiques/S8_bonus_residus.html">Bonus Résidus</a></p>
<section id="quelques-stratégies-pour-gérer-la-non-indépendance-des-observations" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="quelques-stratégies-pour-gérer-la-non-indépendance-des-observations"><span class="header-section-number">2.1</span> Quelques stratégies pour gérer la non-indépendance des observations</h2>
<ul>
<li><p>Ignorer l’effet centre / le caractère longitudinal</p>
<ul>
<li><p>Par ex : 4 visites pour 1 patient = 1 seul patient</p></li>
<li><p>Problème : perte d’information donc perte de puissance</p></li>
</ul></li>
<li><p>Estimer un modèle par centre / par patient et “combiner” les estimations</p>
<ul>
<li>Problème : pas de quantification de la variabilité inter-centres / inter-patients</li>
</ul></li>
<li><p>Incorporer le centre / le patient comme effet fixe (c’est à dire comme une variable catégorielle / un facteur)</p>
<ul>
<li>Problème : perte de puissance, pas de quantification de la variabilité inter-centres / inter-patients, impossible si bcp de centres avec peu de patients par centre</li>
</ul></li>
</ul>
<p><a href="https://thomashusson29.github.io/M2biostatistiques/S8_B2_Variabilit%C3%A9s%20interindividuelles.html">Bonus Variabilité</a></p>
<p><strong>Stratégie privilégiée</strong> : Modèles linéaires mixtes (MLM) :</p>
<ul>
<li><p>Combine des effets <strong>fixes</strong> : covariables qui ont une influence sur la moyenne dont on veut estimer l’effet</p></li>
<li><p>et des effets <strong>aléatoires</strong> : variables qui modélisent la structure de corrélation entre les observations (rendent compte de la non-indépendance des observations)</p></li>
</ul>
<p>Effets aléatoires : “covariables latentes” qui ne sont pas observées mais qui influencent la variable réponse</p>
<p>(par exemple <span class="math inline">\(\rightarrow\)</span> le fait que les patients d’un même centre se ressemblent plus que des patients de centres différents)</p>
<p><a href="https://thomashusson29.github.io/M2biostatistiques/S8_B3_Effets_fixes_aleatoires.html">Bonus effets</a></p>
<p>Exemple d’effet aléatoire : <strong>niveau de programmation en R dans la salle</strong></p>
<p>Probabilité de réponse dépend de la difficulté du questionnaire : impossible de la modéliser = effet non mesuré et aléatoire = effet aléatoire</p>
</section>
<section id="le-modèle-linéaire-mixte-formulation-mathématique" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="le-modèle-linéaire-mixte-formulation-mathématique"><span class="header-section-number">2.2</span> Le modèle linéaire mixte (formulation mathématique)</h2>
<p>Modèle :<br>
</p>
<p><span class="math display">\[
Y_{ij} = \beta X_{ij} + \gamma_1 Z_{ij} + \epsilon_{ij}
\]</span></p>
<ul>
<li><p><span class="math inline">\(Y_{ij}\)</span> : réponse (quantitative) pour l’observation du patient <span class="math inline">\(j\)</span> issu du cluster <span class="math inline">\(i\)</span> (par ex : mesure biologique au temps <span class="math inline">\(j\)</span> pour le patient <span class="math inline">\(i\)</span>)</p></li>
<li><p><span class="math inline">\(\beta X_{ij}\)</span> : effet fixe (unique ici) dépendant de la variable <span class="math inline">\(X_{ij}\)</span> (âge, sexe, traitement, etc.)</p></li>
<li><p><span class="math inline">\(\gamma_1 Z_{ij}\)</span> : effet aléatoire dépendant de la variable <span class="math inline">\(Z_{ij}\)</span> (par ex : centre, patient, etc.). Le coefficient <span class="math inline">\(\gamma_1\)</span> est commun à tous les patients du cluster <span class="math inline">\(i\)</span></p></li>
<li><p><span class="math inline">\(\epsilon_{ij}\)</span> : erreur aléatoire (résidu) pour l’observation du patient <span class="math inline">\(j\)</span> du cluster <span class="math inline">\(i\)</span> (dont on fait l’hypothèse qu’elle suit une loi normale centrée réduite <span class="math inline">\(N(0,\sigma^2)\)</span>)</p></li>
</ul>
<p>L’effet aléatoire <span class="math inline">\(\gamma_i\)</span> n’est pas observé, il faut spécifier sa loi (<span class="math inline">\(\gamma_i \sim N(0,\sigma^2_Z)\)</span>)</p>
<p>Ainsi, 2 patients du même cluster <span class="math inline">\(i\)</span> se ressemblent plus que 2 patients de clusters différents car ils partagent la même valeur de l’effet aléatoire <span class="math inline">\(\gamma_i\)</span></p>
<p><span class="math inline">\(\rightarrow\)</span> permet de rendre compte de la non-indépendance des observations sur les patients d’un même cluster <span class="math inline">\(i\)</span></p>
<p>2 applications possibles :</p>
<ul>
<li><p>Estimer les effets fixes et prendre en compte la non-indépendance des observations (plusieurs visites par patient, patients dans des centres différents, etc.)</p></li>
<li><p>Estimer séparément les composantes de la variance (variabilité intra-cluster et inter-cluster)</p></li>
</ul>
</section>
<section id="estimation" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="estimation"><span class="header-section-number">2.3</span> Estimation</h2>
<p><span class="math display">\[
Y_{ij} = \beta X_{ij} + \gamma_1 Z_{ij} + \epsilon_{ij}
\]</span></p>
<p>L’ordinateur fournit une estimation :</p>
<ul>
<li><p>des effets fixes <span class="math inline">\(\beta\)</span> et leur incertitude (binaire, catégorielle avec catégorie de référence…) (comme dans un modèle linéaire classique)</p></li>
<li><p>des composantes de la variance :</p>
<ul>
<li><p>variance de l’effet aléatoire : <span class="math inline">\(\sigma_Z^2\)</span> et son incertitude (variabilité inter-cluster)</p></li>
<li><p>variance résiduelle : <span class="math inline">\(\sigma^2\)</span> et son incertitude</p></li>
</ul></li>
</ul>
<p>Avec des modèles plus complexes, il peut y avoir plusieurs effets aléatoires avec une structure de corrélation plus complexe entre eux (matrice de variance-covariance)</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Exemple : questions à un examen (items) posées à des étudiants (individus)</p>
<ul>
<li><p>Caractéristiques des questions (difficulté, type de question, etc.) = effets aléatoires</p></li>
<li><p>Caractéristiques des étudiants (niveau, sexe, etc.) = effets aléatoires</p></li>
</ul>
<p><strong>= Croisement des deux effets aléatoires</strong></p>
<ul>
<li><p>Corrélation intra-questions (les réponses aux questions se ressemblent plus entre elles que les réponses à des questions différentes)</p></li>
<li><p>Corrélation intra-étudiants (les réponses d’un étudiant se ressemblent plus entre elles que les réponses de différents étudiants)</p></li>
</ul>
<p>C’est différent de patients inclus dans des centres (effet emboîté)</p>
<ul>
<li><p>Patients 1 traité dans un centre A</p></li>
<li><p>Patient 2 traité dans un centre B</p></li>
</ul>
<p>Donc les effets sont emboîtés car un patient n’est traité que dans un seul centre</p>
</div>
</div>
<p><strong>2 types d’estimateurs possibles :</strong></p>
<ul>
<li><p>Maximum de vraisemblance (ML)</p></li>
<li><p>Maximum de vraisemblance restreint (REML) = option par défaut dans R</p></li>
</ul>
<p>Bonus : <a href="https://thomashusson29.github.io/M2biostatistiques/S8_B4_Intercept_variances_effets_aleatoires.html">bonus intercept - variances - effets aléatoires</a></p>
</section>
<section id="types-destimateurs" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="types-destimateurs"><span class="header-section-number">2.4</span> Types d’estimateurs</h2>
<ul>
<li><p>Maximum de vraisemblance (ML)</p>
<ul>
<li><p>Variances estimées biaisées, surtout avec de petits échantillons</p></li>
<li><p>Possibilité de faire des tests de rapport de vraisemblance (tester la pertinence de l’ajout d’un effet fixe dans le modèle)</p></li>
</ul></li>
<li><p>Maximum de vraisemblance restreint (REML) = option par défaut dans ```{html}</p>
<ul>
<li><p>Variances estimées non biaisées</p></li>
<li><p>Important, entre autres, pour le calcul de quantités (telles que l’ICC) dépendant des variances</p></li>
</ul></li>
</ul>
<p>Choix de l’estimateur dépend de l’objectif de l’analyse</p>
<ul>
<li><p>Si on veut quantifier un effet traitement en évacuant le côté “données en cluster” = ML</p></li>
<li><p>Si on veut d’évaluer et d’interpréter les composantes de la variance (variabilité intra- et inter-cluster) = REML</p></li>
</ul>
</section>
</section>
<section id="utilisation-de-r-pour-les-modèles-linéaires-mixtes" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Utilisation de R pour les modèles linéaires mixtes</h1>
<p>Charger une base dental.RData contenant des mesures dentaires répétées chez des enfants (quantitatif)</p>
<p>Mesure à 8-10-12-14 ans</p>
<p>2 représentations possibles des données</p>
<section id="représentations" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="représentations"><span class="header-section-number">3.1</span> Représentations</h2>
<section id="version-wide-large" class="level3" data-number="3.1.1">
<h3 data-number="3.1.1" class="anchored" data-anchor-id="version-wide-large"><span class="header-section-number">3.1.1</span> Version Wide (large)</h3>
<ul>
<li><p>1 ligne par individu</p></li>
<li><p>1 colonne par mesure répétée</p></li>
<li><p>Inadapté pour l’analyse avec R</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dental)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 6
     id sex      y8   y10   y12   y14
  &lt;dbl&gt; &lt;fct&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1     1 Girl   21    20    21.5  23  
2     2 Girl   21    21.5  24    25.5
3     3 Girl   20.5  24    24.5  26  
4     4 Girl   23.5  24.5  25    26.5
5     5 Girl   21.5  23    22.5  23.5
6     6 Girl   20    21    21    22.5</code></pre>
</div>
</div>
</section>
<section id="version-long-longue" class="level3" data-number="3.1.2">
<h3 data-number="3.1.2" class="anchored" data-anchor-id="version-long-longue"><span class="header-section-number">3.1.2</span> Version Long (longue)</h3>
<ul>
<li><p>1 ligne par mesure répétée</p></li>
<li><p>1 colonne pour l’âge (temps)</p></li>
<li><p>1 colonne pour la mesure d’intérêt (distance)</p></li>
<li><p>Adapté pour l’analyse avec R</p></li>
</ul>
<p>Utilisation de la fonction <code>melt()</code> du package <code>reshape2</code> pour transformer la base wide en base long.</p>
<p>Syntaxe : <code>melt(data, ..., na.rm = FALSE, value.name = "value")</code></p>
<ul>
<li><p><code>data</code> = Data set to melt</p></li>
<li><p><code>...</code> = further arguments passed to or from other methods.</p></li>
<li><p><code>na.rm</code> = Should NA values be removed from the data set? This will convert explicit missings to implicit missings.</p></li>
<li><p><code>value.name</code> = name of variable used to store values</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>dental_long <span class="ot">=</span> <span class="fu">melt</span>(dental, <span class="at">id.vars=</span><span class="fu">c</span>(<span class="st">"id"</span>,<span class="st">"sex"</span>), <span class="at">variable.name=</span><span class="st">"time"</span>, <span class="at">value.name=</span><span class="st">"distance"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: attributes are not identical across measure variables; they will be
dropped</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>dental_long</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>    id  sex time distance
1    1 Girl   y8     21.0
2    2 Girl   y8     21.0
3    3 Girl   y8     20.5
4    4 Girl   y8     23.5
5    5 Girl   y8     21.5
6    6 Girl   y8     20.0
7    7 Girl   y8     21.5
8    8 Girl   y8     23.0
9    9 Girl   y8     20.0
10  10 Girl   y8     16.5
11  11 Girl   y8     24.5
12  12  Boy   y8     26.0
13  13  Boy   y8     21.5
14  14  Boy   y8     23.0
15  15  Boy   y8     25.5
16  16  Boy   y8     20.0
17  17  Boy   y8     24.5
18  18  Boy   y8     22.0
19  19  Boy   y8     24.0
20  20  Boy   y8     23.0
21  21  Boy   y8     27.5
22  22  Boy   y8     23.0
23  23  Boy   y8     21.5
24  24  Boy   y8     17.0
25  25  Boy   y8     22.5
26  26  Boy   y8     23.0
27  27  Boy   y8     22.0
28   1 Girl  y10     20.0
29   2 Girl  y10     21.5
30   3 Girl  y10     24.0
31   4 Girl  y10     24.5
32   5 Girl  y10     23.0
33   6 Girl  y10     21.0
34   7 Girl  y10     22.5
35   8 Girl  y10     23.0
36   9 Girl  y10     21.0
37  10 Girl  y10     19.0
38  11 Girl  y10     25.0
39  12  Boy  y10     25.0
40  13  Boy  y10     22.5
41  14  Boy  y10     22.5
42  15  Boy  y10     27.5
43  16  Boy  y10     23.5
44  17  Boy  y10     25.5
45  18  Boy  y10     22.0
46  19  Boy  y10     21.5
47  20  Boy  y10     20.5
48  21  Boy  y10     28.0
49  22  Boy  y10     23.0
50  23  Boy  y10     23.5
51  24  Boy  y10     24.5
52  25  Boy  y10     25.5
53  26  Boy  y10     24.5
54  27  Boy  y10     21.5
55   1 Girl  y12     21.5
56   2 Girl  y12     24.0
57   3 Girl  y12     24.5
58   4 Girl  y12     25.0
59   5 Girl  y12     22.5
60   6 Girl  y12     21.0
61   7 Girl  y12     23.0
62   8 Girl  y12     23.5
63   9 Girl  y12     22.0
64  10 Girl  y12     19.0
65  11 Girl  y12     28.0
66  12  Boy  y12     29.0
67  13  Boy  y12     23.0
68  14  Boy  y12     24.0
69  15  Boy  y12     26.5
70  16  Boy  y12     22.5
71  17  Boy  y12     27.0
72  18  Boy  y12     24.5
73  19  Boy  y12     24.5
74  20  Boy  y12     31.0
75  21  Boy  y12     31.0
76  22  Boy  y12     23.5
77  23  Boy  y12     24.0
78  24  Boy  y12     26.0
79  25  Boy  y12     25.5
80  26  Boy  y12     26.0
81  27  Boy  y12     23.5
82   1 Girl  y14     23.0
83   2 Girl  y14     25.5
84   3 Girl  y14     26.0
85   4 Girl  y14     26.5
86   5 Girl  y14     23.5
87   6 Girl  y14     22.5
88   7 Girl  y14     25.0
89   8 Girl  y14     24.0
90   9 Girl  y14     21.5
91  10 Girl  y14     19.5
92  11 Girl  y14     28.0
93  12  Boy  y14     31.0
94  13  Boy  y14     26.5
95  14  Boy  y14     27.5
96  15  Boy  y14     27.0
97  16  Boy  y14     26.0
98  17  Boy  y14     28.5
99  18  Boy  y14     26.5
100 19  Boy  y14     25.5
101 20  Boy  y14     26.0
102 21  Boy  y14     31.5
103 22  Boy  y14     25.0
104 23  Boy  y14     28.0
105 24  Boy  y14     29.5
106 25  Boy  y14     26.0
107 26  Boy  y14     30.0
108 27  Boy  y14     25.0</code></pre>
</div>
</div>
<p>On peut aussi faire avec <code>gather()</code> du package <code>tidyr</code> (tidyverse)</p>
<p>Syntaxe : <code>gather( data, key = "key", value = "value", ..., na.rm = FALSE, convert = FALSE, factor_key = FALSE )</code></p>
<p>avec :</p>
<ul>
<li><p><code>data</code> = data frame.</p></li>
<li><p><code>key</code>, <code>value</code> = Names of new key and value columns, as strings or symbols. This argument is passed by expression and supports quasiquotation (you can unquote strings and symbols).</p></li>
<li><p><code>...</code> = A selection of columns. If empty, all variables are selected. You can supply bare variable names, select all variables between x and z with x:z, exclude y with -y.</p></li>
<li><p><code>na.rm</code> = If TRUE, will remove rows from output where the value column is NA.</p></li>
<li><p><code>convert</code> = If TRUE will automatically run type.convert() on the key column.</p></li>
<li><p><code>factor_key</code> = If FALSE, the default, the key values will be stored as a character vector. If TRUE, will be stored as a factor, which preserves the original ordering of the columns.</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>dental_long2 <span class="ot">=</span> <span class="fu">gather</span>(dental, <span class="at">key=</span><span class="st">"time"</span>, <span class="at">value=</span><span class="st">"distance"</span>, <span class="sc">-</span>id, <span class="sc">-</span>sex)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: attributes are not identical across measure variables; they will be
dropped</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dental_long2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 4
     id sex   time  distance
  &lt;dbl&gt; &lt;fct&gt; &lt;chr&gt;    &lt;dbl&gt;
1     1 Girl  y8        21  
2     2 Girl  y8        21  
3     3 Girl  y8        20.5
4     4 Girl  y8        23.5
5     5 Girl  y8        21.5
6     6 Girl  y8        20  </code></pre>
</div>
</div>
</section>
</section>
<section id="modèle-linéaire-mixte-avec-r" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="modèle-linéaire-mixte-avec-r"><span class="header-section-number">3.2</span> Modèle linéaire mixte avec R</h2>
<p>Pour gérer les données manquantes : pas grave si elles sont MAR. R gère automatiquement les données manquantes en utilisant toutes les données disponibles pour chaque individu (approche “full information maximum likelihood” FIML)</p>
<section id="utilisation-de-la-fonction-lmer-du-package-lme4" class="level3" data-number="3.2.1">
<h3 data-number="3.2.1" class="anchored" data-anchor-id="utilisation-de-la-fonction-lmer-du-package-lme4"><span class="header-section-number">3.2.1</span> Utilisation de la fonction <code>lmer()</code> du package <code>lme4</code></h3>
<p>Syntaxe : <code>lmer(response ~ fixed_effects + (random_intercept | grouping_factor_1) + (random_intercept | grouping_factor_2), data = data_frame, REML = TRUE )</code></p>
<p>Avec :</p>
<ul>
<li><p><code>response</code> = Variable dépendante numérique (ce que le modèle cherche à prédire).</p></li>
<li><p><code>fixed_effects</code> = Effets fixes, c’est-à-dire les variables explicatives dont on estime un coefficient unique pour l’ensemble de la population.</p>
<ul>
<li>on met 1 s’il n’y a pas de covariable (ici pas d’effet fixe = intercept seul)</li>
</ul></li>
<li><p><code>(random_intercept | grouping_factor_1)</code> = Effet aléatoire spécifiant un intercept propre à chaque niveau du facteur grouping_factor_1.</p>
<ul>
<li><p><code>grouping_factor_1</code> = variable sur laquelle on veut modéliser un effet aléatoire (par ex : patient, centre, etc.)</p></li>
<li><p><code>random_intercept</code> = indique qu’on modélise un intercept qui varie selon les niveaux de grouping_factor_1 (c’est à dire un coefficient qui soit différent pour chaque niveau de grouping_factor_1, donc pour chaque patient, centre, etc..)</p></li>
</ul></li>
<li><p><code>(random_intercept | grouping_factor_2)</code> = Deuxième effet aléatoire, indépendant du premier, avec un intercept variant selon grouping_factor_2.</p></li>
<li><p><code>data_frame</code> = Jeu de données contenant toutes les variables utilisées dans le modèle.</p></li>
<li><p><code>REML</code> = Argument logique indiquant si l’estimation doit utiliser REML (TRUE) ou ML (FALSE).</p>
<ul>
<li>Par défaut, REML = TRUE donc pas besoin de le spécifier</li>
</ul></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lme4)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>fitl <span class="ot">&lt;-</span> <span class="fu">lmer</span>(distance <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> id), <span class="at">data =</span> dental_long, <span class="at">REML =</span> <span class="cn">TRUE</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fitl)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: distance ~ 1 + (1 | id)
   Data: dental_long

REML criterion at convergence: 515.4

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-3.2400 -0.5277 -0.1073  0.4732  2.7687 

Random effects:
 Groups   Name        Variance Std.Dev.
 id       (Intercept) 3.752    1.937   
 Residual             4.930    2.220   
Number of obs: 108, groups:  id, 27

Fixed effects:
            Estimate Std. Error      df t value Pr(&gt;|t|)    
(Intercept)  24.0231     0.4297 26.0000   55.91   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<hr>
<p>Vraisemblance restreinte à l’estimation des paramètres : 515.4 (difficile à interpréter)</p>
<p>Information sur les résidus (Scaled residuals) : min, 1er quartile, médiane, 3ème quartile, max</p>
<p>Informations sur les effets aléatoires :</p>
<ul>
<li><p>Random effects :</p>
<ul>
<li><p>Nombre d’observations : 108</p></li>
<li><p>Nombre de groupes (patients) : 27</p></li>
<li><p>2 effets aléatoires pour lesquelles la variance est rapportée</p>
<ul>
<li><p>Residual : variance résiduelle (intra-cluster) = <span class="math inline">\(\sigma^2\)</span> = 4.930</p></li>
<li><p>id (Intercept) : variance de l’effet aléatoire = patient = <span class="math inline">\(\sigma^2_Z\)</span> = 3.752</p></li>
</ul></li>
</ul></li>
<li><p>Fixed effects :</p>
<ul>
<li><p>Moyenne estimée : 24.0231</p></li>
<li><p>Erreur standard de la moyenne estimée : 0.4297</p></li>
<li><p>Pas de p-value associée (pas de test statistique par défaut dans R pour les effets fixes dans les MLM)</p></li>
</ul></li>
</ul>
<p>Les deux variances estimées (résiduelle et effet aléatoire) permettent de quantifier la variabilité intra- et inter-cluster.</p>
<p>La variabilié résiduelle est du même ordre de grandeur que la variabilité inter-patients.</p>
<p>On a donc raison d’utiliser ce modèle pour estimer la moyenne car il y a une forte variabilité entre patients, quasiment du même ordre de grandeur que la variabilité résiduelle !</p>
</section>
<section id="utilisation-de-la-fonction-lme-du-package-nlme" class="level3" data-number="3.2.2">
<h3 data-number="3.2.2" class="anchored" data-anchor-id="utilisation-de-la-fonction-lme-du-package-nlme"><span class="header-section-number">3.2.2</span> Utilisation de la fonction <code>lme()</code> du package <code>nlme</code></h3>
<p>Syntaxe : <code>lme(fixed, data, random, correlation, weights, subset, method, na.action, control, contrasts, keep.data)</code></p>
<p>Ici : <code>fit2 &lt;- lme(fixed = distance ~ 1, data = dental_long, random = ~ 1 | id, method = "REML")</code></p>
<p>2 formules séparées :</p>
<ul>
<li><p>Une pour la moyenne : <code>distance ~ 1</code> (1 = pas d’effet fixe = on estime juste la moyenne globale)</p></li>
<li><p>Une pour les effets aléatoires : <code>random = ~ 1 | id</code> (effet aléatoire du patient sur l’intercept)</p></li>
</ul>
<p>Avec :</p>
<ul>
<li><p><code>fixed</code> = Formule des effets fixes : <code>response ~ covariables</code>.</p>
<ul>
<li>Exemple : <code>distance ~ age + sexe</code> pour estimer des effets moyens de l’âge et du sexe.</li>
</ul></li>
<li><p><code>data</code> = Jeu de données contenant toutes les variables du modèle.</p>
<ul>
<li>Exemple : <code>data = dental_long</code>.</li>
</ul></li>
<li><p><code>random</code> = Spécification des effets aléatoires.</p>
<ul>
<li><p>Exemple : <code>~ 1 | patient</code> pour un intercept aléatoire par patient.</p></li>
<li><p>Exemple : <code>~ age | patient</code> pour un intercept <strong>et</strong> une pente aléatoire selon l’âge.</p></li>
</ul></li>
<li><p><code>correlation</code> = Structure de corrélation intra-groupe (optionnelle).</p>
<p>Exemple : <code>corAR1(form = ~ time | patient)</code> pour une autocorrélation AR(1) dans le temps au sein de chaque patient.</p></li>
<li><p><code>weights</code> = Structure d’hétéroscédasticité (optionnelle).</p>
<ul>
<li>Exemple : <code>varIdent(form = ~ 1 | sexe)</code> pour autoriser une variance différente selon le sexe.</li>
</ul></li>
<li><p><code>subset</code> = Sous-ensemble des lignes utilisées.</p>
<ul>
<li>Exemple : <code>subset = age &gt; 10</code> pour ne garder que certains individus.</li>
</ul></li>
<li><p><code>method</code> =Méthode d’estimation : <code>"REML"</code> ou <code>"ML"</code>.</p>
<ul>
<li>Exemple : utiliser <code>"ML"</code> si l’on compare des modèles à effets fixes différents.</li>
</ul></li>
<li><p><code>na.action</code> = Comportement en présence de valeurs manquantes.</p>
<ul>
<li>Par défaut : <code>na.fail</code> (le modèle s’arrête si NAs).</li>
</ul></li>
<li><p><code>control</code> = Paramètres de contrôle de l’algorithme d’estimation.</p>
<ul>
<li>Exemple : <code>control = lmeControl(msMaxIter = 200)</code> pour augmenter le nombre d’itérations.</li>
</ul></li>
<li><p><code>contrasts</code> = Choix des contrastes pour les variables catégorielles.</p>
<ul>
<li>Exemple : définir des contrastes spécifiques pour un facteur.</li>
</ul></li>
<li><p><code>keep.data</code> = Indique si le jeu de données doit être conservé dans l’objet modèle. Utile pour réutiliser l’objet plus tard.</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>fit2 <span class="ot">&lt;-</span> <span class="fu">lme</span>(<span class="at">fixed =</span> distance <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> dental_long, <span class="at">random =</span> <span class="sc">~</span> <span class="dv">1</span> <span class="sc">|</span> id, <span class="at">method =</span> <span class="st">"REML"</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed-effects model fit by REML
  Data: dental_long 
       AIC      BIC    logLik
  521.3618 529.3803 -257.6809

Random effects:
 Formula: ~1 | id
        (Intercept) Residual
StdDev:    1.937002 2.220312

Fixed effects:  distance ~ 1 
               Value Std.Error DF  t-value p-value
(Intercept) 24.02315 0.4296606 81 55.91192       0

Standardized Within-Group Residuals:
       Min         Q1        Med         Q3        Max 
-3.2400448 -0.5277439 -0.1072888  0.4731815  2.7687301 

Number of Observations: 108
Number of Groups: 27 </code></pre>
</div>
</div>
<hr>
<p>Formula : donne des écarts-types (StdDev) pour l’effet aléatoire (Intercept) et pour les résidus (Residual) (et pas des variances comme avec lmer) (pour passer de l’un à l’autre, il faut faire variance = StdDev²)</p>
<ul>
<li><p>StdDev de l’effet aléatoire (Intercept) = 1.937002 <span class="math inline">\(\rightarrow\)</span> variance de l’effet aléatoire = 3.752 (même valeur que précédemment avec lmer)</p></li>
<li><p>StdDev des résidus (Residual) = 2.220312 <span class="math inline">\(\rightarrow\)</span> variance résiduelle = 4.930 (même valeur que précédemment avec lmer)</p></li>
</ul>
<p>Distance moyenne estimée = 24.02315 (même valeur que précédemment avec lmer).</p>
<p>Interprétation = la distance moyenne dentaire chez les enfants est estimée à environ 24.02 unités.</p>
</section>
<section id="exemple-3-lmertest-obtention-de-p-values-pour-les-effets-fixes" class="level3" data-number="3.2.3">
<h3 data-number="3.2.3" class="anchored" data-anchor-id="exemple-3-lmertest-obtention-de-p-values-pour-les-effets-fixes"><span class="header-section-number">3.2.3</span> Exemple 3 : ‘lmerTest’ : obtention de p-values pour les effets fixes</h3>
<p>Utilisation de la fonction <code>lmer()</code> du package <code>lmerTest</code> (extension de <code>lme4</code>)</p>
<p>Le fait d’importer la library <code>lmerTest</code> remplace automatiquement la fonction <code>lmer()</code> de <code>lme4</code> par celle de <code>lmerTest</code> qui fournit des p-values pour les effets fixes.</p>
<p>Syntaxe : <code>lmer(response ~ fixed_effects + (random_intercept | grouping_factor_1) + (random_intercept | grouping_factor_2), data = data_frame, REML = TRUE )</code></p>
<p>Ici : <code>fit3 &lt;- lmer(distance ~ time + (1 | id), data = dental_long, REML = TRUE)</code></p>
<p><strong>En gros, on veut estimer l’effet moyen de l’âge (time) sur la distance dentaire en prenant en compte la non-indépendance des mesures répétées chez un même enfant (id)</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmerTest)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>fit3 <span class="ot">&lt;-</span> <span class="fu">lmer</span>(distance <span class="sc">~</span> time <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> id), <span class="at">data =</span> dental_long, <span class="at">REML =</span> <span class="cn">TRUE</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit3)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: distance ~ time + (1 | id)
   Data: dental_long

REML criterion at convergence: 443.2

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-3.7376 -0.5248  0.0153  0.4027  3.7212 

Random effects:
 Groups   Name        Variance Std.Dev.
 id       (Intercept) 4.465    2.113   
 Residual             2.078    1.442   
Number of obs: 108, groups:  id, 27

Fixed effects:
            Estimate Std. Error      df t value Pr(&gt;|t|)    
(Intercept)  22.1852     0.4923 43.3911  45.066  &lt; 2e-16 ***
timey10       0.9815     0.3924 78.0000   2.501   0.0145 *  
timey12       2.4630     0.3924 78.0000   6.277 1.80e-08 ***
timey14       3.9074     0.3924 78.0000   9.958 1.52e-15 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
        (Intr) timy10 timy12
timey10 -0.399              
timey12 -0.399  0.500       
timey14 -0.399  0.500  0.500</code></pre>
</div>
</div>
<hr>
<ul>
<li><p>3 coefficients estimés : la variable <code>time</code>a été exprimée comme une variable catégorielle avec 4 modalités (8, 10, 12 et 14 ans) avec 8 ans comme catégorie de référence</p>
<ul>
<li><p><code>timey10</code> = différence moyenne estimée entre 10 ans et 8 ans = 0.9815 (p-value = 0.0145)</p></li>
<li><p><code>timey12</code> = différence moyenne estimée entre 12 ans et 8 ans = 2.4630 (p-value = 1.80e-08)</p></li>
<li><p><code>timey14</code> = différence moyenne estimée entre 14 ans et 8 ans = 3.9074 (p-value = 1.52e-15)</p></li>
</ul></li>
<li><p>La library <code>lmerTest</code> fournit des p-values <em>relativement</em> valides y compris avec une estimation REML (mais pas parfaite non plus).</p></li>
<li><p>Aussi !! La variance et l’écart-type ont ÉVOLUÉS : elles sont différentes de celles des modèles précédents car on a ajouté un effet fixe <code>time</code> dans le modèle.</p>
<ul>
<li><p>C’est comme si on avait “ignoré” la variabilité expliquée par l’âge dans les modèles précédents (sans <code>time</code>), donc la variabilité résiduelle diminue.</p></li>
<li><p>On a donc diminué la variabilité individuelle (résiduelle) en expliquant une partie de cette variabilité par l’âge.</p></li>
<li><p>On pourrait calculer un ICC en faisant :</p>
<ul>
<li><p>ICC = variance effet aléatoire / (variance effet aléatoire + variance résiduelle)</p></li>
<li><p>ICC = 4.465 / (4.465 + 2.078) = 0.682</p></li>
<li><p>Donc la variance expliquée par le patient compte à peu près pour 68.2% de la variance totale (après avoir ajusté pour l’âge)</p></li>
</ul></li>
<li><p>Avoir le minimum de variance résiduelle possible est important pour avoir des intervalles de confiance les plus précis possibles sur les effets fixes.</p></li>
</ul></li>
</ul>
</section>
<section id="pertinence-de-la-variable-time-globale-dans-le-modèle" class="level3" data-number="3.2.4">
<h3 data-number="3.2.4" class="anchored" data-anchor-id="pertinence-de-la-variable-time-globale-dans-le-modèle"><span class="header-section-number">3.2.4</span> Pertinence de la variable <code>time</code> globale dans le modèle</h3>
<p>On pourrait faire un rapport de vraisemblance entre :</p>
<ul>
<li><p>Modèle complet avec <code>time</code> : <code>fit3 &lt;- lmer(distance ~ time + (1 | id), data = dental_long, REML = TRUE)</code></p></li>
<li><p>Modèle sans <code>time</code> : <code>fitl &lt;- lmer(distance ~ 1 + (1 | id), data = dental_long, REML = TRUE)</code></p></li>
</ul>
<p>Le problème c’est qu’on a fitté les deux modèles avec REML (par défaut dans R) donc on ne peut pas faire de test de rapport de vraisemblance, parce que les vraisemblances restreintes ne sont pas comparables entre deux modèles avec des effets fixes différents.</p>
<p>On peut donc faire avec <code>anova()</code> qui utilise une approximation de Satterthwaite pour calculer une p-value globale pour la variable <code>time</code></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(fit3)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Type III Analysis of Variance Table with Satterthwaite's method
     Sum Sq Mean Sq NumDF DenDF F value    Pr(&gt;F)    
time 237.19  79.064     3    78   38.04 2.986e-15 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<ul>
<li>p-value globale pour la variable <code>time</code> &lt; 2.2e-16 <span class="math inline">\(\rightarrow\)</span> la variable <code>time</code> est globalement significative dans le modèle</li>
</ul>
<p>Il faut donc bien mettre un effet fixe <code>time</code> dans le modèle et il y a un effet significatif de l’âge sur la distance dentaire chez les enfants.</p>
</section>
<section id="pertinence-de-la-variable-sex-dans-le-modèle" class="level3" data-number="3.2.5">
<h3 data-number="3.2.5" class="anchored" data-anchor-id="pertinence-de-la-variable-sex-dans-le-modèle"><span class="header-section-number">3.2.5</span> Pertinence de la variable <code>sex</code> dans le modèle</h3>
<p><code>sex</code> est une variable binaire donc c’est différent!</p>
<p>On peut faire un test de Wald car on ne compare pas des vraisemblances restreintes entre deux modèles différents.</p>
</section>
</section>
</section>
<section id="applications-études-publiées" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Applications (études publiées)</h1>
<section id="déclin-cognitif-des-personnes-âgées-aux-états-unis-pendant-et-après-la-covid" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="déclin-cognitif-des-personnes-âgées-aux-états-unis-pendant-et-après-la-covid"><span class="header-section-number">4.1</span> Déclin cognitif des personnes âgées aux États-Unis pendant et après la Covid !!</h2>
<p><img src="images/paste-49.png" class="img-fluid"></p>
<p>= Déclin cognitif des personnes âgées aux États-Unis pendant et après la Covid</p>
<ul>
<li><p>Données longtitudinales</p></li>
<li><p>Patients de 50 ans ou plus</p></li>
<li><p>3 périodes d’observation :</p>
<ul>
<li><p>Avant 1ère vague (jusqu’au 29 février 2020)</p></li>
<li><p>Pendant 1ère vague (1er mars 2020 - 28 février 2021)</p></li>
<li><p>Seconde vague (1er mars 2021 - 28 février 2022)</p></li>
</ul></li>
<li><p><em>NB : si on avait eu 2 temps : avant et après la 1ère vague, on aurait pu faire une analyse en différences de différences, c’est à dire en faisant juste la différence pour chaque patient, qui permet de retrouver des mesures indépendantes</em></p></li>
<li><p>Ont utilisé un modèle linéaire mixte pour modéliser le déclin cognitif en fonction du temps (avant, pendant, après la 1ère vague)</p></li>
</ul>
</section>
<section id="analyse-statistique" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="analyse-statistique"><span class="header-section-number">4.2</span> Analyse statistique</h2>
<ul>
<li><p>Scores cognitifs assignés à trois périodes : pré-pandémie, année 1, année 2.</p></li>
<li><p>Modèle mixte linéaire :</p>
<ul>
<li><p>score cognition = à gauche comme outcome (quantitatif) = <span class="math inline">\(Y_{ij}\)</span></p></li>
<li><p>Effets aléatoires individuels patients ajoutés (variation propre à chaque participant) : <span class="math inline">\((1 | id)\)</span> = <span class="math inline">\(\gamma_1 Z_{ij}\)</span></p></li>
<li><p>Covariables : âge (continu), sexe — facteurs connus pour influencer la cognition : <span class="math inline">\(\beta X_{ij}\)</span></p></li>
<li><p>année pandémie = variable explicative = variable d’intérêt : catégorielle à 3 niveaux (avant, année 1, année 2) = effet fixe = <span class="math inline">\(\beta X_{ij}\)</span></p></li>
</ul></li>
<li><p>Modèle utilisé pour estimer les différences entre moyennes selon les années pandémie.</p></li>
<li><p>Analyses incluant les participants manquants à une ou deux périodes (tests t).</p></li>
<li><p>Packages utilisés : <code>lmer</code>, <code>emmeans</code>.</p></li>
<li><p>Résultats rapportés en Cohen’s d effect sizes + IC 95 % + p-values.</p>
<ul>
<li><p>Ils auraient pu rapporter des coefficients de régression (qui s’interprète comme une différence de moyenne dans un modèle linéaire)</p></li>
<li><p>Le problème : c’est que les scores cognitifs n’ont pas d’unité claire (ils sont composites) donc difficile d’interpréter une différence de moyenne en “unités de score cognitif”</p>
<ul>
<li>Par exemple : une différence de moyenne de -3 unités de score cognitif entre avant et année 1 : est-ce que c’est beaucoup ? peu ? comment savoir ?</li>
</ul></li>
<li><p>Effect size de Cohen = (moyenne groupe 1 - moyenne groupe 2) / écart-type pooled = coefficient rapporté à l’écart-type en population = pas d’unité</p></li>
<li><p>Objectif = <strong>ADIMENSIONNER</strong> le coefficient</p></li>
<li><p><strong>on met donc en rapport la différence de score avec la dispersion des scores entre les patients</strong></p></li>
</ul></li>
</ul>
<p>Si tu veux une version encore plus condensée ou orientée “méthodes stats”, je peux le faire.</p>
</section>
<section id="résultats" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="résultats"><span class="header-section-number">4.3</span> Résultats</h2>
<p><img src="images/paste-50.png" class="img-fluid"></p>
<ul>
<li><p>0,15 : déclin (devrait être un signe négatif en vrai)</p>
<ul>
<li><p>ne correspond pas à un nombre de points</p></li>
<li><p>correspond à “0,15 écarts-types en dessous à l’année 1 par rapport à l’année 0”</p></li>
</ul></li>
</ul>
</section>
</section>
<section id="modèles-linéaires-mixtes-extension" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Modèles linéaires mixtes : extension</h1>
<section id="modèles-non-linéaires-mixtes-nlmm" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="modèles-non-linéaires-mixtes-nlmm"><span class="header-section-number">5.1</span> Modèles non linéaires mixtes (NLMM)</h2>
<p><img src="images/paste-51.png" class="img-fluid"></p>
<p>Exemple : évolution d’un biomarqueur</p>
<ul>
<li><p>Modèle non linéaire (exponentiel, logistique, etc.)</p></li>
<li><p>Incorporation d’effets aléatoires (patient, centre, etc.)</p></li>
<li><p>Estimation des paramètres fixes et des composantes de la variance</p></li>
</ul>
<p>Différence avec un modèle linéaire mixte : la relation entre la variable dépendante et les covariables n’est pas linéaire.</p>
<p>Donc ça ne s’interpète pas comme une différence de moyenne mais comme un paramètre de croissance, une constante de temps, etc.</p>
</section>
<section id="modèles-linéaires-généralisées-mixtes-glmm" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="modèles-linéaires-généralisées-mixtes-glmm"><span class="header-section-number">5.2</span> Modèles linéaires généralisées mixtes (GLMM)</h2>
<p><img src="images/paste-52.png" class="img-fluid"></p>
<p>Exemple : logistique mixte</p>
<ul>
<li><p>Variable dépendante binaire (oui/non)</p></li>
<li><p>Incorporation d’effets aléatoires (patient, centre, etc.)</p></li>
<li><p>Estimation des paramètres fixes (odds ratios) et des composantes de la variance</p></li>
</ul>
<p>Différence avec un modèle linéaire mixte : la variable dépendante n’est pas quantitative et suit une loi de probabilité d’une famille exponentielle (binomiale, Poisson, etc.)</p>
<p>Donc ça ne s’interpète pas comme une différence de moyenne mais comme un odds ratio, un risque relatif, etc.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>