<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Thomas Husson, Groupe 52">

<title>Devoir Statistiques Avancées</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="devoir_stats_avancees_files/libs/clipboard/clipboard.min.js"></script>
<script src="devoir_stats_avancees_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="devoir_stats_avancees_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="devoir_stats_avancees_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="devoir_stats_avancees_files/libs/quarto-html/popper.min.js"></script>
<script src="devoir_stats_avancees_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="devoir_stats_avancees_files/libs/quarto-html/anchor.min.js"></script>
<link href="devoir_stats_avancees_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="devoir_stats_avancees_files/libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="devoir_stats_avancees_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="devoir_stats_avancees_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="devoir_stats_avancees_files/libs/bootstrap/bootstrap-55aa396ea3e988129bcec43acf404917.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#énoncé-et-présentation-des-échelles" id="toc-énoncé-et-présentation-des-échelles" class="nav-link active" data-scroll-target="#énoncé-et-présentation-des-échelles"><span class="header-section-number">1</span> Énoncé et présentation des échelles</a>
  <ul>
  <li><a href="#énoncé-du-devoir" id="toc-énoncé-du-devoir" class="nav-link" data-scroll-target="#énoncé-du-devoir"><span class="header-section-number">1.1</span> Énoncé du devoir</a></li>
  <li><a href="#échelles" id="toc-échelles" class="nav-link" data-scroll-target="#échelles"><span class="header-section-number">1.2</span> Échelles</a></li>
  </ul></li>
  <li><a href="#gestion-des-données" id="toc-gestion-des-données" class="nav-link" data-scroll-target="#gestion-des-données"><span class="header-section-number">2</span> Gestion des données</a>
  <ul>
  <li><a href="#présentation-des-fichiers-de-données" id="toc-présentation-des-fichiers-de-données" class="nav-link" data-scroll-target="#présentation-des-fichiers-de-données"><span class="header-section-number">2.1</span> Présentation des fichiers de données</a>
  <ul>
  <li><a href="#fichier-hamilton" id="toc-fichier-hamilton" class="nav-link" data-scroll-target="#fichier-hamilton"><span class="header-section-number">2.1.1</span> Fichier Hamilton</a></li>
  <li><a href="#fichier-scl90" id="toc-fichier-scl90" class="nav-link" data-scroll-target="#fichier-scl90"><span class="header-section-number">2.1.2</span> Fichier scl90</a></li>
  <li><a href="#fichier-groupe" id="toc-fichier-groupe" class="nav-link" data-scroll-target="#fichier-groupe"><span class="header-section-number">2.1.3</span> Fichier groupe</a></li>
  </ul></li>
  <li><a href="#import-des-données-et-data-management" id="toc-import-des-données-et-data-management" class="nav-link" data-scroll-target="#import-des-données-et-data-management"><span class="header-section-number">2.2</span> Import des données et data management</a>
  <ul>
  <li><a href="#scl90" id="toc-scl90" class="nav-link" data-scroll-target="#scl90"><span class="header-section-number">2.2.1</span> SCL90</a></li>
  <li><a href="#hdrs" id="toc-hdrs" class="nav-link" data-scroll-target="#hdrs"><span class="header-section-number">2.2.2</span> HDRS</a></li>
  <li><a href="#groupes" id="toc-groupes" class="nav-link" data-scroll-target="#groupes"><span class="header-section-number">2.2.3</span> Groupes</a></li>
  <li><a href="#fusion-des-3-fichiers" id="toc-fusion-des-3-fichiers" class="nav-link" data-scroll-target="#fusion-des-3-fichiers"><span class="header-section-number">2.2.4</span> Fusion des 3 fichiers</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#question-1-validation-de-léchelle-hamilton" id="toc-question-1-validation-de-léchelle-hamilton" class="nav-link" data-scroll-target="#question-1-validation-de-léchelle-hamilton"><span class="header-section-number">3</span> Question 1 : Validation de l’échelle Hamilton</a>
  <ul>
  <li><a href="#valdidation.à-j0" id="toc-valdidation.à-j0" class="nav-link" data-scroll-target="#valdidation.à-j0"><span class="header-section-number">3.1</span> Valdidation.à J0</a>
  <ul>
  <li><a href="#description" id="toc-description" class="nav-link" data-scroll-target="#description"><span class="header-section-number">3.1.1</span> Description</a></li>
  <li><a href="#validité-interne-structure-dimensionnelle-analyse-factorielle" id="toc-validité-interne-structure-dimensionnelle-analyse-factorielle" class="nav-link" data-scroll-target="#validité-interne-structure-dimensionnelle-analyse-factorielle"><span class="header-section-number">3.1.2</span> Validité interne : structure dimensionnelle, analyse factorielle</a>
  <ul class="collapse">
  <li><a href="#exploration-de-la-structure-dimensionnelle-analyse-en-composantes-principales" id="toc-exploration-de-la-structure-dimensionnelle-analyse-en-composantes-principales" class="nav-link" data-scroll-target="#exploration-de-la-structure-dimensionnelle-analyse-en-composantes-principales"><span class="header-section-number">3.1.2.1</span> Exploration de la structure dimensionnelle : analyse en composantes principales</a></li>
  <li><a href="#exploration-de-la-structure-dimensionnelle-analyse-factorielle" id="toc-exploration-de-la-structure-dimensionnelle-analyse-factorielle" class="nav-link" data-scroll-target="#exploration-de-la-structure-dimensionnelle-analyse-factorielle"><span class="header-section-number">3.1.2.2</span> Exploration de la structure dimensionnelle : analyse factorielle</a></li>
  </ul></li>
  <li><a href="#fiabilité-interne-que-vaut-la-mesure" id="toc-fiabilité-interne-que-vaut-la-mesure" class="nav-link" data-scroll-target="#fiabilité-interne-que-vaut-la-mesure"><span class="header-section-number">3.1.3</span> Fiabilité interne = que vaut la mesure ?</a>
  <ul class="collapse">
  <li><a href="#consistance-interne-alpha-de-cronbach" id="toc-consistance-interne-alpha-de-cronbach" class="nav-link" data-scroll-target="#consistance-interne-alpha-de-cronbach"><span class="header-section-number">3.1.3.1</span> Consistance interne : alpha de Cronbach</a></li>
  </ul></li>
  <li><a href="#validité-externe-linstrument-mesure-t-il-ce-quil-est-censé-mesurer" id="toc-validité-externe-linstrument-mesure-t-il-ce-quil-est-censé-mesurer" class="nav-link" data-scroll-target="#validité-externe-linstrument-mesure-t-il-ce-quil-est-censé-mesurer"><span class="header-section-number">3.1.4</span> Validité externe = l’instrument mesure-t-il ce qu’il est censé mesurer ?</a>
  <ul class="collapse">
  <li><a href="#corrélation-entre-le-score-de-hamilton-et-les-dimensions-du-scl-90-à-j0" id="toc-corrélation-entre-le-score-de-hamilton-et-les-dimensions-du-scl-90-à-j0" class="nav-link" data-scroll-target="#corrélation-entre-le-score-de-hamilton-et-les-dimensions-du-scl-90-à-j0"><span class="header-section-number">3.1.4.1</span> Corrélation entre le score de Hamilton et les dimensions du SCL-90 à J0</a></li>
  <li><a href="#conclusion-validité-externe-à-j0" id="toc-conclusion-validité-externe-à-j0" class="nav-link" data-scroll-target="#conclusion-validité-externe-à-j0"><span class="header-section-number">3.1.4.2</span> Conclusion validité externe à J0</a></li>
  </ul></li>
  <li><a href="#conclusion-globale-à-j0" id="toc-conclusion-globale-à-j0" class="nav-link" data-scroll-target="#conclusion-globale-à-j0"><span class="header-section-number">3.1.5</span> Conclusion globale à J0</a></li>
  </ul></li>
  <li><a href="#validation-à-j56" id="toc-validation-à-j56" class="nav-link" data-scroll-target="#validation-à-j56"><span class="header-section-number">3.2</span> Validation à J56</a>
  <ul>
  <li><a href="#description-1" id="toc-description-1" class="nav-link" data-scroll-target="#description-1"><span class="header-section-number">3.2.1</span> Description</a></li>
  <li><a href="#validité-interne-structure-dimensionnelle-analyse-factorielle-1" id="toc-validité-interne-structure-dimensionnelle-analyse-factorielle-1" class="nav-link" data-scroll-target="#validité-interne-structure-dimensionnelle-analyse-factorielle-1"><span class="header-section-number">3.2.2</span> Validité interne : structure dimensionnelle, analyse factorielle</a>
  <ul class="collapse">
  <li><a href="#exploration-de-la-structure-dimensionnelle-analyse-en-composantes-principales-1" id="toc-exploration-de-la-structure-dimensionnelle-analyse-en-composantes-principales-1" class="nav-link" data-scroll-target="#exploration-de-la-structure-dimensionnelle-analyse-en-composantes-principales-1"><span class="header-section-number">3.2.2.1</span> Exploration de la structure dimensionnelle : analyse en composantes principales</a></li>
  <li><a href="#exploration-de-la-structure-dimensionnelle-analyse-factorielle-1" id="toc-exploration-de-la-structure-dimensionnelle-analyse-factorielle-1" class="nav-link" data-scroll-target="#exploration-de-la-structure-dimensionnelle-analyse-factorielle-1"><span class="header-section-number">3.2.2.2</span> Exploration de la structure dimensionnelle : analyse factorielle</a></li>
  </ul></li>
  <li><a href="#fiabilité-interne-que-vaut-la-mesure-1" id="toc-fiabilité-interne-que-vaut-la-mesure-1" class="nav-link" data-scroll-target="#fiabilité-interne-que-vaut-la-mesure-1"><span class="header-section-number">3.2.3</span> Fiabilité interne = que vaut la mesure ?</a>
  <ul class="collapse">
  <li><a href="#consistance-interne-alpha-de-cronbach-1" id="toc-consistance-interne-alpha-de-cronbach-1" class="nav-link" data-scroll-target="#consistance-interne-alpha-de-cronbach-1"><span class="header-section-number">3.2.3.1</span> Consistance interne : alpha de Cronbach</a></li>
  </ul></li>
  <li><a href="#validité-externe-linstrument-mesure-t-il-ce-quil-est-censé-mesurer-1" id="toc-validité-externe-linstrument-mesure-t-il-ce-quil-est-censé-mesurer-1" class="nav-link" data-scroll-target="#validité-externe-linstrument-mesure-t-il-ce-quil-est-censé-mesurer-1"><span class="header-section-number">3.2.4</span> Validité externe = l’instrument mesure-t-il ce qu’il est censé mesurer ?</a>
  <ul class="collapse">
  <li><a href="#corrélation-entre-le-score-de-hamilton-et-les-dimensions-du-scl-90-à-j56" id="toc-corrélation-entre-le-score-de-hamilton-et-les-dimensions-du-scl-90-à-j56" class="nav-link" data-scroll-target="#corrélation-entre-le-score-de-hamilton-et-les-dimensions-du-scl-90-à-j56"><span class="header-section-number">3.2.4.1</span> Corrélation entre le score de Hamilton et les dimensions du SCL-90 à J56</a></li>
  <li><a href="#conclusion-validité-externe-à-j56" id="toc-conclusion-validité-externe-à-j56" class="nav-link" data-scroll-target="#conclusion-validité-externe-à-j56"><span class="header-section-number">3.2.4.2</span> Conclusion validité externe à J56</a></li>
  </ul></li>
  <li><a href="#conclusion-globale-à-j56" id="toc-conclusion-globale-à-j56" class="nav-link" data-scroll-target="#conclusion-globale-à-j56"><span class="header-section-number">3.2.5</span> Conclusion globale à J56</a></li>
  <li><a href="#synthèse-des-résultats-de-validation-de-léchelle-de-hamilton-à-j0-et-j56" id="toc-synthèse-des-résultats-de-validation-de-léchelle-de-hamilton-à-j0-et-j56" class="nav-link" data-scroll-target="#synthèse-des-résultats-de-validation-de-léchelle-de-hamilton-à-j0-et-j56"><span class="header-section-number">3.2.6</span> Synthèse des résultats de validation de l’échelle de Hamilton à J0 et J56</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#question-2-comparaison-de-la-réponse-au-traitement-entre-deux-groupes-de-patients" id="toc-question-2-comparaison-de-la-réponse-au-traitement-entre-deux-groupes-de-patients" class="nav-link" data-scroll-target="#question-2-comparaison-de-la-réponse-au-traitement-entre-deux-groupes-de-patients"><span class="header-section-number">4</span> Question 2 : Comparaison de la réponse au traitement entre deux groupes de patients</a>
  <ul>
  <li><a href="#gestion-des-données-1" id="toc-gestion-des-données-1" class="nav-link" data-scroll-target="#gestion-des-données-1"><span class="header-section-number">4.1</span> Gestion des données</a></li>
  <li><a href="#scores-bruts-à-j0-dans-chaque-groupe" id="toc-scores-bruts-à-j0-dans-chaque-groupe" class="nav-link" data-scroll-target="#scores-bruts-à-j0-dans-chaque-groupe"><span class="header-section-number">4.2</span> Scores bruts à J0 dans chaque groupe</a>
  <ul>
  <li><a href="#comparaison-des-scores-bruts-à-j0-entre-les-deux-groupes" id="toc-comparaison-des-scores-bruts-à-j0-entre-les-deux-groupes" class="nav-link" data-scroll-target="#comparaison-des-scores-bruts-à-j0-entre-les-deux-groupes"><span class="header-section-number">4.2.1</span> Comparaison des scores bruts à J0 entre les deux groupes</a></li>
  </ul></li>
  <li><a href="#évolution-des-scores-bruts-entre-j0-et-j56-dans-chaque-groupe" id="toc-évolution-des-scores-bruts-entre-j0-et-j56-dans-chaque-groupe" class="nav-link" data-scroll-target="#évolution-des-scores-bruts-entre-j0-et-j56-dans-chaque-groupe"><span class="header-section-number">4.3</span> Évolution des scores bruts entre J0 et J56 dans chaque groupe</a>
  <ul>
  <li><a href="#évolution-du-nombre-de-patients-dans-chaque-groupe-à-chaque-visite" id="toc-évolution-du-nombre-de-patients-dans-chaque-groupe-à-chaque-visite" class="nav-link" data-scroll-target="#évolution-du-nombre-de-patients-dans-chaque-groupe-à-chaque-visite"><span class="header-section-number">4.3.1</span> Évolution du nombre de patients dans chaque groupe à chaque visite</a></li>
  <li><a href="#évolution-des-scores-bruts-moyens-entre-j0-et-j56-dans-chaque-groupe" id="toc-évolution-des-scores-bruts-moyens-entre-j0-et-j56-dans-chaque-groupe" class="nav-link" data-scroll-target="#évolution-des-scores-bruts-moyens-entre-j0-et-j56-dans-chaque-groupe"><span class="header-section-number">4.3.2</span> Évolution des scores bruts moyens entre J0 et J56 dans chaque groupe</a></li>
  </ul></li>
  <li><a href="#comparaison-de-la-réponse-au-traitement-entre-deux-groupes-de-patients" id="toc-comparaison-de-la-réponse-au-traitement-entre-deux-groupes-de-patients" class="nav-link" data-scroll-target="#comparaison-de-la-réponse-au-traitement-entre-deux-groupes-de-patients"><span class="header-section-number">4.4</span> Comparaison de la réponse au traitement entre deux groupes de patients</a>
  <ul>
  <li><a href="#compraison-de-la-réponse-en-utilisant-la-méthode-locf" id="toc-compraison-de-la-réponse-en-utilisant-la-méthode-locf" class="nav-link" data-scroll-target="#compraison-de-la-réponse-en-utilisant-la-méthode-locf"><span class="header-section-number">4.4.1</span> Compraison de la réponse en utilisant la méthode LOCF</a>
  <ul class="collapse">
  <li><a href="#imputation-des-données-manquantes-par-la-méthode-locf-last-observation-carried-forward" id="toc-imputation-des-données-manquantes-par-la-méthode-locf-last-observation-carried-forward" class="nav-link" data-scroll-target="#imputation-des-données-manquantes-par-la-méthode-locf-last-observation-carried-forward"><span class="header-section-number">4.4.1.1</span> Imputation des données manquantes par la méthode LOCF (last observation carried forward)</a></li>
  <li><a href="#comparaison-de-la-réponse-au-traitement-entre-les-deux-groupes-après-imputation-locf" id="toc-comparaison-de-la-réponse-au-traitement-entre-les-deux-groupes-après-imputation-locf" class="nav-link" data-scroll-target="#comparaison-de-la-réponse-au-traitement-entre-les-deux-groupes-après-imputation-locf"><span class="header-section-number">4.4.1.2</span> Comparaison de la réponse au traitement entre les deux groupes après imputation LOCF</a></li>
  </ul></li>
  <li><a href="#comparaison-de-la-réponse-en-utilisant-un-modèle-mixte" id="toc-comparaison-de-la-réponse-en-utilisant-un-modèle-mixte" class="nav-link" data-scroll-target="#comparaison-de-la-réponse-en-utilisant-un-modèle-mixte"><span class="header-section-number">4.4.2</span> Comparaison de la réponse en utilisant un modèle mixte</a>
  <ul class="collapse">
  <li><a href="#modèle-mixte-sans-interaction" id="toc-modèle-mixte-sans-interaction" class="nav-link" data-scroll-target="#modèle-mixte-sans-interaction"><span class="header-section-number">4.4.2.1</span> Modèle mixte sans interaction</a>
  <ul class="collapse">
  <li><a href="#modèle-mixte-sans-interaction-avec-visit-comme-facteur-et-j0-comme-référence" id="toc-modèle-mixte-sans-interaction-avec-visit-comme-facteur-et-j0-comme-référence" class="nav-link" data-scroll-target="#modèle-mixte-sans-interaction-avec-visit-comme-facteur-et-j0-comme-référence"><span class="header-section-number">4.4.2.1.1</span> Modèle mixte sans interaction avec <code>VISIT</code> comme facteur et J0 comme référence</a></li>
  <li><a href="#modèle-mixte-sans-interaction-avec-visit-comme-variable-continue" id="toc-modèle-mixte-sans-interaction-avec-visit-comme-variable-continue" class="nav-link" data-scroll-target="#modèle-mixte-sans-interaction-avec-visit-comme-variable-continue"><span class="header-section-number">4.4.2.1.2</span> Modèle mixte sans interaction avec <code>VISIT</code> comme variable continue</a></li>
  </ul></li>
  <li><a href="#modèle-mixte-avec-interaction" id="toc-modèle-mixte-avec-interaction" class="nav-link" data-scroll-target="#modèle-mixte-avec-interaction"><span class="header-section-number">4.4.2.2</span> Modèle mixte avec interaction</a>
  <ul class="collapse">
  <li><a href="#modèle-mixte-avec-interaction-avec-visit-comme-facteur-et-j0-comme-référence" id="toc-modèle-mixte-avec-interaction-avec-visit-comme-facteur-et-j0-comme-référence" class="nav-link" data-scroll-target="#modèle-mixte-avec-interaction-avec-visit-comme-facteur-et-j0-comme-référence"><span class="header-section-number">4.4.2.2.1</span> Modèle mixte avec interaction avec <code>VISIT</code> comme facteur et J0 comme référence</a></li>
  <li><a href="#modèle-mixte-avec-interaction-avec-visit-comme-variable-continue" id="toc-modèle-mixte-avec-interaction-avec-visit-comme-variable-continue" class="nav-link" data-scroll-target="#modèle-mixte-avec-interaction-avec-visit-comme-variable-continue"><span class="header-section-number">4.4.2.2.2</span> Modèle mixte avec interaction avec <code>VISIT</code> comme variable continue</a></li>
  <li><a href="#test-de-leffet-dinteraction-par-rapport-au-modèle-sans-interaction" id="toc-test-de-leffet-dinteraction-par-rapport-au-modèle-sans-interaction" class="nav-link" data-scroll-target="#test-de-leffet-dinteraction-par-rapport-au-modèle-sans-interaction"><span class="header-section-number">4.4.2.2.3</span> Test de l’effet d’interaction par rapport au modèle sans interaction</a></li>
  </ul></li>
  </ul></li>
  </ul></li>
  </ul></li>
  <li><a href="#annexe-code-r" id="toc-annexe-code-r" class="nav-link" data-scroll-target="#annexe-code-r"><span class="header-section-number">5</span> Annexe – Code R</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="devoir_stats_avancees.docx"><i class="bi bi-file-word"></i>MS Word</a></li><li><a href="devoir_stats_avancees.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Devoir Statistiques Avancées</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Thomas Husson, Groupe 52 </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<div style="page-break-after: always;"></div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Utilisation de l’IA</strong></p>
<p>Des LLMs ont été utilisés à plusieurs reprises dans ce devoir, pour deux tâches principales :</p>
<ul>
<li><p>En cas de problème d’éxécution du code R (pour suggérer correction et amélioration)</p></li>
<li><p>Pour amélioration du rendu depuis un fichier Quarto Markdown vers PDF. Notamment certaines fonctions dont l’output R n’est pas compatible avec le rendu pdf (par exemple, <code>factanal()</code> pour l’analyse factorielle ou le rendu des tableaux automatisé des coefficients alpha de Cronbach et leur IC)</p></li>
</ul>
<p>Utilisation de Gemini pour le rendu Quarto et Github Copilot pour le code R.</p>
</div>
</div>
<div style="page-break-after: always;"></div>
<section id="énoncé-et-présentation-des-échelles" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Énoncé et présentation des échelles</h1>
<section id="énoncé-du-devoir" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="énoncé-du-devoir"><span class="header-section-number">1.1</span> Énoncé du devoir</h2>
<p>Consigne :</p>
<ul>
<li><p>Étude d’épidémiologie clinique avec mesures répétées</p></li>
<li><p>Données :</p>
<ul>
<li><p>146 patients déprimés</p></li>
<li><p>Évaluations à J0, J4, J7, J14, J21, J28, J42, J56</p></li>
<li><p>Autoévaluation (SCL90) et hétéroévaluation (échelle de dépression de Hamilton)</p></li>
</ul></li>
<li><p>Questions :</p>
<ol type="1">
<li><p>Validation de l’échelle de dépression de Hamilton aux temps J0 et J56</p></li>
<li><p>Comparaison de la réponse au traitement entre deux groupes de patients (groupe=0 et groupe=1) en utilisant le score brut de Hamilton avec une approche LOCF puis un modèle mixte</p></li>
<li><p>Réponse à la question 2 en utilisant un critère binaire censuré « réponse au traitement » défini par une chute de 50% à l’échelle de Hamilton par rapport à J0</p></li>
</ol></li>
<li><p>Fichiers :</p>
<ul>
<li><p>Fichier groupe (<code>outil groupe.xlsx</code>) (2 sous-groupes de patients)</p></li>
<li><p>Fichier autoévaluation (<code>outil autoeval.xlsx</code>) (SCL 90)</p></li>
<li><p>Fichier hdrs (<code>outil hdrs.xlsx</code>) (échelle de Hamilton)</p></li>
</ul></li>
</ul>
</section>
<section id="échelles" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="échelles"><span class="header-section-number">1.2</span> Échelles</h2>
<p>Table 1: Présentation des échelles utilisées dans le devoir</p>
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 45%">
<col style="width: 45%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Échelle de Hamilton (HDRS)</th>
<th>Échelle SCL90</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Objectif</td>
<td>Mesure l’intensité de la symptomatologie dépressive</td>
<td>“Inconfort psychopathologique” selon plusieurs dimensions.</td>
</tr>
<tr class="even">
<td>Type</td>
<td>Hétéro-évaluation</td>
<td>Autoévaluation</td>
</tr>
<tr class="odd">
<td>Méthode</td>
<td>17 items codés de 2 à 4<br><br>- Score ≤ 7 : pas de dépression clinique<br>- Score 8–15 : dépression mineure<br>- Score &gt; 15 : dépression majeure</td>
<td>10 dimensions : somatisation, symptômes obsessionnels, sensibilité interpersonnelle, dépression, anxiété, hostilité, phobies, traits paranoïaques, traits psychotiques et symptômes divers.</td>
</tr>
</tbody>
</table>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="gestion-des-données" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Gestion des données</h1>
<section id="présentation-des-fichiers-de-données" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="présentation-des-fichiers-de-données"><span class="header-section-number">2.1</span> Présentation des fichiers de données</h2>
<p>Les 3 fichiers sont en format “large” : chaque ligne correspond à une visite d’un patient et une colonne par item de l’échelle (sauf l’item 16 = PERTE DE POIDS qui est codé en deux variables HAMD16A et HAMD16B dans l’échelle de Hamilton, selon que la perte de poids est déclarée par le patient ou appréciée par le médecin)</p>
<p>On créera donc une colonne <code>hdrs$HAMD16</code> qui prendra la valeur de <code>hdrs$HAMD16A</code> si elle est remplie, sinon la valeur de <code>hdrs$HAMD16B</code>.</p>
<section id="fichier-hamilton" class="level3" data-number="2.1.1">
<h3 data-number="2.1.1" class="anchored" data-anchor-id="fichier-hamilton"><span class="header-section-number">2.1.1</span> Fichier Hamilton</h3>
<ul>
<li><p>1053 observations, 20 variables pour 146 patients</p></li>
<li><p>On ajoute une colonne <code>score</code> qui contient le score total de l’échelle de Hamilton (somme des items)</p></li>
<li><p>Les données d’une ligne (J7 du 128ème patient) sont manquantes <span class="math inline">\(\rightarrow\)</span> on supprime cette ligne.</p></li>
</ul>
</section>
<section id="fichier-scl90" class="level3" data-number="2.1.2">
<h3 data-number="2.1.2" class="anchored" data-anchor-id="fichier-scl90"><span class="header-section-number">2.1.2</span> Fichier scl90</h3>
<ul>
<li><p>1034 observations, 92 variables, 146 patients.</p></li>
<li><p>On crée 10 nouvelles variables représentant les scores moyen des 10 dimensions de l’échelle SCL90.</p></li>
<li><p>Données aberrantes parfois, qui sont recodées en données manquantes et représentent ainsi 0.6% des données totales.</p></li>
</ul>
</section>
<section id="fichier-groupe" class="level3" data-number="2.1.3">
<h3 data-number="2.1.3" class="anchored" data-anchor-id="fichier-groupe"><span class="header-section-number">2.1.3</span> Fichier groupe</h3>
<ul>
<li><p>Répartit les 146 patients en 2 groupes (1 et 0)</p></li>
<li><p>Pas de NA</p></li>
</ul>
</section>
</section>
<section id="import-des-données-et-data-management" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="import-des-données-et-data-management"><span class="header-section-number">2.2</span> Import des données et data management</h2>
<p>Les données sont importées à partir de fichiers Excel.</p>
<section id="scl90" class="level3" data-number="2.2.1">
<h3 data-number="2.2.1" class="anchored" data-anchor-id="scl90"><span class="header-section-number">2.2.1</span> SCL90</h3>
<p>Le jeu de données <code>scl90</code> est traité de la manière suivante :</p>
<ul>
<li><p>Visites ordonnées chronologiquement</p></li>
<li><p>Identification des doublons</p></li>
<li><p>Visualisation et gestion des données aberrantes</p></li>
<li><p>Imputation des données manquantes par le mode pour chaque question</p></li>
<li><p>Création des scores moyens par dimension (10 dimensions)</p></li>
<li><p>Nouveau dataframe <code>scl90_dim</code> avec uniquement les 10 dimensions</p></li>
</ul>
</section>
<section id="hdrs" class="level3" data-number="2.2.2">
<h3 data-number="2.2.2" class="anchored" data-anchor-id="hdrs"><span class="header-section-number">2.2.2</span> HDRS</h3>
<p>Le jeu de données <code>hdrs</code> est traité de la manière suivante :</p>
<ul>
<li><p>Visites ordonnées chronologiquement</p></li>
<li><p>Identification des doublons</p></li>
<li><p>Fusion des variables HAMD16A et HAMD16B en une seule variable HAMD16</p></li>
<li><p>Création du score total HDRS (ajouté dans la colonne <code>hdrs$score</code>)</p></li>
</ul>
</section>
<section id="groupes" class="level3" data-number="2.2.3">
<h3 data-number="2.2.3" class="anchored" data-anchor-id="groupes"><span class="header-section-number">2.2.3</span> Groupes</h3>
</section>
<section id="fusion-des-3-fichiers" class="level3" data-number="2.2.4">
<h3 data-number="2.2.4" class="anchored" data-anchor-id="fusion-des-3-fichiers"><span class="header-section-number">2.2.4</span> Fusion des 3 fichiers</h3>
<p>Convertir <code>hdrs_groupe</code>, <code>scl90_groupe</code> et <code>df_total_wide</code> de format “large” à format “long”</p>
<div style="page-break-after: always;"></div>
</section>
</section>
</section>
<section id="question-1-validation-de-léchelle-hamilton" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Question 1 : Validation de l’échelle Hamilton</h1>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Consigne de la question 1</strong> : Lorsque l’on utilise un instrument de mesure subjective dans une étude clinique, il est toujours bon de le (re)valider rapidement. Procédez ici à cette <strong>vérification</strong> sur l’échelle de dépression de Hamilton, aux temps J0 et J56.</p>
</div>
</div>
<ul>
<li><p>Vérification d’une échelle de mesure subjective = 1/ Que mesure l’instrument ? 2/ Que vaut la mesure ?</p></li>
<li><p>Premier temps : Évaluation préliminaire des réponses aux items, puis chercher une corrélation entre eux par une matrice de corrélation 2 à 2</p></li>
<li><p>Second temps : Analyse de la structure dimensionnelle = <strong>que mesure l’instrument ?</strong></p>
<ul>
<li><p>Exploration de la structure par analyse en composante principale : visualiser les relations entre les items</p></li>
<li><p>Détermination du nombre de dimensions : diagramme des valeurs propres (<em>scree plot</em>) permet de déterminer le nombre de dimensions (composantes principales)</p></li>
<li><p>Si structure dimensionnelle identifiée : <strong>analyse factorielle</strong> permet de déterminer quels items se regroupent dans chaque dimension</p></li>
</ul></li>
<li><p>Troisième temps : Évaluation de la fiabilité interne = <strong>que vaut la mesure ?</strong></p>
<ul>
<li>La consistance interne des items (évalue si les items sont cohérents entre eux) sera évaluée par le calcul de l’alpha de Cronbach, calculé sur l’échelle totale et sur chaque dimension identifiée précédemment.</li>
</ul></li>
<li><p>Quatrième temps : Évaluation de la validité = <strong>l’instrument mesure-t-il ce qu’il est censé mesurer ?</strong> (similaire à la question “que mesure l’instrument ?”)</p>
<ul>
<li><p>Validité interne : déjà évaluée au cours du second temps (structure dimensionnelle)</p></li>
<li><p>Validité externe : corrélation avec d’autres instruments de mesure (ici les dimensions de l’échelle SCL90)</p></li>
</ul></li>
</ul>
<section id="valdidation.à-j0" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="valdidation.à-j0"><span class="header-section-number">3.1</span> Valdidation.à J0</h2>
<section id="description" class="level3" data-number="3.1.1">
<h3 data-number="3.1.1" class="anchored" data-anchor-id="description"><span class="header-section-number">3.1.1</span> Description</h3>
<p>Les réponses sont représentées :</p>
<ul>
<li><p>par des histogrammes pour chaque item de l’échelle de Hamilton à J0</p></li>
<li><p>par une matrice de corrélation 2 à 2 entre les items</p></li>
</ul>
<p>NB : le code R utilise une fonction pour faciliter la création des histogrammes pour chaque item.</p>
<p>La fonction crée un histogramme pour chaque item listés dans un vecteur crée précédemment (<code>hdrs_items</code>).</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="devoir_stats_avancees_files/figure-html/histo%20items%20J0-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Histogrammes des scores des items de l’échelle de Hamilton à J0</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="devoir_stats_avancees_files/figure-html/histo%20items%20J0-2.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Histogrammes des scores des items de l’échelle de Hamilton à J0</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="devoir_stats_avancees_files/figure-html/matrice%20corrélation%20J0-1.png" class="img-fluid figure-img" width="480"></p>
<figcaption>Matrice de corrélation entre les items de l’échelle de Hamilton à J0</figcaption>
</figure>
</div>
</div>
</div>
<ul>
<li><p>Il n’y a pas de données manquantes.</p></li>
<li><p>Les histogrammes montrent que certains items ont une distribution asymétrique (ex : insomnie quelque soit le moment de la nuit, symptômes généraux, perte de poids…)</p></li>
<li><p>La matrice de corrélation des items 2 à 2 ne retrouve pas de coefficient de corrélation supérieure à 0,50 en valeur absolu, il n’existe pas de redondance entre les items de l’échelle Hamilton.</p></li>
</ul>
</section>
<section id="validité-interne-structure-dimensionnelle-analyse-factorielle" class="level3" data-number="3.1.2">
<h3 data-number="3.1.2" class="anchored" data-anchor-id="validité-interne-structure-dimensionnelle-analyse-factorielle"><span class="header-section-number">3.1.2</span> Validité interne : structure dimensionnelle, analyse factorielle</h3>
<section id="exploration-de-la-structure-dimensionnelle-analyse-en-composantes-principales" class="level4" data-number="3.1.2.1">
<h4 data-number="3.1.2.1" class="anchored" data-anchor-id="exploration-de-la-structure-dimensionnelle-analyse-en-composantes-principales"><span class="header-section-number">3.1.2.1</span> Exploration de la structure dimensionnelle : analyse en composantes principales</h4>
<ul>
<li>On peut réaliser une analyse en composantes principales (ACP) pour visualiser les relations entre les items.</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="devoir_stats_avancees_files/figure-html/ACP%20J0-1.png" class="img-fluid figure-img" width="528"></p>
<figcaption>Analyse en composantes principales des items de l’échelle de Hamilton à J0</figcaption>
</figure>
</div>
</div>
</div>
<ul>
<li><p>Chaque point représente un item de l’échelle de Hamilton.</p></li>
<li><p>Deux axes principaux :</p>
<ul>
<li><p>l’axe horizontale <code>x</code> représente la première composante principale (PC1) qui explique 11% de la variance totale, l’axe verticale <code>y</code> représente la deuxième composante principale (PC2) qui explique 10% de la variance totale.</p></li>
<li><p>Ensemble, les deux premières composantes principales expliquent 21% de la variance totale, ce qui est relativement faible.</p></li>
</ul></li>
<li><p>La majorité des variables sont proches du centre, ce qui indique qu’elles ne contribuent pas fortement aux premières composantes principales.</p></li>
<li><p>Au total, cette ACP ne révèle pas de structure dimensionnelle claire parmi les items de l’échelle de Hamilton à J0.</p></li>
</ul>
</section>
<section id="exploration-de-la-structure-dimensionnelle-analyse-factorielle" class="level4" data-number="3.1.2.2">
<h4 data-number="3.1.2.2" class="anchored" data-anchor-id="exploration-de-la-structure-dimensionnelle-analyse-factorielle"><span class="header-section-number">3.1.2.2</span> Exploration de la structure dimensionnelle : analyse factorielle</h4>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="devoir_stats_avancees_files/figure-html/analyse%20factorielle%20J0-1.png" class="img-fluid figure-img" width="480"></p>
<figcaption>Diagramme des valeurs propres (scree plot) des items de l’échelle de Hamilton à J0 avec représentation de données simulées (analyse parallèle)</figcaption>
</figure>
</div>
</div>
</div>
<ul>
<li><p>À J0, le <em>scree plot</em> ne permet pas d’identifier un nombre clair de facteurs : les valeurs propres décroissent progressivement sans “coude” net.</p></li>
<li><p>En analyse parallèle, on observe au moins 3 dimensions ayant une valeur propre supérieure à celle obtenue sur des données simulées.</p></li>
<li><p>On pourrait réaliser des tests statistiques qui permettraient de déterminer le nombre optimal de dimensions, mais ces tests sont sujets à plusieurs biais :</p>
<ul>
<li><p>on calculerait une p-value pour l’hypothèse “n facteurs sont suffisants”</p></li>
<li><p>mais ces tests sont difficiles à interpréter et sensibles à la taille de l’échantillon</p></li>
<li><p>On retient donc 3 facteurs principaux pour l’analyse factorielle.</p></li>
</ul></li>
</ul>
<table class="caption-top table">
<caption>Contribution des facteurs à la variance de la réponse à chaque item du score de Hamilton évalué à J0 (analyse factorielle avec rotation varimax à 3 facteurs)</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: center;">Factor1</th>
<th style="text-align: center;">Factor2</th>
<th style="text-align: center;">Factor3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1_humeur_depressive</td>
<td style="text-align: center;">0.006</td>
<td style="text-align: center;">0.028</td>
<td style="text-align: center;">0.263</td>
</tr>
<tr class="even">
<td style="text-align: left;">2_sentim_culpabilite</td>
<td style="text-align: center;">-0.057</td>
<td style="text-align: center;">-0.076</td>
<td style="text-align: center;">0.240</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3_suicide</td>
<td style="text-align: center;">-0.021</td>
<td style="text-align: center;">-0.120</td>
<td style="text-align: center;">0.207</td>
</tr>
<tr class="even">
<td style="text-align: left;">4_insomnie_debut</td>
<td style="text-align: center;">0.110</td>
<td style="text-align: center;">0.359</td>
<td style="text-align: center;">-0.050</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5_insomnie_milieu</td>
<td style="text-align: center;">0.004</td>
<td style="text-align: center;">0.118</td>
<td style="text-align: center;">0.240</td>
</tr>
<tr class="even">
<td style="text-align: left;">6_insomnie_matin</td>
<td style="text-align: center;">0.132</td>
<td style="text-align: center;">-0.155</td>
<td style="text-align: center;">0.427</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7_travail_activite</td>
<td style="text-align: center;">0.124</td>
<td style="text-align: center;">0.121</td>
<td style="text-align: center;">0.320</td>
</tr>
<tr class="even">
<td style="text-align: left;">8_ralentissement</td>
<td style="text-align: center;">0.183</td>
<td style="text-align: center;">-0.105</td>
<td style="text-align: center;">0.101</td>
</tr>
<tr class="odd">
<td style="text-align: left;">9_agitation</td>
<td style="text-align: center;">-0.107</td>
<td style="text-align: center;">-0.228</td>
<td style="text-align: center;">0.501</td>
</tr>
<tr class="even">
<td style="text-align: left;">10_anxiete_psychique</td>
<td style="text-align: center;">0.066</td>
<td style="text-align: center;">-0.152</td>
<td style="text-align: center;">0.255</td>
</tr>
<tr class="odd">
<td style="text-align: left;">11_anxiete_somatique</td>
<td style="text-align: center;">-0.029</td>
<td style="text-align: center;">0.070</td>
<td style="text-align: center;">0.316</td>
</tr>
<tr class="even">
<td style="text-align: left;">12_symptomes_gastro</td>
<td style="text-align: center;">0.992</td>
<td style="text-align: center;">0.044</td>
<td style="text-align: center;">-0.091</td>
</tr>
<tr class="odd">
<td style="text-align: left;">13_symptomes_generaux</td>
<td style="text-align: center;">0.046</td>
<td style="text-align: center;">0.977</td>
<td style="text-align: center;">0.194</td>
</tr>
<tr class="even">
<td style="text-align: left;">14_symptomes_genitaux</td>
<td style="text-align: center;">0.238</td>
<td style="text-align: center;">0.120</td>
<td style="text-align: center;">0.147</td>
</tr>
<tr class="odd">
<td style="text-align: left;">15_hypochondrie</td>
<td style="text-align: center;">0.076</td>
<td style="text-align: center;">0.089</td>
<td style="text-align: center;">0.226</td>
</tr>
<tr class="even">
<td style="text-align: left;">16_perte_poids</td>
<td style="text-align: center;">0.424</td>
<td style="text-align: center;">0.155</td>
<td style="text-align: center;">-0.100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">17_prise_conscience</td>
<td style="text-align: center;">0.022</td>
<td style="text-align: center;">-0.004</td>
<td style="text-align: center;">0.176</td>
</tr>
</tbody>
</table>
<ul>
<li><p>À J0, l’analyse factorielle exploratoire avec rotation varimax met en évidence 3 facteurs latents expliquant cumulativement 21,9 % de la variance des réponses aux items du score de Hamilton.</p></li>
<li><p>Concernant l’interprétation du tableau des “loadings” (charges factorielles) :</p>
<ul>
<li><p>Les “loadings” (charges factorielles) indiquent la contribution de chaque item à chaque facteur. Ils mesure la force de la régression linéaire entre chaque item et chaque facteur latent. Plus l’item est proche de 1, plus il est expliqué par le facteur latent commun.</p></li>
<li><p>Il n’existe pas de “seuil” universel pour déterminer si un loading est “élevé” ou “faible”, mais généralement, un loading supérieur à 0,4 ou 0,5 est considéré comme significatif.</p></li>
</ul></li>
<li><p>On peut interpréter les 3 facteurs identifiés comme suit :</p>
<ul>
<li><p>Facteur 1 : 8, 12, 14, 16 (principalement des symptômes somatiques).</p></li>
<li><p>Facteur 2 : 4, 13 (relatifs à l’asthénie).</p></li>
<li><p>Facteur 3 : les items restants (symptômes dépressifs psychiatriques proprement dits).</p></li>
</ul></li>
</ul>
<p>On peut rajouter 3 “sous-scores” au score total de Hamilton à J0, correspondant aux scores moyens des items chargés sur chaque facteur.</p>
<ul>
<li>A titre exploratoire, on peut refaire une ACP sur ces 3 sous-scores pour visualiser leur relation.</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="devoir_stats_avancees_files/figure-html/ACP%20sous-scores%20J0-1.png" class="img-fluid figure-img" width="480"></p>
<figcaption>Analyse en composantes principales des sous-scores de l’échelle de Hamilton à J0</figcaption>
</figure>
</div>
</div>
</div>
<ul>
<li><p>Les 3 sous-scores sont bien représentés (proches du cercle). Le facteur “symptômes dépressifs” semble orthogonal aux deux autres facteurs.</p></li>
<li><p>La variance totale expliquée par ces 3 sous-score est de 69%.</p></li>
</ul>
<p>Une ACP focalisée sur ces 3 sous-scores et le score total de Hamilton permet de visualiser la relation entre le score total et les sous-scores.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="devoir_stats_avancees_files/figure-html/ACP%20focalisée%20J0-1.png" class="img-fluid figure-img" width="480"></p>
<figcaption>Analyse en composantes principales focalisée des sous-scores de l’échelle de Hamilton à J0</figcaption>
</figure>
</div>
</div>
</div>
<p>Le score total de Hamilton semble plus corrélé aux symptômes dépressifs (F3) qu’aux deux autres sous-scores.</p>
</section>
</section>
<section id="fiabilité-interne-que-vaut-la-mesure" class="level3" data-number="3.1.3">
<h3 data-number="3.1.3" class="anchored" data-anchor-id="fiabilité-interne-que-vaut-la-mesure"><span class="header-section-number">3.1.3</span> Fiabilité interne = que vaut la mesure ?</h3>
<section id="consistance-interne-alpha-de-cronbach" class="level4" data-number="3.1.3.1">
<h4 data-number="3.1.3.1" class="anchored" data-anchor-id="consistance-interne-alpha-de-cronbach"><span class="header-section-number">3.1.3.1</span> Consistance interne : alpha de Cronbach</h4>
<p>La consistance interne des items de l’échelle de Hamilton à J0 est évaluée par le calcul de l’alpha de Cronbach, qui correspond globalement au <strong>pourcentage de « variance partagée »</strong> entre le score vrai (hypothétique) et la mesure obtenue.</p>
<p>Il permet ainsi de mesurer la cohérence entre les items d’une échelle de mesure, et est élevé lorsque les items sont fortement corrélés entre eux.</p>
<p>On peut donc calculer dans un premier temps l’alpha de Cronbach sur l’ensemble des items de l’échelle de Hamilton à J0, puis sur chacun des 3 facteurs identifiés précédemment.</p>
<p>Les intervalles de confiance (IC) à 95% des alpha de Cronbach sont estimés par la méthode du bootstrap avec 1000 rééchantillonnages. Le bootstrap est possible ici car il y a &gt; 100 observations.</p>
<table class="caption-top table">
<caption>Alpha de Cronbach et intervalles de confiance à 95% pour l’échelle de Hamilton à J0 et ses sous-échelles</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Scale</th>
<th style="text-align: center;">Alpha</th>
<th style="text-align: center;">CI_lower</th>
<th style="text-align: center;">CI_upper</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Global</td>
<td style="text-align: center;">0.456</td>
<td style="text-align: center;">0.262</td>
<td style="text-align: center;">0.624</td>
</tr>
<tr class="even">
<td style="text-align: left;">F1_somatique</td>
<td style="text-align: center;">0.381</td>
<td style="text-align: center;">0.188</td>
<td style="text-align: center;">0.530</td>
</tr>
<tr class="odd">
<td style="text-align: left;">F2_asthenie</td>
<td style="text-align: center;">0.490</td>
<td style="text-align: center;">0.266</td>
<td style="text-align: center;">0.653</td>
</tr>
<tr class="even">
<td style="text-align: left;">F3_depressif</td>
<td style="text-align: center;">0.486</td>
<td style="text-align: center;">0.349</td>
<td style="text-align: center;">0.622</td>
</tr>
</tbody>
</table>
<p>Au total, quelque soit le niveau d’analyse (global ou par facteur), les alpha de Cronbach sont &lt; 0.5, indiquant une faible consistance interne des items de l’échelle de Hamilton à J0.</p>
</section>
</section>
<section id="validité-externe-linstrument-mesure-t-il-ce-quil-est-censé-mesurer" class="level3" data-number="3.1.4">
<h3 data-number="3.1.4" class="anchored" data-anchor-id="validité-externe-linstrument-mesure-t-il-ce-quil-est-censé-mesurer"><span class="header-section-number">3.1.4</span> Validité externe = l’instrument mesure-t-il ce qu’il est censé mesurer ?</h3>
<ul>
<li><p>Validité externe d’un instrument cherche à démontrer que l’instrument se comporte logiquement par rapport au réseau théorique qui lui est associé.</p></li>
<li><p>Selon la théorie nomologique (c’est à dire selon les relations postulées entre les différents concepts d’une même discipline), la dépression mesurée par l’échelle de Hamilton doit être fortement liée à d’autres manifestations de la détresse psychologique générale (mesurée par le SCL-90), mais distincte de certains autres concepts.</p>
<ul>
<li><p>Ici, la validité du construit peut être évaluée en évaluant la validité convergente (corrélation forte entre des concepts proches).</p></li>
<li><p>Il est plus difficile d’évaluer la validité divergente (corrélation faible entre des concepts différents) car le SCL-90 mesure principalement des dimensions de la détresse psychologique ; de même pour la validité concurrente (corrélation forte avec un <em>gold-standard</em>, car nous ne disposons pas d’un instrument de mesure de la dépression reconnu comme un <em>gold-standard</em> ici).</p></li>
</ul></li>
</ul>
<section id="corrélation-entre-le-score-de-hamilton-et-les-dimensions-du-scl-90-à-j0" class="level4" data-number="3.1.4.1">
<h4 data-number="3.1.4.1" class="anchored" data-anchor-id="corrélation-entre-le-score-de-hamilton-et-les-dimensions-du-scl-90-à-j0"><span class="header-section-number">3.1.4.1</span> Corrélation entre le score de Hamilton et les dimensions du SCL-90 à J0</h4>
<ul>
<li>On peut représenter une matrice de corrélation entre le score total de Hamilton et les 10 dimensions du SCL-90 à J0.</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="devoir_stats_avancees_files/figure-html/corrélation%20J0-1.png" class="img-fluid figure-img" width="480"></p>
<figcaption>Corrélation entre le score total de l’échelle de Hamilton et les dimensions du SCL-90 à J0</figcaption>
</figure>
</div>
</div>
</div>
<p>La corrélation est au maximum à 0.37 avec la composante “somatisation” du SCL-90 et de 0.40 avec la composante “symptômes divers” du SCL-90, indiquant une validité convergente modérée entre le score total de Hamilton et cette dimension du SCL-90 à J0.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="devoir_stats_avancees_files/figure-html/corrélation%20sous-scores%20J0-1.png" class="img-fluid figure-img" width="480"></p>
<figcaption>Corrélation entre les sous-scores de l’échelle de Hamilton et les dimensions SCL-90 à J0</figcaption>
</figure>
</div>
</div>
</div>
<ul>
<li><p>Il n’y a pas non plus de corrélation forte entre les sous-scores de Hamilton et les dimensions du SCL-90 à J0.</p></li>
<li><p>Par exemple, le sous-score “symptômes somatiques” de Hamilton est faiblement corrélé avec la dimension “somatisation” du SCL-90 (r = 0.07 !!).</p></li>
</ul>
</section>
<section id="conclusion-validité-externe-à-j0" class="level4" data-number="3.1.4.2">
<h4 data-number="3.1.4.2" class="anchored" data-anchor-id="conclusion-validité-externe-à-j0"><span class="header-section-number">3.1.4.2</span> Conclusion validité externe à J0</h4>
<p>La validité convergente entre le score total de Hamilton et les dimensions du SCL-90 à J0 est faible à modérée, suggérant que l’échelle de Hamilton mesure partiellement des aspects de la détresse psychologique générale, mais pas de manière très forte.</p>
</section>
</section>
<section id="conclusion-globale-à-j0" class="level3" data-number="3.1.5">
<h3 data-number="3.1.5" class="anchored" data-anchor-id="conclusion-globale-à-j0"><span class="header-section-number">3.1.5</span> Conclusion globale à J0</h3>
<p>À J0, l’échelle de dépression de Hamilton présente une structure dimensionnelle peu claire, avec une faible consistance interne des items (alpha de Cronbach &lt; 0.5) et une validité convergente modérée avec les dimensions du SCL-90.</p>
<p>Ces résultats suggèrent que l’échelle de Hamilton pourrait ne pas être un instrument optimal pour mesurer la dépression dans cette population à ce moment précis.</p>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="validation-à-j56" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="validation-à-j56"><span class="header-section-number">3.2</span> Validation à J56</h2>
<section id="description-1" class="level3" data-number="3.2.1">
<h3 data-number="3.2.1" class="anchored" data-anchor-id="description-1"><span class="header-section-number">3.2.1</span> Description</h3>
<p>[1] 120 [1] 146 [1] 82.19178</p>
<p>À J56, 120 des 146 patients présents à J0 ont répondu à tous les items : 17.8% des patients ont été perdus de vue.</p>
<p>Comme à J0, les réponses sont représentées :</p>
<ul>
<li><p>par des histogrammes pour chaque item de l’échelle de Hamilton à J56</p></li>
<li><p>par une matrice de corrélation 2 à 2 entre les items</p></li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="devoir_stats_avancees_files/figure-html/histo%20items%20J56-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Histogrammes des scores des items de l’échelle de Hamilton à J56</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="devoir_stats_avancees_files/figure-html/histo%20items%20J56-2.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Histogrammes des scores des items de l’échelle de Hamilton à J56</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="devoir_stats_avancees_files/figure-html/matrice%20corrélation%20J56-1.png" class="img-fluid figure-img" width="480"></p>
<figcaption>Matrice de corrélation entre les items de l’échelle de Hamilton à J56</figcaption>
</figure>
</div>
</div>
</div>
<ul>
<li><p>Sur les histogrammes, on observe un effet plancher, c’est à dire que de nombreux patients ont des scores faibles sur plusieurs items. Il est probable que ce soit lié à l’amélioration de la symptomatologie dépressive entre J0 et J56.</p></li>
<li><p>La matrice de corrélation des items met en évidence des coefficients de corrélation plus élevés que ceux observés à J0, avec plusieurs coefficients supérieurs à 0.5 en valeur absolue, indiquant une certaine redondance entre les items de l’échelle Hamilton à J56.</p>
<ul>
<li>Il est possible que cette redondance soit liée à l’effet plancher observé sur les histogrammes, où de nombreux patients ont des scores faibles sur plusieurs items, ce qui peut augmenter artificiellement les corrélations entre ces items.</li>
</ul></li>
</ul>
</section>
<section id="validité-interne-structure-dimensionnelle-analyse-factorielle-1" class="level3" data-number="3.2.2">
<h3 data-number="3.2.2" class="anchored" data-anchor-id="validité-interne-structure-dimensionnelle-analyse-factorielle-1"><span class="header-section-number">3.2.2</span> Validité interne : structure dimensionnelle, analyse factorielle</h3>
<section id="exploration-de-la-structure-dimensionnelle-analyse-en-composantes-principales-1" class="level4" data-number="3.2.2.1">
<h4 data-number="3.2.2.1" class="anchored" data-anchor-id="exploration-de-la-structure-dimensionnelle-analyse-en-composantes-principales-1"><span class="header-section-number">3.2.2.1</span> Exploration de la structure dimensionnelle : analyse en composantes principales</h4>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="devoir_stats_avancees_files/figure-html/ACP%20J56-1.png" class="img-fluid figure-img" width="528"></p>
<figcaption>Analyse en composantes principales des items de l’échelle de Hamilton à J56</figcaption>
</figure>
</div>
</div>
</div>
<ul>
<li><p>La première composante principale explique 28% de la variance totale, la deuxième composante principale explique 10% de la variance totale.</p>
<ul>
<li><p>Les deux premières composantes principales expliquent 38% de la variance totale, ce qui est une amélioration par rapport à J0.</p></li>
<li><p>Certaines variables sont un peu plus éloignées du centre qu’à J0, il est possible qu’elles contribuent davantage aux premières composantes principales.</p></li>
</ul></li>
</ul>
</section>
<section id="exploration-de-la-structure-dimensionnelle-analyse-factorielle-1" class="level4" data-number="3.2.2.2">
<h4 data-number="3.2.2.2" class="anchored" data-anchor-id="exploration-de-la-structure-dimensionnelle-analyse-factorielle-1"><span class="header-section-number">3.2.2.2</span> Exploration de la structure dimensionnelle : analyse factorielle</h4>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="devoir_stats_avancees_files/figure-html/analyse%20factorielle%20J56-1.png" class="img-fluid figure-img" width="480"></p>
<figcaption>Diagramme des valeurs propres (scree plot) des items de l’échelle de Hamilton à J56 avec représentation de données simulées (analyse parallèle)</figcaption>
</figure>
</div>
</div>
</div>
<ul>
<li><p>À J56, le <em>scree plot</em> n’est pas du tout le même qu’à J0 : on observe un “coude” net après la première valeur propre.</p></li>
<li><p><strong>L’échelle Hamilton à J56 semble donc essentiellement unidimensionnelle.</strong></p></li>
</ul>
<table class="caption-top table">
<caption>Contribution du facteur unique à la variance de la réponse à chaque item du score de Hamilton évalué à J56 (analyse factorielle avec rotation varimax à 1 facteur)</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: center;">Factor1</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1_humeur_depressive</td>
<td style="text-align: center;">0.802</td>
</tr>
<tr class="even">
<td style="text-align: left;">2_sentim_culpabilite</td>
<td style="text-align: center;">0.468</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3_suicide</td>
<td style="text-align: center;">0.706</td>
</tr>
<tr class="even">
<td style="text-align: left;">4_insomnie_debut</td>
<td style="text-align: center;">0.333</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5_insomnie_milieu</td>
<td style="text-align: center;">0.456</td>
</tr>
<tr class="even">
<td style="text-align: left;">6_insomnie_matin</td>
<td style="text-align: center;">0.282</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7_travail_activite</td>
<td style="text-align: center;">0.745</td>
</tr>
<tr class="even">
<td style="text-align: left;">8_ralentissement</td>
<td style="text-align: center;">0.657</td>
</tr>
<tr class="odd">
<td style="text-align: left;">9_agitation</td>
<td style="text-align: center;">0.328</td>
</tr>
<tr class="even">
<td style="text-align: left;">10_anxiete_psychique</td>
<td style="text-align: center;">0.624</td>
</tr>
<tr class="odd">
<td style="text-align: left;">11_anxiete_somatique</td>
<td style="text-align: center;">0.401</td>
</tr>
<tr class="even">
<td style="text-align: left;">12_symptomes_gastro</td>
<td style="text-align: center;">0.471</td>
</tr>
<tr class="odd">
<td style="text-align: left;">13_symptomes_generaux</td>
<td style="text-align: center;">0.495</td>
</tr>
<tr class="even">
<td style="text-align: left;">14_symptomes_genitaux</td>
<td style="text-align: center;">0.252</td>
</tr>
<tr class="odd">
<td style="text-align: left;">15_hypochondrie</td>
<td style="text-align: center;">0.494</td>
</tr>
<tr class="even">
<td style="text-align: left;">16_perte_poids</td>
<td style="text-align: center;">0.125</td>
</tr>
<tr class="odd">
<td style="text-align: left;">17_prise_conscience</td>
<td style="text-align: center;">-0.132</td>
</tr>
</tbody>
</table>
<ul>
<li><p>Les valeurs numériques mesurent la force de la relation linéaire entre chaque item observé et le facteur latent unique.</p></li>
<li><p>Les symptômes centraux de la dépression (humeur dépressive, ralentissement, baisse d’activité) présentent les charges factorielles les plus élevées, indiquant qu’ils sont de bons indicateurs du facteur latent unique (la dépression).</p></li>
<li><p>Certains items périphériques (perte de poids, symptômes génitaux) ont une très faible charge, ils peuvent être peu informatifs et faiblement contribuer à la mesure du concept unique de dépression à J56. Leur pertinence dans le score total de l’instrument peut être remise en question.</p></li>
</ul>
</section>
</section>
<section id="fiabilité-interne-que-vaut-la-mesure-1" class="level3" data-number="3.2.3">
<h3 data-number="3.2.3" class="anchored" data-anchor-id="fiabilité-interne-que-vaut-la-mesure-1"><span class="header-section-number">3.2.3</span> Fiabilité interne = que vaut la mesure ?</h3>
<section id="consistance-interne-alpha-de-cronbach-1" class="level4" data-number="3.2.3.1">
<h4 data-number="3.2.3.1" class="anchored" data-anchor-id="consistance-interne-alpha-de-cronbach-1"><span class="header-section-number">3.2.3.1</span> Consistance interne : alpha de Cronbach</h4>
<p>La consistance interne des items de l’échelle de Hamilton à J56 est évaluée par le calcul de l’alpha de Cronbach, et son IC à 95% par la méthode du bootstrap avec 1000 rééchantillonnages.</p>
<table class="caption-top table">
<caption>Alpha de Cronbach et intervalle de confiance à 95% pour l’échelle de Hamilton à J56</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Scale</th>
<th style="text-align: center;">Alpha</th>
<th style="text-align: center;">CI_lower</th>
<th style="text-align: center;">CI_upper</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Global</td>
<td style="text-align: center;">0.82</td>
<td style="text-align: center;">0.76</td>
<td style="text-align: center;">0.86</td>
</tr>
</tbody>
</table>
<ul>
<li>A J56, l’alpha de Cronbach est de 0.82, avec un intervalle de confiance à 95% de [0.75 ; 0.86], indiquant une bonne consistance interne des items de l’échelle de Hamilton à ce moment. Elle n’est pas exagérément lourde ni redondante.</li>
</ul>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="validité-externe-linstrument-mesure-t-il-ce-quil-est-censé-mesurer-1" class="level3" data-number="3.2.4">
<h3 data-number="3.2.4" class="anchored" data-anchor-id="validité-externe-linstrument-mesure-t-il-ce-quil-est-censé-mesurer-1"><span class="header-section-number">3.2.4</span> Validité externe = l’instrument mesure-t-il ce qu’il est censé mesurer ?</h3>
<p>De la même manière qu’à J0, la validité externe de l’échelle de Hamilton à J56 peut être évaluée en examinant la corrélation entre le score total de Hamilton et les dimensions du SCL-90.</p>
<section id="corrélation-entre-le-score-de-hamilton-et-les-dimensions-du-scl-90-à-j56" class="level4" data-number="3.2.4.1">
<h4 data-number="3.2.4.1" class="anchored" data-anchor-id="corrélation-entre-le-score-de-hamilton-et-les-dimensions-du-scl-90-à-j56"><span class="header-section-number">3.2.4.1</span> Corrélation entre le score de Hamilton et les dimensions du SCL-90 à J56</h4>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="devoir_stats_avancees_files/figure-html/corrélation%20J56-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Corrélation entre score total de Hamilton et les dimensions du SCL-90 à J56</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="devoir_stats_avancees_files/figure-html/corrélation%20sous-scores%20J56-1.png" class="img-fluid figure-img" width="480"></p>
<figcaption>ACP focalisée du score total de l’échelle de Hamilton et des dimensions du SCL-90 à J56</figcaption>
</figure>
</div>
</div>
</div>
<ul>
<li><p>Les corrélations sont plus importantes entre les sous-scores de SCL90 et le score d’Hamilton à J56, : ces deux échelles mesurent probablement la même chose.</p></li>
<li><p>La sous échelle dépression du SCL90 est particulièrement corrélée avec le score d’Hamilton.</p></li>
</ul>
</section>
<section id="conclusion-validité-externe-à-j56" class="level4" data-number="3.2.4.2">
<h4 data-number="3.2.4.2" class="anchored" data-anchor-id="conclusion-validité-externe-à-j56"><span class="header-section-number">3.2.4.2</span> Conclusion validité externe à J56</h4>
<p>La validité convergente entre le score total de Hamilton et les dimensions du SCL-90 à J56 est modérée à forte, suggérant que l’échelle de Hamilton mesure des aspects pertinents de la détresse psychologique générale à ce moment.</p>
</section>
</section>
<section id="conclusion-globale-à-j56" class="level3" data-number="3.2.5">
<h3 data-number="3.2.5" class="anchored" data-anchor-id="conclusion-globale-à-j56"><span class="header-section-number">3.2.5</span> Conclusion globale à J56</h3>
<p>À J56, l’échelle de dépression de Hamilton présente une structure dimensionnelle essentiellement unidimensionnelle, avec une bonne consistance interne des items (alpha de Cronbach = 0.82) et une validité convergente modérée à forte avec les dimensions du SCL-90.</p>
<p>Au total, ces résultats suggèrent que l’échelle de Hamilton est un instrument valide et fiable pour mesurer la dépression dans cette population à J56.</p>
</section>
<section id="synthèse-des-résultats-de-validation-de-léchelle-de-hamilton-à-j0-et-j56" class="level3" data-number="3.2.6">
<h3 data-number="3.2.6" class="anchored" data-anchor-id="synthèse-des-résultats-de-validation-de-léchelle-de-hamilton-à-j0-et-j56"><span class="header-section-number">3.2.6</span> Synthèse des résultats de validation de l’échelle de Hamilton à J0 et J56</h3>
<p>Tableau récapitulatif des principaux résultats de validation de l’échelle de Hamilton à J0 et J56 :</p>
<table class="caption-top table">
<colgroup>
<col style="width: 30%">
<col style="width: 35%">
<col style="width: 35%">
</colgroup>
<thead>
<tr class="header">
<th>Aspect</th>
<th>J0</th>
<th>J56</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Structure dimensionnelle</td>
<td>Multidimensionnelle (3 facteurs)</td>
<td>Essentiellement unidimensionnelle</td>
</tr>
<tr class="even">
<td>Consistance interne (<span class="math inline">\(Alpha\)</span> de Cronbach)</td>
<td>Faible (<span class="math inline">\(\alpha\)</span> = 0.45 [0.39 ; 0.51])</td>
<td>Bonne (<span class="math inline">\(\alpha\)</span> = 0.82 [0.75 ; 0.86])</td>
</tr>
<tr class="odd">
<td>Validité convergente (corrélation avec SCL-90)</td>
<td>Modérée (max = 0.40)</td>
<td>Plus élevée (max = 0.85)</td>
</tr>
<tr class="even">
<td>Conclusion globale</td>
<td>Structure dimensionnelle peu claire, faible consistance interne, validité convergente modérée</td>
<td>Essentiellement unidimensionnelle, bonne consistance interne, validité convergente modérée à forte</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Validité divergente</strong></p>
<p>La validité divergente (ou discriminante) fait référence à la capacité d’un instrument de mesure à ne pas être fortement corrélé avec des concepts ou des mesures qui sont théoriquement distincts. En d’autres termes, un instrument doit montrer qu’il mesure un concept spécifique sans être influencé de manière significative par d’autres concepts non liés.</p>
<p>En l’occurence, on ne dispose pas d’instruments mesurant des concepts clairement distincts de la dépression dans ce jeu de données, ce qui limite notre capacité à évaluer la validité divergente de l’échelle de Hamilton dans ce contexte.</p>
</div>
</div>
<div style="page-break-after: always;"></div>
</section>
</section>
</section>
<section id="question-2-comparaison-de-la-réponse-au-traitement-entre-deux-groupes-de-patients" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Question 2 : Comparaison de la réponse au traitement entre deux groupes de patients</h1>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Consigne</strong></p>
<p>“A partir du score brut de Hamilton, déterminez si les patients du groupe <code>groupe=1</code> répondent mieux au traitement que les patients du groupe <code>groupe=0</code>. (utilisez d’abord une approche LOCF (last observation carried forward), puis un modèle mixte).”</p>
</div>
</div>
<section id="gestion-des-données-1" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="gestion-des-données-1"><span class="header-section-number">4.1</span> Gestion des données</h2>
<p>Il faut utiliser</p>
</section>
<section id="scores-bruts-à-j0-dans-chaque-groupe" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="scores-bruts-à-j0-dans-chaque-groupe"><span class="header-section-number">4.2</span> Scores bruts à J0 dans chaque groupe</h2>
<ul>
<li>Présentation en tableau des scores bruts de l’échelle de Hamilton à J0 dans chaque groupe de traitement avec effectifs, moyennes, écarts-types, médianes et intervalles interquartiles.</li>
</ul>
<table class="caption-top table">
<caption>Scores bruts de l’échelle de Hamilton à J0 par groupe de traitement</caption>
<thead>
<tr class="header">
<th style="text-align: left;">GROUPE</th>
<th style="text-align: center;">N</th>
<th style="text-align: center;">Moyenne</th>
<th style="text-align: center;">Écart type</th>
<th style="text-align: center;">Médiane</th>
<th style="text-align: center;">Q1</th>
<th style="text-align: center;">Q3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">0</td>
<td style="text-align: center;">75</td>
<td style="text-align: center;">28.1</td>
<td style="text-align: center;">4.43</td>
<td style="text-align: center;">27</td>
<td style="text-align: center;">26</td>
<td style="text-align: center;">30</td>
</tr>
<tr class="even">
<td style="text-align: left;">1</td>
<td style="text-align: center;">71</td>
<td style="text-align: center;">27.8</td>
<td style="text-align: center;">3.97</td>
<td style="text-align: center;">27</td>
<td style="text-align: center;">25</td>
<td style="text-align: center;">30</td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="devoir_stats_avancees_files/figure-html/histo%20et%20boxplot%20J0%20par%20groupe-1.png" class="img-fluid figure-img" width="576"></p>
<figcaption>Histogramme et boxplot présentant les scores bruts de l’échelle de Hamilton à J0</figcaption>
</figure>
</div>
</div>
</div>
<section id="comparaison-des-scores-bruts-à-j0-entre-les-deux-groupes" class="level3" data-number="4.2.1">
<h3 data-number="4.2.1" class="anchored" data-anchor-id="comparaison-des-scores-bruts-à-j0-entre-les-deux-groupes"><span class="header-section-number">4.2.1</span> Comparaison des scores bruts à J0 entre les deux groupes</h3>
<ul>
<li><p>Un histogramme des scores bruts à J0 à déjà été présenté ci-dessus.</p></li>
<li><p>La distribution semble approximativement normale dans chaque groupe.</p></li>
<li><p>On peut donc comparer les scores bruts moyens entre les deux groupes par un test t de Student pour échantillons indépendants.</p></li>
</ul>
<div id="rxcflkqwmi" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#rxcflkqwmi table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#rxcflkqwmi thead, #rxcflkqwmi tbody, #rxcflkqwmi tfoot, #rxcflkqwmi tr, #rxcflkqwmi td, #rxcflkqwmi th {
  border-style: none;
}

#rxcflkqwmi p {
  margin: 0;
  padding: 0;
}

#rxcflkqwmi .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#rxcflkqwmi .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#rxcflkqwmi .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#rxcflkqwmi .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#rxcflkqwmi .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#rxcflkqwmi .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#rxcflkqwmi .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#rxcflkqwmi .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#rxcflkqwmi .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#rxcflkqwmi .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#rxcflkqwmi .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#rxcflkqwmi .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#rxcflkqwmi .gt_spanner_row {
  border-bottom-style: hidden;
}

#rxcflkqwmi .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#rxcflkqwmi .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#rxcflkqwmi .gt_from_md > :first-child {
  margin-top: 0;
}

#rxcflkqwmi .gt_from_md > :last-child {
  margin-bottom: 0;
}

#rxcflkqwmi .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#rxcflkqwmi .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#rxcflkqwmi .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#rxcflkqwmi .gt_row_group_first td {
  border-top-width: 2px;
}

#rxcflkqwmi .gt_row_group_first th {
  border-top-width: 2px;
}

#rxcflkqwmi .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#rxcflkqwmi .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#rxcflkqwmi .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#rxcflkqwmi .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#rxcflkqwmi .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#rxcflkqwmi .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#rxcflkqwmi .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#rxcflkqwmi .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#rxcflkqwmi .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#rxcflkqwmi .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#rxcflkqwmi .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#rxcflkqwmi .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#rxcflkqwmi .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#rxcflkqwmi .gt_left {
  text-align: left;
}

#rxcflkqwmi .gt_center {
  text-align: center;
}

#rxcflkqwmi .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#rxcflkqwmi .gt_font_normal {
  font-weight: normal;
}

#rxcflkqwmi .gt_font_bold {
  font-weight: bold;
}

#rxcflkqwmi .gt_font_italic {
  font-style: italic;
}

#rxcflkqwmi .gt_super {
  font-size: 65%;
}

#rxcflkqwmi .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#rxcflkqwmi .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#rxcflkqwmi .gt_indent_1 {
  text-indent: 5px;
}

#rxcflkqwmi .gt_indent_2 {
  text-indent: 10px;
}

#rxcflkqwmi .gt_indent_3 {
  text-indent: 15px;
}

#rxcflkqwmi .gt_indent_4 {
  text-indent: 20px;
}

#rxcflkqwmi .gt_indent_5 {
  text-indent: 25px;
}

#rxcflkqwmi .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#rxcflkqwmi div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table caption-top table" data-quarto-bootstrap="false">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="gt_col_headings header">
<th id="label" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col"><strong>Characteristic</strong></th>
<th id="stat_1" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>0</strong><br>
N = 75<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span></th>
<th id="stat_2" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>1</strong><br>
N = 71<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span></th>
<th id="p.value" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>p-value</strong><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>2</sup></span></th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="label">score</td>
<td class="gt_row gt_center" headers="stat_1">28.05 (4.43)</td>
<td class="gt_row gt_center" headers="stat_2">27.79 (3.97)</td>
<td class="gt_row gt_center" headers="p.value">0.7</td>
</tr>
</tbody><tfoot>
<tr class="gt_footnotes odd">
<td colspan="4" class="gt_footnote"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span> Mean (SD)</td>
</tr>
<tr class="gt_footnotes even">
<td colspan="4" class="gt_footnote"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>2</sup></span> Two Sample t-test</td>
</tr>
</tfoot>

</table>

</div>
<p>NB : la fonction utilisée ici est <code>tbl_summary</code> du package <code>gtsummary</code> permet de réaliser des tableaux de synthèse avec des tests statistiques intégrés.</p>
</section>
</section>
<section id="évolution-des-scores-bruts-entre-j0-et-j56-dans-chaque-groupe" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="évolution-des-scores-bruts-entre-j0-et-j56-dans-chaque-groupe"><span class="header-section-number">4.3</span> Évolution des scores bruts entre J0 et J56 dans chaque groupe</h2>
<section id="évolution-du-nombre-de-patients-dans-chaque-groupe-à-chaque-visite" class="level3" data-number="4.3.1">
<h3 data-number="4.3.1" class="anchored" data-anchor-id="évolution-du-nombre-de-patients-dans-chaque-groupe-à-chaque-visite"><span class="header-section-number">4.3.1</span> Évolution du nombre de patients dans chaque groupe à chaque visite</h3>
<ul>
<li>Nombre de données entre chaque visite entre J0 et J56 dans chaque groupe :</li>
</ul>
<p>A la visite J56, les visites manquent pour 11 patients sur 75 dans le groupe 0 (14,7%), contre 15 patients sur 56 dans le groupe 1 (26,8%).</p>
<table class="caption-top table">
<caption>Nombre de patients par groupe de traitement et visite</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">J0</th>
<th style="text-align: center;">J4</th>
<th style="text-align: center;">J7</th>
<th style="text-align: center;">J14</th>
<th style="text-align: center;">J21</th>
<th style="text-align: center;">J28</th>
<th style="text-align: center;">J42</th>
<th style="text-align: center;">J56</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">0</td>
<td style="text-align: left;">75</td>
<td style="text-align: center;">72</td>
<td style="text-align: center;">71</td>
<td style="text-align: center;">70</td>
<td style="text-align: center;">69</td>
<td style="text-align: center;">68</td>
<td style="text-align: center;">65</td>
<td style="text-align: center;">64</td>
</tr>
<tr class="even">
<td style="text-align: left;">1</td>
<td style="text-align: left;">71</td>
<td style="text-align: center;">67</td>
<td style="text-align: center;">65</td>
<td style="text-align: center;">63</td>
<td style="text-align: center;">60</td>
<td style="text-align: center;">59</td>
<td style="text-align: center;">57</td>
<td style="text-align: center;">56</td>
</tr>
</tbody>
</table>
<p>A la visite J56, les visites manquent pour 11 patients sur 75 dans le groupe 0 (14,7%), contre 15 patients sur 56 dans le groupe 1 (26,8%).</p>
</section>
<section id="évolution-des-scores-bruts-moyens-entre-j0-et-j56-dans-chaque-groupe" class="level3" data-number="4.3.2">
<h3 data-number="4.3.2" class="anchored" data-anchor-id="évolution-des-scores-bruts-moyens-entre-j0-et-j56-dans-chaque-groupe"><span class="header-section-number">4.3.2</span> Évolution des scores bruts moyens entre J0 et J56 dans chaque groupe</h3>
<p>On peut représenter :</p>
<ul>
<li>L’évolution des scores bruts moyens dans chacun des groupes avec des boxplot à chaque visite</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="devoir_stats_avancees_files/figure-html/boxplot%20scores%20bruts%20par%20visite%20et%20groupe-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Évolution des scores moyens entre J0 et J56 dans chaque groupe</figcaption>
</figure>
</div>
</div>
</div>
<ul>
<li>L’évolution par patients (dans chacun des groupes), avec un diagramme en spaghetti, d’interprétation plus difficile mais qui montre les trajectories individuelles.</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="devoir_stats_avancees_files/figure-html/spaghetti%20scores%20bruts%20par%20visite%20et%20groupe-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Évolution individuelle des scores entre J0 et J56 dans chaque groupe</figcaption>
</figure>
</div>
</div>
</div>
<ul>
<li>De nouveaux boxplots qui montre le score à J56 côte à côte pour chaque groupe.</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="devoir_stats_avancees_files/figure-html/boxplot%20scores%20bruts%20J0%20et%20J56%20par%20groupe-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Scores bruts de l’échelle de Hamilton à J56 dans chaque groupe de traitement</figcaption>
</figure>
</div>
</div>
</div>
<p>Quelque soit la méthode de visualiation, on observe une tendance diminution des scores bruts moyens de l’échelle de Hamilton entre J0 et J56 dans les deux groupes de traitement.</p>
<p>La diminution semble plus marquée dans le groupe 0 que dans le groupe 1.</p>
</section>
</section>
<section id="comparaison-de-la-réponse-au-traitement-entre-deux-groupes-de-patients" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="comparaison-de-la-réponse-au-traitement-entre-deux-groupes-de-patients"><span class="header-section-number">4.4</span> Comparaison de la réponse au traitement entre deux groupes de patients</h2>
<p>L’objectif est donc de déterminer si un des groupes répond mieux au traitement que l’autre, en comparant l’évolution des scores bruts entre J0 et J56 dans chaque group, en utilisant d’abord une approche LOCF (last observation carried forward), puis un modèle mixte.</p>
<section id="compraison-de-la-réponse-en-utilisant-la-méthode-locf" class="level3" data-number="4.4.1">
<h3 data-number="4.4.1" class="anchored" data-anchor-id="compraison-de-la-réponse-en-utilisant-la-méthode-locf"><span class="header-section-number">4.4.1</span> Compraison de la réponse en utilisant la méthode LOCF</h3>
<section id="imputation-des-données-manquantes-par-la-méthode-locf-last-observation-carried-forward" class="level4" data-number="4.4.1.1">
<h4 data-number="4.4.1.1" class="anchored" data-anchor-id="imputation-des-données-manquantes-par-la-méthode-locf-last-observation-carried-forward"><span class="header-section-number">4.4.1.1</span> Imputation des données manquantes par la méthode LOCF (last observation carried forward)</h4>
<p>Méthode LOCF = on remplace les valeurs manquantes par la dernière valeur observée pour chaque patient.</p>
<p>On applique la fonction <code>na.locf</code> du package <code>zoo</code> pour réaliser cette imputation.</p>
<table class="caption-top table">
<caption>Nombre de patients par groupe de traitement et visite après imputation LOCF</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">J0</th>
<th style="text-align: center;">J14</th>
<th style="text-align: center;">J21</th>
<th style="text-align: center;">J28</th>
<th style="text-align: center;">J4</th>
<th style="text-align: center;">J42</th>
<th style="text-align: center;">J56</th>
<th style="text-align: center;">J7</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">0</td>
<td style="text-align: left;">75</td>
<td style="text-align: center;">75</td>
<td style="text-align: center;">75</td>
<td style="text-align: center;">75</td>
<td style="text-align: center;">75</td>
<td style="text-align: center;">75</td>
<td style="text-align: center;">75</td>
<td style="text-align: center;">75</td>
</tr>
<tr class="even">
<td style="text-align: left;">1</td>
<td style="text-align: left;">71</td>
<td style="text-align: center;">71</td>
<td style="text-align: center;">71</td>
<td style="text-align: center;">71</td>
<td style="text-align: center;">71</td>
<td style="text-align: center;">71</td>
<td style="text-align: center;">71</td>
<td style="text-align: center;">71</td>
</tr>
</tbody>
</table>
</section>
<section id="comparaison-de-la-réponse-au-traitement-entre-les-deux-groupes-après-imputation-locf" class="level4" data-number="4.4.1.2">
<h4 data-number="4.4.1.2" class="anchored" data-anchor-id="comparaison-de-la-réponse-au-traitement-entre-les-deux-groupes-après-imputation-locf"><span class="header-section-number">4.4.1.2</span> Comparaison de la réponse au traitement entre les deux groupes après imputation LOCF</h4>
<p>Il faut comparer l’évolution des scores bruts moyens entre J0 et J56, donc la différence de score entre J56 et J0, entre les deux groupes.</p>
<p>Pour ça, on crée une nouvelle variable “difference” qui correspond à la différence entre le score à J56 et le score à J0 (après imputation LOCF).</p>
<p>On fait maintenant un test t de Student pour comparer la différence moyenne de score entre J0 et J56 entre les deux groupes.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="devoir_stats_avancees_files/figure-html/conditions%20de%20validité%20du%20test%20t%20sur%20la%20différence%20LOCF-1.png" class="img-fluid figure-img" width="576"></p>
<figcaption>Histogramme et QQ-plot de la différence de score entre J0 et J56 (après imputation LOCF) sur l’échantillon complet</figcaption>
</figure>
</div>
<p>Les conditions de validité semblent respectées pour le test t de Student sur la différence de score entre J0 et J56 (après imputation LOCF) sur l’échantillon complet.</p>
<div id="wicseozjch" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#wicseozjch table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#wicseozjch thead, #wicseozjch tbody, #wicseozjch tfoot, #wicseozjch tr, #wicseozjch td, #wicseozjch th {
  border-style: none;
}

#wicseozjch p {
  margin: 0;
  padding: 0;
}

#wicseozjch .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#wicseozjch .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#wicseozjch .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#wicseozjch .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#wicseozjch .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#wicseozjch .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#wicseozjch .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#wicseozjch .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#wicseozjch .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#wicseozjch .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#wicseozjch .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#wicseozjch .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#wicseozjch .gt_spanner_row {
  border-bottom-style: hidden;
}

#wicseozjch .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#wicseozjch .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#wicseozjch .gt_from_md > :first-child {
  margin-top: 0;
}

#wicseozjch .gt_from_md > :last-child {
  margin-bottom: 0;
}

#wicseozjch .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#wicseozjch .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#wicseozjch .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#wicseozjch .gt_row_group_first td {
  border-top-width: 2px;
}

#wicseozjch .gt_row_group_first th {
  border-top-width: 2px;
}

#wicseozjch .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#wicseozjch .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#wicseozjch .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#wicseozjch .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#wicseozjch .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#wicseozjch .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#wicseozjch .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#wicseozjch .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#wicseozjch .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#wicseozjch .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#wicseozjch .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#wicseozjch .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#wicseozjch .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#wicseozjch .gt_left {
  text-align: left;
}

#wicseozjch .gt_center {
  text-align: center;
}

#wicseozjch .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#wicseozjch .gt_font_normal {
  font-weight: normal;
}

#wicseozjch .gt_font_bold {
  font-weight: bold;
}

#wicseozjch .gt_font_italic {
  font-style: italic;
}

#wicseozjch .gt_super {
  font-size: 65%;
}

#wicseozjch .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#wicseozjch .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#wicseozjch .gt_indent_1 {
  text-indent: 5px;
}

#wicseozjch .gt_indent_2 {
  text-indent: 10px;
}

#wicseozjch .gt_indent_3 {
  text-indent: 15px;
}

#wicseozjch .gt_indent_4 {
  text-indent: 20px;
}

#wicseozjch .gt_indent_5 {
  text-indent: 25px;
}

#wicseozjch .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#wicseozjch div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table caption-top table" data-quarto-bootstrap="false">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="gt_col_headings header">
<th id="label" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col"><strong>Characteristic</strong></th>
<th id="stat_1" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>0</strong><br>
N = 75<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span></th>
<th id="stat_2" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>1</strong><br>
N = 71<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span></th>
<th id="p.value" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>p-value</strong><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>2</sup></span></th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="label">difference</td>
<td class="gt_row gt_center" headers="stat_1">-19.92 (8.68)</td>
<td class="gt_row gt_center" headers="stat_2">-14.79 (8.15)</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
</tbody><tfoot>
<tr class="gt_footnotes odd">
<td colspan="4" class="gt_footnote"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span> Mean (SD)</td>
</tr>
<tr class="gt_footnotes even">
<td colspan="4" class="gt_footnote"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>2</sup></span> Two Sample t-test</td>
</tr>
</tfoot>

</table>

</div>
<p>Le test t montre une différence moyenne de score entre J0 et J56 significativement plus élevée das le groupe 0 (-19,92) que dans le groupe 1 (-14,79), avec une p-value &lt; 0.001.</p>
<p>Le problème majeur de cette méthode est qu’elle ne tient pas en compte que les mesures sont répétées chez les mêmes patients !</p>
<p>En utilisant un modèle mixte, on va pouvoir prendre en compte cette dépendance entre les mesures répétées en modélisant un effet aléatoire pour chaque patient.</p>
</section>
</section>
<section id="comparaison-de-la-réponse-en-utilisant-un-modèle-mixte" class="level3" data-number="4.4.2">
<h3 data-number="4.4.2" class="anchored" data-anchor-id="comparaison-de-la-réponse-en-utilisant-un-modèle-mixte"><span class="header-section-number">4.4.2</span> Comparaison de la réponse en utilisant un modèle mixte</h3>
<p>Ici on veut comparer l’évolution du score HDRS entre les groupes <strong>en tenant compte des mesures répétées</strong> (plusieurs visites par patient).</p>
<p>Un modèle linéaire mixte (LMM) est adapté car il modélise la corrélation intra-patient.</p>
<ul>
<li><p>Variable à expliquer : <code>score</code> (après imputation LOCF), quantitative, discrète.</p></li>
<li><p>Effets fixes : <code>VISIT</code> et <code>GROUPE</code>.</p></li>
<li><p>Effet aléatoire : un intercept par patient <code>(1|NUMERO)</code> pour tenir compte du niveau moyen différent selon les patients, donc une ordonnée à l’origine différente pour chaque patient.</p></li>
</ul>
<p>On peut envisager deux modèles :</p>
<ul>
<li><p><strong>Sans interaction</strong> : suppose des trajectoires « parallèles » à chaque visite (différence entre groupes constante au cours du temps).</p></li>
<li><p><strong>Avec interaction <code>VISIT*GROUPE</code></strong> : teste si l’évolution au cours du temps diffère entre groupes (c’est le test principal pour « répond mieux »).</p></li>
</ul>
<p>La question résiduelle est le codage de la variable <code>VISIT</code> : on peut la traiter comme une variable catégorielle (facteur) ou continue (temps).</p>
<p>Dans le code, on fera les deux pour voir si ça change les résultats.</p>
<section id="modèle-mixte-sans-interaction" class="level4" data-number="4.4.2.1">
<h4 data-number="4.4.2.1" class="anchored" data-anchor-id="modèle-mixte-sans-interaction"><span class="header-section-number">4.4.2.1</span> Modèle mixte sans interaction</h4>
<section id="modèle-mixte-sans-interaction-avec-visit-comme-facteur-et-j0-comme-référence" class="level5" data-number="4.4.2.1.1">
<h5 data-number="4.4.2.1.1" class="anchored" data-anchor-id="modèle-mixte-sans-interaction-avec-visit-comme-facteur-et-j0-comme-référence"><span class="header-section-number">4.4.2.1.1</span> Modèle mixte sans interaction avec <code>VISIT</code> comme facteur et J0 comme référence</h5>
<table class="caption-top table">
<caption>Estimation des coefficients du modèle mixte sans interaction entre VISIT (facteur) et GROUPE</caption>
<colgroup>
<col style="width: 16%">
<col style="width: 14%">
<col style="width: 15%">
<col style="width: 12%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Coefficient</th>
<th style="text-align: center;">Estimate</th>
<th style="text-align: center;">Std_Error</th>
<th style="text-align: center;">t_value</th>
<th style="text-align: center;">CI_lower</th>
<th style="text-align: center;">CI_upper</th>
<th style="text-align: center;">p_value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: center;">26.523</td>
<td style="text-align: center;">0.638</td>
<td style="text-align: center;">41.555</td>
<td style="text-align: center;">25.275</td>
<td style="text-align: center;">27.771</td>
<td style="text-align: center;">0e+00</td>
</tr>
<tr class="even">
<td style="text-align: left;">VISITJ4</td>
<td style="text-align: center;">-2.889</td>
<td style="text-align: center;">0.498</td>
<td style="text-align: center;">-5.796</td>
<td style="text-align: center;">-3.863</td>
<td style="text-align: center;">-1.914</td>
<td style="text-align: center;">0e+00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">VISITJ7</td>
<td style="text-align: center;">-7.142</td>
<td style="text-align: center;">0.502</td>
<td style="text-align: center;">-14.223</td>
<td style="text-align: center;">-8.123</td>
<td style="text-align: center;">-6.160</td>
<td style="text-align: center;">0e+00</td>
</tr>
<tr class="even">
<td style="text-align: left;">VISITJ14</td>
<td style="text-align: center;">-11.250</td>
<td style="text-align: center;">0.506</td>
<td style="text-align: center;">-22.237</td>
<td style="text-align: center;">-12.238</td>
<td style="text-align: center;">-10.261</td>
<td style="text-align: center;">0e+00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">VISITJ21</td>
<td style="text-align: center;">-13.607</td>
<td style="text-align: center;">0.511</td>
<td style="text-align: center;">-26.643</td>
<td style="text-align: center;">-14.605</td>
<td style="text-align: center;">-12.609</td>
<td style="text-align: center;">0e+00</td>
</tr>
<tr class="even">
<td style="text-align: left;">VISITJ28</td>
<td style="text-align: center;">-16.298</td>
<td style="text-align: center;">0.513</td>
<td style="text-align: center;">-31.759</td>
<td style="text-align: center;">-17.301</td>
<td style="text-align: center;">-15.295</td>
<td style="text-align: center;">0e+00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">VISITJ42</td>
<td style="text-align: center;">-18.546</td>
<td style="text-align: center;">0.519</td>
<td style="text-align: center;">-35.704</td>
<td style="text-align: center;">-19.561</td>
<td style="text-align: center;">-17.530</td>
<td style="text-align: center;">0e+00</td>
</tr>
<tr class="even">
<td style="text-align: left;">VISITJ56</td>
<td style="text-align: center;">-20.010</td>
<td style="text-align: center;">0.522</td>
<td style="text-align: center;">-38.333</td>
<td style="text-align: center;">-21.030</td>
<td style="text-align: center;">-18.990</td>
<td style="text-align: center;">0e+00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">GROUPE</td>
<td style="text-align: center;">2.883</td>
<td style="text-align: center;">0.795</td>
<td style="text-align: center;">3.627</td>
<td style="text-align: center;">1.324</td>
<td style="text-align: center;">4.440</td>
<td style="text-align: center;">4e-04</td>
</tr>
</tbody>
</table>
<ul>
<li><p>La t-value et la p-value de l’intercept n’ont pas d’intérêt ici, car le test de Wald pour l’intercept n’a pas de signification pratique, il teste l’hypothèse H0 : intercept = 0, ce qui n’a pas de sens dans ce contexte.</p></li>
<li><p>Intercept (26.523) : score moyen estimé à J0 dans le groupe de référence (groupe 0).</p></li>
<li><p>Effet du temps (VISIT) : tous les coefficients VISITJx sont négatifs et significatifs → le score diminue significativement par rapport à J0. À J56, la baisse moyenne est de 20.010 points (IC95% [-21.030 ; -18.990]).</p>
<ul>
<li>NB : ici l’effet du temps est fait quelque soit le groupe !</li>
</ul></li>
<li><p>Effet du groupe (GROUPE = 2.883) : à visite donnée, le groupe 1 a en moyenne +2.883 points de score par rapport au groupe 0 (IC95% [1.324 ; 4.440], p = 0.0004), donc des scores plus élevés en moyenne sur l’ensemble du suivi.</p></li>
</ul>
<p>Ce modèle décrit une amélioration globale au cours du temps et un décalage moyen entre groupes, mais il ne permet pas de conclure sur une différence de réponse “en pente” entre groupes (il faut le modèle avec interaction VISIT×GROUPE pour ça)</p>
</section>
<section id="modèle-mixte-sans-interaction-avec-visit-comme-variable-continue" class="level5" data-number="4.4.2.1.2">
<h5 data-number="4.4.2.1.2" class="anchored" data-anchor-id="modèle-mixte-sans-interaction-avec-visit-comme-variable-continue"><span class="header-section-number">4.4.2.1.2</span> Modèle mixte sans interaction avec <code>VISIT</code> comme variable continue</h5>
<table class="caption-top table">
<caption>Estimation des coefficients du modèle mixte sans interaction entre VISIT (continue) et GROUPE</caption>
<colgroup>
<col style="width: 16%">
<col style="width: 14%">
<col style="width: 15%">
<col style="width: 12%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Coefficient</th>
<th style="text-align: center;">Estimate</th>
<th style="text-align: center;">Std_Error</th>
<th style="text-align: center;">t_value</th>
<th style="text-align: center;">CI_lower</th>
<th style="text-align: center;">CI_upper</th>
<th style="text-align: center;">p_value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: center;">22.968</td>
<td style="text-align: center;">0.581</td>
<td style="text-align: center;">39.543</td>
<td style="text-align: center;">21.831</td>
<td style="text-align: center;">24.106</td>
<td style="text-align: center;">0e+00</td>
</tr>
<tr class="even">
<td style="text-align: left;">VISIT_num</td>
<td style="text-align: center;">-0.352</td>
<td style="text-align: center;">0.009</td>
<td style="text-align: center;">-40.792</td>
<td style="text-align: center;">-0.369</td>
<td style="text-align: center;">-0.335</td>
<td style="text-align: center;">0e+00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">GROUPE</td>
<td style="text-align: center;">2.997</td>
<td style="text-align: center;">0.799</td>
<td style="text-align: center;">3.752</td>
<td style="text-align: center;">1.431</td>
<td style="text-align: center;">4.562</td>
<td style="text-align: center;">3e-04</td>
</tr>
</tbody>
</table>
<ul>
<li><p>Intercept = 22.968 : score HDRS prédit pour le groupe de référence (groupe 0) quand VISIT_num = 0 (jour 0), selon le modèle linéaire en jours. Ce n’est pas forcément égal à la moyenne empirique à J0.</p>
<ul>
<li>NB : l’intercept correspond donc ici à la valeur prédite par la droite ajustée sur toutes les visites !</li>
</ul></li>
<li><p>VISIT_num = −0.352 : le score diminue en moyenne de 0.352 point par jour (IC95% [−0.369 ; −0.335], p&lt;0.001). Sur 56 jours, ça correspond à une baisse attendue d’environ 0.352×56 ≈ 19.7 points.</p></li>
<li><p>GROUPE = +2.997 : à temps donné (même jour), le groupe 1 a un score moyen plus élevé d’environ 3 points que le groupe 0 (IC95% [1.431 ; 4.562], p=0.0003). Sans interaction, cette différence est supposée constante dans le temps.</p></li>
</ul>
<p>Le score baisse avec le temps (modélisé linéairement en jours) et le groupe 1 reste en moyenne plus haut que le groupe 0 ; ce modèle ne teste pas une différence d’évolution entre groupes (il faudrait ajouter l’interaction VISIT_num * GROUPE).</p>
</section>
</section>
<section id="modèle-mixte-avec-interaction" class="level4" data-number="4.4.2.2">
<h4 data-number="4.4.2.2" class="anchored" data-anchor-id="modèle-mixte-avec-interaction"><span class="header-section-number">4.4.2.2</span> Modèle mixte avec interaction</h4>
<section id="modèle-mixte-avec-interaction-avec-visit-comme-facteur-et-j0-comme-référence" class="level5" data-number="4.4.2.2.1">
<h5 data-number="4.4.2.2.1" class="anchored" data-anchor-id="modèle-mixte-avec-interaction-avec-visit-comme-facteur-et-j0-comme-référence"><span class="header-section-number">4.4.2.2.1</span> Modèle mixte avec interaction avec <code>VISIT</code> comme facteur et J0 comme référence</h5>
<table class="caption-top table">
<caption>Estimation des coefficients du modèle mixte avec interaction entre VISIT (facteur) et GROUPE</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Coefficient</th>
<th style="text-align: center;">Estimate</th>
<th style="text-align: center;">Std_Error</th>
<th style="text-align: center;">t_value</th>
<th style="text-align: center;">p_value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: center;">28.053</td>
<td style="text-align: center;">0.699</td>
<td style="text-align: center;">40.115</td>
<td style="text-align: center;">0.0000</td>
</tr>
<tr class="even">
<td style="text-align: left;">VISITJ4</td>
<td style="text-align: center;">-3.364</td>
<td style="text-align: center;">0.674</td>
<td style="text-align: center;">-4.990</td>
<td style="text-align: center;">0.0000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">VISITJ7</td>
<td style="text-align: center;">-8.663</td>
<td style="text-align: center;">0.677</td>
<td style="text-align: center;">-12.790</td>
<td style="text-align: center;">0.0000</td>
</tr>
<tr class="even">
<td style="text-align: left;">VISITJ14</td>
<td style="text-align: center;">-12.587</td>
<td style="text-align: center;">0.680</td>
<td style="text-align: center;">-18.497</td>
<td style="text-align: center;">0.0000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">VISITJ21</td>
<td style="text-align: center;">-15.640</td>
<td style="text-align: center;">0.683</td>
<td style="text-align: center;">-22.882</td>
<td style="text-align: center;">0.0000</td>
</tr>
<tr class="even">
<td style="text-align: left;">VISITJ28</td>
<td style="text-align: center;">-18.875</td>
<td style="text-align: center;">0.686</td>
<td style="text-align: center;">-27.495</td>
<td style="text-align: center;">0.0000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">VISITJ42</td>
<td style="text-align: center;">-21.328</td>
<td style="text-align: center;">0.696</td>
<td style="text-align: center;">-30.654</td>
<td style="text-align: center;">0.0000</td>
</tr>
<tr class="even">
<td style="text-align: left;">VISITJ56</td>
<td style="text-align: center;">-22.307</td>
<td style="text-align: center;">0.699</td>
<td style="text-align: center;">-31.914</td>
<td style="text-align: center;">0.0000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">GROUPE</td>
<td style="text-align: center;">-0.265</td>
<td style="text-align: center;">1.003</td>
<td style="text-align: center;">-0.264</td>
<td style="text-align: center;">0.7920</td>
</tr>
<tr class="even">
<td style="text-align: left;">VISITJ4:GROUPE</td>
<td style="text-align: center;">0.949</td>
<td style="text-align: center;">0.969</td>
<td style="text-align: center;">0.979</td>
<td style="text-align: center;">0.3278</td>
</tr>
<tr class="odd">
<td style="text-align: left;">VISITJ7:GROUPE</td>
<td style="text-align: center;">3.141</td>
<td style="text-align: center;">0.977</td>
<td style="text-align: center;">3.216</td>
<td style="text-align: center;">0.0013</td>
</tr>
<tr class="even">
<td style="text-align: left;">VISITJ14:GROUPE</td>
<td style="text-align: center;">2.778</td>
<td style="text-align: center;">0.984</td>
<td style="text-align: center;">2.822</td>
<td style="text-align: center;">0.0049</td>
</tr>
<tr class="odd">
<td style="text-align: left;">VISITJ21:GROUPE</td>
<td style="text-align: center;">4.289</td>
<td style="text-align: center;">0.994</td>
<td style="text-align: center;">4.313</td>
<td style="text-align: center;">0.0000</td>
</tr>
<tr class="even">
<td style="text-align: left;">VISITJ28:GROUPE</td>
<td style="text-align: center;">5.464</td>
<td style="text-align: center;">0.999</td>
<td style="text-align: center;">5.469</td>
<td style="text-align: center;">0.0000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">VISITJ42:GROUPE</td>
<td style="text-align: center;">5.889</td>
<td style="text-align: center;">1.011</td>
<td style="text-align: center;">5.824</td>
<td style="text-align: center;">0.0000</td>
</tr>
<tr class="even">
<td style="text-align: left;">VISITJ56:GROUPE</td>
<td style="text-align: center;">4.853</td>
<td style="text-align: center;">1.016</td>
<td style="text-align: center;">4.775</td>
<td style="text-align: center;">0.0000</td>
</tr>
</tbody>
</table>
</section>
<section id="modèle-mixte-avec-interaction-avec-visit-comme-variable-continue" class="level5" data-number="4.4.2.2.2">
<h5 data-number="4.4.2.2.2" class="anchored" data-anchor-id="modèle-mixte-avec-interaction-avec-visit-comme-variable-continue"><span class="header-section-number">4.4.2.2.2</span> Modèle mixte avec interaction avec <code>VISIT</code> comme variable continue</h5>
<table class="caption-top table">
<caption>Estimation des coefficients du modèle mixte avec interaction entre VISIT (continue) et GROUPE</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Coefficient</th>
<th style="text-align: center;">Estimate</th>
<th style="text-align: center;">Std_Error</th>
<th style="text-align: center;">t_value</th>
<th style="text-align: center;">p_value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: center;">23.807</td>
<td style="text-align: center;">0.600</td>
<td style="text-align: center;">39.669</td>
<td style="text-align: center;">0.0000</td>
</tr>
<tr class="even">
<td style="text-align: left;">VISIT_num</td>
<td style="text-align: center;">-0.394</td>
<td style="text-align: center;">0.012</td>
<td style="text-align: center;">-33.792</td>
<td style="text-align: center;">0.0000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">GROUPE</td>
<td style="text-align: center;">1.251</td>
<td style="text-align: center;">0.863</td>
<td style="text-align: center;">1.450</td>
<td style="text-align: center;">0.1486</td>
</tr>
<tr class="even">
<td style="text-align: left;">VISIT_num:GROUPE</td>
<td style="text-align: center;">0.090</td>
<td style="text-align: center;">0.017</td>
<td style="text-align: center;">5.283</td>
<td style="text-align: center;">0.0000</td>
</tr>
</tbody>
</table>
</section>
<section id="test-de-leffet-dinteraction-par-rapport-au-modèle-sans-interaction" class="level5" data-number="4.4.2.2.3">
<h5 data-number="4.4.2.2.3" class="anchored" data-anchor-id="test-de-leffet-dinteraction-par-rapport-au-modèle-sans-interaction"><span class="header-section-number">4.4.2.2.3</span> Test de l’effet d’interaction par rapport au modèle sans interaction</h5>
<p>Pour tester l’effet d’interaction, on peut faire un test de rapport de vraisemblance entre le modèle avec interaction et le modèle sans interaction.</p>
<p>Utilisation de la fonction <code>drop1</code> pour ça :</p>
<p>Single term deletions using Satterthwaite’s method:</p>
<p>Model: score ~ VISIT * GROUPE + (1 | NUMERO) Sum Sq Mean Sq NumDF DenDF F value Pr(&gt;F)<br>
VISIT:GROUPE 1009.5 144.21 7 897.83 8.7357 2.062e-10 *** — Signif. codes: 0 ‘<em><strong>’ 0.001 ’</strong>’ 0.01 ’</em>’ 0.05 ‘.’ 0.1 ’ ’ 1</p>
</section>
</section>
</section>
</section>
</section>
<section id="annexe-code-r" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Annexe – Code R</h1>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>